### ISSUE TITLE
پشتیبانی از زبان‌های گیلکی

### ISSUE THREAD

**Issue by reza1615** [rastikerdar/vazir-font#10]
در
https://fa.wikipedia.org/w/index.php?title=%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D9%82%D9%87%D9%88%D9%87%E2%80%8C%D8%AE%D8%A7%D9%86%D9%87/%D9%81%D9%86%DB%8C&oldid=16127803#.D9.81.D9.88.D9.86.D8.AA_.DA.AF.DB.8C.D9.84.DA.A9.DB.8C
تعدادی از نویسه‌های گیلکی فهرست شده‌اند که اگر ففونت پشتیبانی کند آنها هم می توانند از آن استفاده کنند
کلا پشتیبانی از زبان‌های ایرانی به نظرم باید در اولویت باشد

**Comment by rastikerdar** [comment]
یکی از دوستان به صورت ایمیل برای این موضوع هماهنگ فرمودند و من نیز گلیف هایی که در ایمیل آمده بود رو اضافه کردم و ایشان نیز تایید. اگر حرف یا نویسه خاصی هست که هنوز اضافه نشده بفرمایید تا اصلاح شود.

با تشکر
