### ISSUE TITLE
نمایش ناصحیح جمع تشدید با الف مقصوره

### ISSUE THREAD

**Issue by ali-hardan** [rastikerdar/vazir-font#103]
<div dir="rtl">
سلام.

این کلمه رو با فونت وزیر ببینید:

آزمّٰایش

بر روی حرف «م»، دو کاراکتر تشدید و الف مقصوره قرار گرفتن و میبینید که بر روی یکدیگر قرار گرفتن و قابل خوندن نیستن.

در فونت‌های Yas و Droid Arabic Naskh آزمایش کردم؛ در اونجا مشکلی نبود.

برای تایپ الف مقصوره در صفحه کلید استاندارد فارسی: Shift + V
</div>

**Comment by rastikerdar** [comment]
سلام. متشکرم برای گزارش این ایراد

**Comment by rastikerdar** [comment]
این ایراد در نسخه جدید مرتفع شد. باز هم سپاس
[rastikerdar.github.io/vazir-font/](https://rastikerdar.github.io/vazir-font/)
