### ISSUE TITLE
درخواست تغییر در نحوه نامگذاری وزن‌ها

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/vazir-font#104]
درود مجدد خدمت صابر عزیز
صابر جان در وزن‌های ریگولار شما تنها از نام فونت در اسم فایل قرار استفاده می‌کنید(Vazir.ttf) که این از لحاظ استاندارد نامگذاری در وزن‌های فونت‌ها اشتباه است.
نحوه صحیح نام‌گذاری بهتر است بصورت زیر باشد:
```
Vazir-thin.ttf
Vazir-light.ttf
Vazir-regular.ttf
...
Vazir-bold.ttf
...
```

در صورت صلاح دید پیشنهاد می‌کنم این مورد را بر اساس استاندارد‌های تعریف شده اعمال کنید.
با تشکر

**Comment by rastikerdar** [comment]
سلام صالح عزیز. کاملا درست می‌گید. من از همان اول اشتباه کردم ولی خب الان تغییرش ممکنه برخی رو به زحمت بیندازه. مثلا مجبور بشن موقع آپدیت اسکریپت‌هاشون رو تغییر بدن و یا دردسرهایی که من الان نمی‌دونم. اما حرفتون کاملا درسته و باید ساختار یکدست رعایت میشد. بنابراین اجازه بدین ایشو باز بمونه.

**Comment by sajaddp** [comment]
@rastikerdar 
بنده با شما موافقم و خواهشم این هست در صورت امکان اسم فایل ها رو ویرایش نکنید و به همین صورت بمونه

**Comment by mahdi-alavi** [comment]
@rastikerdar 
می‌تونید فونت‌ها رو توی دو تاپوشه مجزا قرار بدید
یه پوشه قدیمی با نام‌هایی که در حال حاضر وجود داره
به پوشه هم با نام گذاری‌های جدید
الان من خودم هم نام‌گذاری‌ها رو تغییر میدم به همون ترتیبی که 
@zoghal
 گفته

**Comment by rastikerdar** [comment]
در نسخه ۲۷ این تغییر انجام شد. با تشکر از شما آقای سوزنچی
