### ISSUE TITLE
استفاده از font-display

### ISSUE THREAD

**Issue by mahdi-alavi** [rastikerdar/vazir-font#106]
`font-display`
 ویژگی‌ هست که باعث میشه قبل از لود کامل فونت اصلی،  یک فونت دیگه که معمولا سیستمی هست فراخوانی بشه
لذا سرعت نمایش محتوا بیشتر میشه
حالا سوال این‌جاست از چه فونتی استفاده بشه که حجم و اندازه فونت بیشترین شباهت رو به فونت وزیر داشته باشه
نمونه استفاده از 
`font-display`
```
@font-face {
  font-family: "vazir";
  font-weight: 400;
  font-style: normal;
  src: url("assets/fonts/Vazir-Regular.woff") format("woff");
  font-display: swap;
}
body {
  font-family: 'vazir', 'Segoe UI', sans-serif;
}
```
در این نمونه قبل از لود کامل فونت وزیر، محتوای سایت با فونت دومی نمایش داده میشه
که یک فونت سیستمی هست
اگر کاربر این فونت رو نداشته باشه، محتوا بر اساس فونت بعدی نمایش داده میشه
ممنون از شما و زحمتی که کشیدید (: 
[اطلاعات بیشتر](https://css-tricks.com/font-display-masses/)

**Comment by mahdi-alavi** [comment]
سلامت باشید
مسئله مهم این هست که در برخی از کتاب‌خونه‌های جی‌کوئری و البته خیلی از جاهای دیگه
هنگامی که صفحه داره لود میشه، ارتفاع اون دیو محاسبه میشه
حالا اگه حجم فونت سیستمی با فونت اصلی متفاوت باشه این محاسبه اشتباه میشه و مشکل پیش میاد
به عنوان نمونه 
[masonry](https://masonry.desandro.com/)
ارتفاع رو محاسبه می‌کنه و بر اساس اون به هر دیو ارتفاع میده

خود فونت 
`dejavu`
بر اساس
`Vera Fonts`
درست شده
و متاسفانه هیچ کدوم از این‌ها فونت سیستمی نیستند
البته هنوز فونت تاهوما رو امتحان نکردم
الان خودم از فونت
`Segoe UI‍`
استفاده می‌کنم که تقریبا نزدیک به فونت وزیر هست و البته یک فونت سیستمی محسوب میشه و مهمتر این‌که به نظرم خیلی از تاهوما زیباتر هست

**Comment by rastikerdar** [comment]
دو تا مشکل وجود داره:
۱. متریک‌های فونت‌های فارسی با هم متفاوت است. برخی مثل تاهوما و دژاوو و امثالهم تلاش کرده‌اند از قاعده لاتین پیروی کنند اما سایرین برای آزادی و زیبایی در طراحی از متریک‌های دلخواهشان پیروی می‌کنند که عمدتا بزرگتر/بالاتر از لاتین می‌باشد مگر اینکه اندازه تایپ‌فیس رو کوچکتر در نظر بگیرند. اما اگر اندازه ارتفاع خط (لاین-هایت) رو خودتون تنظیم می‌کنید (و نه بر مبنای آنچه که در خود فونت تعریف شده) فونت وزیر بیشتر به تاهوما یا سیگو نزدیک است. معمولا این اندازه را طراحان وب خودشون تنظیم می‌کنند. چه پیکسلی و چه نسبتی.

۲. کشیدگی قلم که عملا در هیچ کدام از قلم‌ها (چه در لاتین و چه در فارسی) یکسان نمی‌باشد. در نتیجه محاسبه مثلا اندازه ارتفاع دیو بر مبنای اندازه قلم در حالتی که امکان چند خطی شدن وجود داشته باشد ممکن است اشتباه از آب در بیاید. چون ممکن است یک جمله با قلم روبوتو در یک خط جا گیرد و با قلم اوپن‌سنس در دو خط.

**Comment by mahdi-alavi** [comment]
با این وجود پیشنهاد می‌کنم در بخش نحوه استفاده از فونت، ویژگی 
`font-display`
رو هم اضافه کنید
حالا یا با فونت تاهوما یا فونت 
`Segoe UI‍`
بازم ممنون از زحمتی که برای این فونت کشیدید
بارها از این فونت زیبا در کارهام استفاده کردم
🥇

**Comment by rastikerdar** [comment]
این ویژگی در نسخه ۲۷ اضافه شده. ممنونم از شما برای معرفی آن.
