### ISSUE TITLE
حروف پشتو

### ISSUE THREAD

**Issue by ebraminio** [rastikerdar/vazir-font#109]
سلام! از اونجایی که فارسی در افغانستان با زبانی دیگر یعنی پشتو به کار می‌رود و در برنامه‌ای که کاربران پیشنهاد استفاده از فونت وزیر داده‌اند پشتیبانی از پشتو نیز وجود دارد، خیلی خوب می‌شه اگه نویسه‌های پشتو «ټ څ ځ ډ ړ ږ ښ ګ ڼ ي ې ی ۍ» هم در فونت پشتیبانی بشه، ممنون

**Comment by rastikerdar** [comment]
سلام
حروف پشتو رو به صورت آزمایشی به وزیر اضافه کردم. به نظرتون مناسبه؟
متن رو از [اینجا](https://ps.wikipedia.org/wiki/%D9%BE%DA%9A%D8%AA%D9%88) گرفتم.
![Screenshot at 2020-05-12 20-14-48](https://user-images.githubusercontent.com/3116038/81715357-65f3d680-948d-11ea-8677-04eadad17028.png)

**Comment by ebraminio** [comment]
به نظر که عالیه! ممنونم

**Comment by rastikerdar** [comment]
از شما برای این ایشو تشکر می‌کنم. حروف پشتو به نسخه ۲۶ اضافه شد. اگر ایرادی دیدین ممنون میشم اطلاع بدین.
[https://github.com/rastikerdar/vazir-font/releases](https://github.com/rastikerdar/vazir-font/releases)
