### ISSUE TITLE
ایجاد بسته Bower 

### ISSUE THREAD

**Issue by javadparvaresh** [rastikerdar/vazir-font#11]
بسیار بهتر می شود اگر بسته bower  نیز ایجاد گردد.

**Comment by aziz** [comment]
<p dir="rtl" align="right">
فکر بدی نیست. و البته از اون مهمتر خود NPM 
باید وقت گذاشت و یک بیلد تول خوب درست کرد که هم پگیج‌ها رو دست کنه و پابلیش کنه
</p>

**Comment by aziz** [comment]
اولیتش ولی به نظرم پایینه. 
اولویت اول باید خود قلم باشه.

**Comment by javadparvaresh** [comment]
اونکه صد درصد
اما اگر بتونیم موازی این کار رو انجام بدیم شدنی می شه.
من یه برنچ از پروژه شما ایجاد می کنم و کارای bower و npm رو انجام می دم. 
بعد اگر تمایل داشتین می تونین به branch خوتون اضافه کنین.

**Comment by aziz** [comment]
فکر کنم بهتره این کار رو روی فونت صمیم انجام بدی چون اون از تگ و ریلیس برنچ استفاده می‌کنه که هنوز رو این انجام نشده.

**Comment by rastikerdar** [comment]
بالاخره ساختار این ریپو هم عوض شد.

اولا تشکر می کنم برای باز شدن این ایشو. فکر خیلی خوبیه اگر کمک کنید.
برنچ یا شاخه دولوپ رو برای همین تغییرات ایجاد کردم. هر گونه تغییری صلاح می دونید توی دولوپ انجام بدید موقع انتشار ادغام می کنیم.
develop

باز هم ممنون

**Comment by behdad222** [comment]
@ebraminio
بیلدری که ردیف کردی رو میتونی اینجا هم بزاری؟

**Comment by ebraminio** [comment]
@behdad222 من کار خاصی نکرده‌ام و فقط تنظیمات خیلی اولیهٔ [این مجموعه](https://github.com/googlefonts/fontbakery ) را قرار دادم که احتمالاً به راحتی قابل تنظیم در پروژه‌های مختلف باشد
