### ISSUE TITLE
فاصله اعداد

### ISSUE THREAD

**Issue by TeslaITIR** [rastikerdar/vazir-font#110]
درود خدمت همه دوستان

من در وب دارم از فونت وزیر استفاده میکنم که دیروز در طراحی یک قسمت از سایت دیدم که اصلا فاصله اعداد از لبه های صفحه های صفحه به یک اندازه نیست و خیلی بد نشون میده
برای بهتر متوجه شدن عکس زیر رو مشاهده کنید:
![vazir](https://user-images.githubusercontent.com/47227619/52469984-311a1500-2ba2-11e9-8279-7fcdaa45ab1b.png)
همانطور که میبیند اصلا فاصله بالا و پایین هر عدد با گوشه های صفحه یکسان نیست
اما در یک فونت خارجی به نام Droid Serif فاصله اعداد از گوشه های صفحه یکسان هست
برای بهتر متوجه شدن عکس زیر رو مشاهده کنید:
![droid serif](https://user-images.githubusercontent.com/47227619/52470214-c7e6d180-2ba2-11e9-88b4-876f9f712547.png)

نکته: انداز تصاویر اصلا هیچ ربطی به این موضوع نداره

حالا اگه میشه دوستان یا فونت رو درست کنید یا یه راه حلی به من معرفی کنید.
تشکر از همه دوستان

**Comment by typoman** [comment]
به نکته‌ی جالبی اشاره کردی. چون این نکته معمولن در فونت‌های فارسی این در نظر گرفته نمی‌شه (یا حداقل من بهش اهمیت نمی‌دادم)، یا بخاطر اینکه در کنار فونت لاتین هست اسندر و دیسندر فارسی با لاتین فرق داره و اگه دیسندر رو کم کنه سازنده‌ی فونت؛ ممکنه در برخی از برنامه‌ها پایین حروف بریده بشه و ناقص دیده بشه. می‌شه درستش کرد، شایدم نشه، بسته به طراحی کاراکترها داره.

**Comment by typoman** [comment]
راه حل، تغییر دادن این دو پارامتر پایین هست. می‌تونی از ttx استفاده کنی.

`Ascender, Descender`

ttx:
https://github.com/fonttools/fonttools

**Comment by TeslaITIR** [comment]
درود و خسته نباشید
یعنی چی `Ascender, Descender` رو کاهش بدم؟
منظورتون در فونت هست؟
من زیاد بلد نیستم اگه خودتون بلدید میشه زحمتش رو بکشید

**Comment by rastikerdar** [comment]
درود
همانطور که جناب اسلامی به درستی اشاره فرمودند و در تصویر مشاهده می‌نمایید حروف فارسی/عربی به همراه اعراب به فضای بیشتری نسبت به لاتین برای نمایش احتیاج دارند. در فونت‌های مختلف اعم از عربی و فارسی تنظیمات متفاوت است. و خب مسئله‌ایست دردسرآفرین و اسباب ناهماهنگی.
![screenshot at 2019-02-09 21-02-16](https://user-images.githubusercontent.com/3116038/52524073-06b57e00-2cae-11e9-8565-1cb30ebb2a60.png)

مثلا این متن رو توی این صفحه روی فونت‌های مختلف با انتخاب کردنش تست کنید:
`اَپلِّلُحِhg8`
[rastikerdar.github.io/compare-fonts/](https://rastikerdar.github.io/compare-fonts/)

**Comment by typoman** [comment]
یک مسئله‌ی دیگه هم که این محدودیت ایجاد می‌کنه اینه که به صورت معمول وقتی یک کلمه‌ی فارسی داخل یک دکمه یا در هایلایت قرار می‌گیره، فضای منفی بالا و پائینش یکسان به نظر نمی‌رسه. یک کاری که در اپل انجام دادن این بود که در فونت‌های عربی که در سیستمشون استفاده ‌می‌کنن، کرسی حروف عربی رو یک مقدار بالاتر از بیس‌لاین لاتین گذاشتن (این در فونت جدیدشون بیشتر دیده می‌شه که من نصب ندارم الآن). این باعث می‌شه کلمات فارسی یه مقدار بالا بیان و این مشکل تا حدودی حل بشه.

<img width="408" alt="screen shot 2019-02-10 at 00 47 59" src="https://user-images.githubusercontent.com/4546443/52527758-383e4180-2cce-11e9-950e-c6fc9bee8aa2.png">

**Comment by rastikerdar** [comment]
در حد جزیی شاید بشه اما فکر نمی‌کنم برای وزیر یا امثالهم موثر واقع بشه. مثلا در همین تصویر شما، شکل «ـی» به بالا منتقل شده یا همچنین توی تاهوما و دژاوو حروف پایین خط کرسی از دیسندر تجاوز نکرده‌اند. توی وزیر نسخه یک این موضوع رعایت شده بود و فاصله بالا و پایین یکسان بود اما توی نسخه‌های بعد تجدید‌نظر شد. نمی‌دونم شاید بهتر بود همون مسیر ادامه پیدا می‌کرد.
وزیر۱:
![screenshot at 2019-02-10 13-37-49](https://user-images.githubusercontent.com/3116038/52532366-352c6b00-2d39-11e9-909f-25c59580769f.png)

وزیر۱۹:
![screenshot at 2019-02-10 13-38-13](https://user-images.githubusercontent.com/3116038/52532376-47a6a480-2d39-11e9-8b3e-b1a417dc0ebe.png)

**Comment by typoman** [comment]
چطوره کل شکل گلیف‌های لاتین رو در این فونت پائین بکشین؟ فکر نمی‌کنم مشکلی ایجاد بکنه.

**Comment by TeslaITIR** [comment]
درود خدمت شما دو نفر گرامی
ببخشید که من در بحث های شما دخالت نمیکنم چون واقعا اطلاعات زیادی درباره فونت ندارم 😅😅
بازم معذرت میخوام که نمیتوانم نظری مفید بدم

**Comment by typoman** [comment]
تازه متوجه شدم اگه تمام گلیف‌های لاتین رو پائین بکشین بعد علامات نقطه گذاری با فارسی مشکل پیدا می‌کنه. شاید علامات نقطه‌گذاری رو بشه سر جاش گذاشت و بقیه حروف لاتین رو دستکاری کرد؟ یه مقدار پیچیده شد! اما فکر می‌کنم اکثر کاربرها از این فونت برای نوشتن جملات لاتین استفاده نکنند.

**Comment by TeslaITIR** [comment]
من بر خلاف شما فکر میکنم مهندس(البته با عرض پوزش) در سایت هایی امروزی هم از فارسی استفاده میشه و هم از انگلیسی و در بعضی جاها هم از انگلیسی فقط استفاده میکنند و اغلب از یک فونت استفاده میکنند
به نظر من وزیر 1 بهتر بوده از وزیر 19 در این مورد

**Comment by typoman** [comment]
درسته اما این فونت برای فارسی ساخته شده و فارسی اولویت داره. اگه قرار باشه که فاصله‌ی بین بالا و پائین حروف خوب به نظر بیاد یا باید لاتین خودشو وفق بده یا فارسی نباید تغییری داده بشه. فارسی اینجا اولویت داره.

**Comment by zoghal** [comment]
@typoman  دیدم بهمن داره پاسخ میده کلی خوشحال شدم، گفتم یک سلامی بدم و بگم ایول 👍

**Comment by typoman** [comment]
نظر شخصی من این هست که فضای بالا و پائین فارسی الآن خوب به نظر می‌رسه؛ لاتین هست که مشکل داره. چند راه حل به ذهن من می‌رسه:


. اسندر افزایش داده بشه، این باعث می‌شه فضای بالای حروف فارسی بد بشه ولی بالای لاتین خوب به نظر میاد.
. حروف لاتین پائین کشیده بشن، این باعث می‌شه که علامات نقطه گذاری برای لاتین درست کار نکنه.
. طراحی حروف لاتین یا فارسی تغییر کنه که هر دو فضای بالا و پائینشون هماهنگ به نظر بیاد. به نظرم این باعث می‌شه که حروف فارسی در بالای کرسی فشرده بشن و حس بچگانه‌ای به خط می‌ده که در تاهومای عربی می‌بینیم.

اینکه این اصلاحات چجوری انجام بشه و بهترین گزینه کدوم هست برای این مسئله رو شاید باید بیشتر بررسی کرد اما به نظر شخصی بنده همه‌ی گزینه‌های بالا مشکلاتی بوجود می‌آره که الآن در این فونت وجود نداره. اگر شما نظر بهتری دارین من استقبال می‌کنم اما هر چقدر فکر می‌کنم به این نتیجه می‌رسم که تصحیح این مشکل بیشتر باعث ایجاد مشکلات جدید می‌شه.

**Comment by rastikerdar** [comment]
۱. اگر قلم رو فشرده‌تر طراحی کنیم که خب همانطور که فرمودید طراحی میره تو فاز تاهوما
۲. اگر ارتفاع اسندر بیشتر بشه شاید بد نباشه اما مشکل اینه که در کل ارتفاع قلم خیلی زیاد میشه و مشکلاتی دیگر اضافه میشه کمااینکه همین الان هم زیاده. ولی منطقا ممکنه
۳. یکی اینکه کلا گلیف‌های لاتین و فارسی رو کوچک‌تر کنیم (با یه کوچولو تغییر در قوس ح) تا به دنبالش بشه دیسندر رو کم کرد که خروجیش این میشه:
**وزیر کوچک‌تر شده**
![screenshot at 2019-02-12 20-31-14](https://user-images.githubusercontent.com/3116038/52653757-dff18480-2f05-11e9-8dbe-c3d83e93ab2f.png)
تو این حالت هم مثل روش دوم فضای خالی بالای حروف فارسی شاید یه کم زیاد به نظر برسه. نمیدونم.


**وزیر فعلی ۱۹**
![screenshot at 2019-02-12 20-33-27](https://user-images.githubusercontent.com/3116038/52653780-f1d32780-2f05-11e9-842e-21baa1e20f90.png)

**Comment by typoman** [comment]
من امروز با همکارم که طراح تایپ لاتین هست این مسئله رو در میون گذاشتم. به نظر اون فضای منفی بالا و پائین لاتین در نسخه‌ی فعلی درست به نظر میاد و فضای منفی نسخه‌ی جدید خیلی غیر عادی (نظر من هم اینه که فارسی در نسخه‌ی فعلی درست به نظر می‌رسه). یعنی تغییرات جدید مشکلات بیشتری ایجاد می‌کنه. این مشکل باید از طریق دیگه‌ای حل بشه. در نظر همکارم این سوال‌ها اول باید جواب داده بشه:

تصویری که در پست اول توسط کاربر نشون داده شده که مشکل داره باید به شکل دقیق تری توضیح داده بشه که چجوری بوجود اومده. در چه نرم‌افزاری (بروزر)؟ با چه کدی؟

بعد اینکه بشه دقیق مشکل شما رو دوباره بوجود آورد، می‌شه راه حل درست‌تری پیشنهاد کرد. در نظرم همکارم حتی تصویر دومی که در پست اول نشون داده شده به شکل عجیبی بالا و پائین حروف فضای مساوی قرار بوجود اومده، شاید بروزر فقط برای این موقیعت اینکارو انجام داده. اگه شما یک حرف لاتین که دیسندر داره مثل g در کنار بقیه اعداد تایپ کنید چه اتفاقی می‌افته؟ ممکنه دیگه فضای مساوی وجود نداشته باشه! بروزرهای مختلف رفتار متفاوتی دارن.

 باید اضافه کنم همکار جز تیمی هست که فونت ‌‌IBM Plex رو طراحی کردن.
لینک به صفحه کاربری همکارم:
@JasperTerra
https://github.com/JasperTerra

**Comment by TeslaITIR** [comment]
من با بروزر opera و firefox و google chrome امتحان کردم
همچنین در مرورگر فایر فاکس با استفاده از ابزار inspect elements و از بخش فونت در جایی که اسم فونت رو نوشته کمی پایین ترش بازم اسم فونت رو نوشته که اگر روی اون موس تون رو ببرید میبینید که اون بخش مربوط به اون رو هایلایت میکنه و میتوانید یه عکس بگیرید و در نرم افزار paint.net این مشکل رو مشاهده کنید
همه این ها جواب یکسانی داره
اما چه کدی زدم رو هم در زیر میذارم
`<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>This is my code</title>

    
    <link rel="stylesheet" href="fonts/vazir.min.css">

    
    <link rel="stylesheet" href="fonts/droid-serif.min.css">

    <style>

        .font-vazir{
	        font-family: 'Vazir';
        }

        .font-droid-serif{
	        font-family: 'Droid-Serif';
        }

    </style>

</head>

<body>

    <p class="font-vazir">400</p>
    <p class="font-droid-serif">400</p>


</body>

</html>`
کد رو کامل گذاشتم که دیگه مشکلی نیاد
اما مهندس یه پیشنهاد میکنم من کد رو قرار دادم به جز فونت ها که اونم فونت وزیر هست و فونت Droid Serif هم در وب موجود هست یا از یه فونت خارجی دیگه استفاده کنید و خودتون هم امتحان کنید

**Comment by rastikerdar** [comment]
یک نسخه با ارتفاع کم برای رفع این مشکل در بسته قلم قرار داده شده.
پوشه UI
https://github.com/rastikerdar/vazir-font/releases
با تشکر از شما
