### ISSUE TITLE
نحوه نمایش الف

### ISSUE THREAD

**Issue by mahdi-alavi** [rastikerdar/vazir-font#114]
حجم حرف الف در حالت‌های مختلف فرق می‌کنه
و به نظر می‌رسه وقتی بدون سرکش استفاده می‌شه
از حالت عادی نازک‌تر میشه
و این حالت وقتی پیش میاد که اندازه فونت کم باشه
![Untitled-1](https://user-images.githubusercontent.com/9952616/54082353-870ce480-4329-11e9-9b4b-b2a074842a4a.png)

---
بعد از این‌که حالت‌های مختلف الف رو داشتم می‌نوشتم
دیدم حرف نون هم در بعضی مواقع نازک‌تر از حالت عادی هست
![Untitled-2](https://user-images.githubusercontent.com/9952616/54082368-e9fe7b80-4329-11e9-9d7d-19b28ef3e158.png)

**Comment by rastikerdar** [comment]
درست می‌فرمایید. این به دلیل شیوه تبدیل مختصات برداری به پیکسلی است که به آن 
Rasterization 
می‌گویند. اگر دقت کنید در سایر فونت‌ها نیز این اتفاق بروز می‌دهد. البته خود طراح هم در هنگام پیاده‌سازی و طراحی باید یک‌سری نکات رو در نظر بگیرد تا این فرآیند تبدیل به خوبی اتفاق بیفتد اما در هر صورت بخشی از این ماجرا اجتناب‌ناپذیر است. خوشبختانه این اتفاق غالبا در اندازه‌های کوچک با تراکم پیکسل پایین‌تر اتفاق می‌افتد.

**Comment by mahdi-alavi** [comment]
بین ا و آ تفاوتی غیر از سرکش هست؟
یکی درست نمایش می‌دی و یک نه

**Comment by rastikerdar** [comment]
توی فونت صرفا ارتفاع «آ» کمتر از «ا» هست اما در ضخامت اختلافی نیست. منظور من از تراکم پیکسل تعداد پیکسل‌هایی که صفحه‌نمایش بتونه برای اندازه مثلا ۱۴ پیکسل نمایش بده هست. معمولا از اون به دی‌پی‌آی و دقیق‌تر پی‌پی‌آی نام می‌برند. مثلا در تصویر شما به نقاط «یـ» دقیت کنید. با این که هر دو دقیقا به یک شکل طراحی شده‌اند اما هنگام نمایش به دلیل محدودیت پیکسل و نحوه تبدیل متفاوت شده‌اند. یکی مربع شده و دیگری لوزی!
![Screenshot at 2019-03-13 10-29-32](https://user-images.githubusercontent.com/3116038/54259444-faf1fb80-457a-11e9-984e-0f7a54d2f207.png)

طراحی مناسب+هینتینگ مناسب+موتور رندر مناسب به نمایش هر چه بهتر قلم می‌تونه کمک می‌کنه. شاید بشه با افزایش میزان هینتینگ کیفیت رو بالا برد اما فکر نمی‌کنم این مشکل زیاد به چشم بیاد.

**Comment by typoman** [comment]
این تصاویری که شما گذاشتی در چه نرم افزار و سیستم عاملی گرفته شده؟ به عنوان مثال هیچ کنترلی روی این نحوه رسترایزشن توی مک وجود نداره. هینتینگ برای ویندوزه.
