### ISSUE TITLE
برای دیفالت فونت کردن این فونت ، چه کاری باید انجام بدم ؟

### ISSUE THREAD

**Issue by kiana-a** [rastikerdar/vazir-font#115]
من این فونت رو روی مانجاروی ۱۸.۰۴ نصب کردم و به هر ترفندی متوصل میشم نمی تونم فونت دیفالت سیستمم که یک فونت نستعلیق هست رو تغییر بدم و فونت وزیر رو جایگزینش کنم. 
چه کاری باید انجام بدم ؟

**Comment by morealaz** [comment]
من اینجا یه توضیحی در این مورد دادم که شاید بدردتون بخوره
https://github.com/omid/Persian-Calendar-for-Gnome-Shell/issues/10#issuecomment-339109199

**Comment by ichbinkiana** [comment]
مرسی ممنون حسابی
