### ISSUE TITLE
«نحوه نمایش «لا

### ISSUE THREAD

**Issue by blackdead263** [rastikerdar/vazir-font#117]
![image](https://user-images.githubusercontent.com/13819151/56042540-86180a00-5d50-11e9-98bd-d503203f6c79.png)
در فونت وزیر کد وقتی حروف الف و لام به هم می‌چسبن، لام زبونه نداره. بهتر است مثل فونت وزیر داشته باشه :)

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو. بهتر است موارد مربوط به فونت وزیرکد در مخزن خودش پیگیری شود. مسیر توسعه وزیرکد از این فونت کاملا جدا می‌باشد. باز هم ممنونم.
