### ISSUE TITLE
مشکلاتی در مورد نامگذاری برخی از گلیفها و نسبتهای رفرنس‌دهی

### ISSUE THREAD

**Issue by aminabedi68** [rastikerdar/vazir-font#123]
سلام صابر جان، خسته نباشی.
من در حال ساخت فونت جدیدی بودم و از وزیر نسخه آخر استفاده میکردم که متوجه اشکالاتی شدم:
- اول اینکه برخی از گلیفها از اسمهای رایج فونت فورج (به صورت unixxxx) استفاده نمیکنن، این وضعیت مشکلات ناشناخته‌ای ممکنه بوجود بیاره، مثلا فونت فورج فکر میکنه کاراکتر متناظر با اون حرف توی فونت وجود نداره. بهتره نامگذاری به فرم مناسبش برگردونده بشه.

![vcxsrv_2019-06-18_14-49-16](https://user-images.githubusercontent.com/25493297/59674305-e32ca380-9177-11e9-8d2e-e5e1e67c9d76.png)
- مشکل دوم مربوط به نسبت رفرنس‌دهی تو ماتریس تبدیل نقاط و بعضی از حروف هست:

![vcxsrv_2019-06-18_14-52-54](https://user-images.githubusercontent.com/25493297/59674560-61894580-9178-11e9-9142-7731af9217cd.png)
دو مورد دیگه هم وجود داره:
1- چرا فرم منحنیها از cubic به quadratic تغییر کرده؟ آیا داری از هینتینگ اختصاصی استفاده میکنی؟
2- چرا نقاط و هندلها رو roun to int نکردی؟

**Comment by rastikerdar** [comment]
سلام امین جان 
ممنونم برای این ایشو
- تنبلی. چون دیدم داره کار میکنه دیگه همه رو درست نکردم. حق با شماست
- این اشتباهیه که هنگام تغییر سایز قلم مرتکب شدم. باز چون دیدم همه به صورت یکسان تغییر کردند دستش نزدم. البته الان دیدم نقطهٔ حرف ز نسبتش با بقیه فرق داره! همون چند سال قبل باید درستش می‌کردم. برایش شبنم و ساحل درستشون کردم اما وزیر و صمیم خیر. در هر صورت حق با شماست.
۱- راستش یادم نمیاد چرا! و اینکه به توصیه چه کسی یا کدام مطلب این حالت رو انتخاب کردم. حرف چند سال پیشه. شاید چون دیدم سایر فونت‌ها این حالت رو گذاشتن من هم گذاشتم. نمی دونم. توصیه خودت چیه؟ هینتینگ رو هم من خودم انجام نمی‌دم. با همون برنامه معروف یکجا به کل قلم اضافه می‌کنم.
۲- شاید تنبلی یا فراموشی. باز هم حق با شماست

زمان زیادی می‌خواد تا بشینم همه این موارد رو اصلاح کنم.
بدهی‌های فنی :)

**Comment by aminabedi68** [comment]
تنبلی که نمیشه گفت، با این همه فونت کار خیلی زیادی برای انجام دادن وجود داره، قابل درکه :)
اما وزیر زیاد بهش مراجعه میشه برای طراحی و یادگیری، یه خورده ضرورت رعایت مسائل فنی توش بیشتره وگرنه عملکردش مخصوصا توی وب عالیه.
در مورد حالت منحنیهای بِزیر، کسی دیگه از quadratic استفاده نمیکنه، دلیلش محدودیت طراحی و سختی ویرایشه.
و اگه هینتینگت اختصاصی نیست(مثلا با VOLT یا خود فونت فورج) لزومی نداره و فقط کارو سختتر میکنه.
و دقیقا آره، با تعریف بدهی فنی جور در میاد :+1:

**Comment by rastikerdar** [comment]
توی نسخه جدید تمامی مواردی که اشاره فرمودید رفع گردید. خیلی متشکرم برای گزارش این ایشو. اگر باز هم ایرادی دیدین ممنون میشم گزارش بدین.

**Comment by aminabedi68** [comment]
ممنون از شما صابرجان :) به روی چشم
