### ISSUE TITLE
مسدود شدن حساب

### ISSUE THREAD

**Issue by mahdi-alavi** [rastikerdar/vazir-font#126]
سلام
به زودی تمام حساب‌های ایران مسدود میشه
شما برنامه‌ای داری تا پروژه رو جای دیگه منتقل کنی؟

**Comment by rastikerdar** [comment]
سلام
برای من هم این پیام زرد رنگه بالای صفحه نوشته که این حساب محدود شده. ببینیم چی میشه. شاید مجبور بشیم مهاجرت کنیم.

**Comment by sajaddp** [comment]
سلام
این موضوع مربوط به محدود شدن ریپازیتوری های خصوصی و امکانات تجاری هست. فعلا بابت ریپازیتوری های عمومی مسئله ای وجود نداره.

**Comment by mahdi-alavi** [comment]
صفحات که برای ایجاد سایت هم استفاده شدن
به زودی بسته می‌شن

**Comment by typoman** [comment]
فقط ریپو‌هایی که خصوصی هستند مشکل پیدا می‌کنن. این ریپو مشکل نخواهد داشت.
