### ISSUE TITLE
نحوه نمایش  اعداد به صورت فارسی

### ISSUE THREAD

**Issue by mrmmg** [rastikerdar/vazir-font#128]
با سلام
برای تنظیم فونت و نمایش اعداد به صورت فارسی باید کدام یک از فایل های موجود در پکیج را در فایل استایل (css) اضافه کنیم؟

چون اعداد در فایل html به صورت انگلیسی وارد می شوند، حتی با وجود کیبورد استاندارد ویندوز باز هم اعداد انگلیسی هستند.
ممنون میشم راهنمایی کنید

**Comment by rastikerdar** [comment]
سلام
از پوشه Farsi-Digits
یا از این آدرس:
https://cdn.rawgit.com/rastikerdar/vazir-font/v[X.Y.Z]/dist/Farsi-Digits/Vazir-FD.woff2
جای v[X.Y.Z] عدد ورژن رو بزارید.
بقیه حالت‌ها هم مثل ضخیم و متوسط و ... هم می‌تونید اضافه کنید.

**Comment by mhorizon** [comment]
سلام وقتی با npm فونت را نصب میکنیم چگونه از اعداد فارسی استفاده کنیم؟

**Comment by rastikerdar** [comment]
`import 'vazir-font/dist/Farsi-Digits/font-face-FD.css';`
توی سی اس اس هاتون هم فونت رو بزارید
`‍font-family: Vazir FD;‍`
