### ISSUE TITLE
ضعف کوچک در قوس دوم "ی" و یک پیشنهاد

### ISSUE THREAD

**Issue by PAPIONbit** [rastikerdar/vazir-font#131]
سلام و درود به شما

واقعا دست مریزاد
بسیار کار های شما با ارزش و ستودنیه و واقعا جاش خالی بود

فقط:

- حرف **ی** چسبیده آخر، مثل **ملی** دقیقا در قسمتی که قوس دومش در پایین راست، شروع میشه یک مقدار باریکتر شده که به چشم خوب نمیاد و این ضعف هم تقریبا در همه سری فونت های شما وجود داره.

و یک درخواست:

- تقاضا دارم با همین اسلوب فونت وزیر یا صمیم یا ناهید، روی یک فونت کار کنید که پایه اش سری سنس باشه.
sans-serif
نه با اسلوب ایران سنس.
اما به نحوی سمتریکال و متقارن باشه و سر خط تمام شده باشه و در عین حال این ظرافت های زیبا رو هم داشته باشه تا افرادی که به دنبال خطوط یکسان و منطقی هستند بتونن ازش استفاده کنن.

موفق و پیروز باشید

**Comment by rastikerdar** [comment]
سلام و سپاس
تشکر می‌کنم برای ایشو.
در مورد موضوع اول اگر تصویر می‌گذاشتید بهتر مشخص می‌شد که دقیقا به کدام قسمت اشاره می‌فرمایید. موضوع دوم رو هم متاسفانه متوجه نشدم.

**Comment by PAPIONbit** [comment]
سپاس از توجه شما

لطفا به تصویر زیر دقت بفرمایید. مشکل بسیار جزئیسیت اما در ناحیه ای که مشخص شده، در ابعاد کوچک، یه کمرنگتر دیده میشه
![vazir-p1](https://user-images.githubusercontent.com/47592258/67774101-09d9df80-fa72-11e9-916e-1c1bec3a6ef1.jpg)
![vazir-p2](https://user-images.githubusercontent.com/47592258/67774133-13634780-fa72-11e9-9627-05676bab9917.jpg)
وزن کلی خط در اونجا کمتر هست.

وقتی در کورل آنالیزش بکنیم هم این مشخصتر میشه:
![iranni](https://user-images.githubusercontent.com/47592258/67774278-51f90200-fa72-11e9-84b3-ecccb03b18f0.jpg)
نقاط سبز هم وزن هستند اما نقاط قرمز خیر.

ظاهرا نقطه ی شماره 2 زیباترش کرده اما نقطه ی 1 اگر توجه کنید دقیقا در محل بیرون زدگی دایره (که آبی کمرنگ شده)، باعث این شده که از دور، کمی خط ضعیف باشه

و همچنین نکته ی دیگه ای هم مشخص شد که به نظرم میرسه در مرورگرها کمتر و در کورل بیشتر، حس میشه و اون کم بودن فاصله حرف **ر** چسبان به **ی** چسبیده در ابتدا هست.
که اون حرف رو برای این منظور قرمز کردم

من به نظرم رسید هر دو مورد رو میشه اصلاحش کرد به این شکل:
![fixlook](https://user-images.githubusercontent.com/47592258/67775139-b9fc1800-fa73-11e9-8304-6740f9a96266.jpg)
![fixlooksmall](https://user-images.githubusercontent.com/47592258/67775140-bb2d4500-fa73-11e9-8d2a-7322439eea4e.jpg)


مورد **ی** این در وزیر کد (فونت بسیار دوست داشتنی) هم هست
![iranicode](https://user-images.githubusercontent.com/47592258/67774365-70f79400-fa72-11e9-8a5c-316d41f55b91.jpg)
اما تاکید می کنم که همه جا فقط در ابعاد کوچک حس میشه.

### و در مورد درخواست
لطفا از این صفحه دیدن بفرمایید:
https://fontiran.com/%d9%81%d9%88%d9%86%d8%aa-%d8%a7%db%8c%d8%b1%d8%a7%d9%86-%db%8c%da%a9%d8%a7%d9%86-iran-yekan/
و همچنین به آنالیز:
![linesym](https://user-images.githubusercontent.com/47592258/67775365-18c19180-fa74-11e9-9b7c-50930cef35c4.jpg)

برای مثال:
- در این نمونه فونتی رو پیدا نکردم که سز خط ن از هر دو طرف یکسان تمام شده باشه
- وزن نقطه ها هم وزن خطوط باشه
- دندانه ها و سایر حروف نزدیک در یک جا پایان یافته باشند
- م آخر، ی آخر واو آخر و... از بالا در یکجا تمام شده باشند.
- **ر** و **و** یک انحنا داشته باشند و همچنین از پایین در یکجا تمام شده باشند
- و... به طور خلاصه همه چیز بر سه یا چهار خط اساسی پایان یافته باشد
به نظرم میرسه تکریبی از اصول وزیر، یکان و ایران یکان و در نهایت یکسان سازی اندازه ها، ارتفاع ها و وزن ها می تونه چنین فونتی رو ایجاد کنه که در خانواده
sans-serif
جای بگیره

قطعا مطلع هستید که در نمونه فونت های انگلیسی (به دلیل هندسی بودن اشکال) فونت های بسیار زیادی وجود داره:
https://www.tinkov.info/qanelas.html
یا
https://www.fontfabric.com/fonts/nexa/
یا حتی
Roboto
و...
اما چون با این همه هنوز نمیشه فونت فارسی که کاملا متقارن و هندسی و همچنین از لحاظ زیبایی و خوانایی در حد **وزیر** باشه رو پیدا کرد، این پیشنهاد رو به شما مطرح کردم.

**Comment by rastikerdar** [comment]
مشکل فاصله ر با حرف بعدی در نسخه ۲۶ برطرف شد. با بهبودهای جدید امیدوارم مشکلات رفع شده باشه. با تشکر
https://github.com/rastikerdar/vazir-font/releases
