### ISSUE TITLE
English mode is not a Sans font!

### ISSUE THREAD

**Issue by AminMemariani** [rastikerdar/vazir-font#132]
Although the font is quit good in Farsi but when you try to mix the Word with some latin(English) letters it gets not so appealing. It would be great if the English letters also use a Sans form.

https://www.dropbox.com/s/ug4zmk8cjz2iwyu/Screen%20Shot%202019-11-13%20at%2013.12.55.png?dl=0

**Comment by rastikerdar** [comment]
ابتدا پیشنهاد می‌کنم حتما از نسخه نهایی استفاده کنید.
احتمالا از نسخه بدون لاتین استفاده می‌کنید در نتیجه سیستم خودش فونت لاتین رو انتخاب میکنه اما نسخه اصلی وزیر با فونت لاتین روبوتو ترکیب شده و در ریشهٔ بستهٔ فونت قرار داره.
اگر هم می‌خواهید از نسخه بدون لاتین استفاده کنید باید برای حالت لاتین، فونت (یا نوعش رو) تنظیم کنید.
مثلا در صفحات وب:
`font-family: 'Vazir', sans-serif;`
