### ISSUE TITLE
مشکل در حرف «ی» آخر

### ISSUE THREAD

**Issue by hadifaridhadi** [rastikerdar/vazir-font#133]
سلام.
با تشکر فراوان از زحمات گرانقدر جنابعالی، خواهشمندم مشکل حرف «ی» آخر همراه با حاشیه (Outline, Stroke) را اصلاح نمایید. لطفاً به مثال زیر توجه نمائید:
![unnamed](https://user-images.githubusercontent.com/30140300/69988911-d0583080-1557-11ea-923c-3a964499cea6.png)
اطلاعات مثال بالا:
فونت: "Vazir Black FD"
نرم‌افزار پاورپوینت 2019
ویندوز 10 ورژن 1903

با تشکر، هادی فرید

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو
توی آفیس ۲۰۱۳  که اینطوری نشون میده.
![Screenshot at 2019-12-02 23-51-53](https://user-images.githubusercontent.com/3116038/69992412-d9003500-155e-11ea-8ef9-7e69c325c424.png)

البته برای فهمیدن این مشکل باید آفیس ۲۰۱۹ نصب کنم

**Comment by hadifaridhadi** [comment]
> سلام
> ممنونم برای این ایشو
> توی آفیس ۲۰۱۳ که اینطوری نشون میده.
> ![Screenshot at 2019-12-02 23-51-53](https://user-images.githubusercontent.com/3116038/69992412-d9003500-155e-11ea-8ef9-7e69c325c424.png)
> 
> البته برای فهمیدن این مشکل باید آفیس ۲۰۱۹ نصب کنم

بله درسته، ظاهر در ورد و پاورپوینت متفاوته و متأسفانه در ورد، با اینکه «ی» آخر درسته، اما «ش» اول (ش‍) اشتباه نمایش داده میشه.
برای مقایسه، لطفاً این اسکرین‌شات رو مشاهده نمائید:

![s](https://user-images.githubusercontent.com/30140300/70064806-5ed3bd00-15ff-11ea-8540-38f061da7da0.png)

همانطور که مشاهده می‌فرمائید، ‍«‍ی» در پاورپوینت و «ش‍» در ورد اشتباه نمایش داده میشن

**Comment by rastikerdar** [comment]
به جهتی پیچیده شد! چون به نظر می‌رسه با اینکه موتور رندر هر دو یکی باشه اما رفتارشون یکسان نیست. اگر با هیچ فونت دیگری چنین مشکلی ندارید احتمال بسیار ایراد از خود وزیر هست.

**Comment by hadifaridhadi** [comment]
بسیار ممنونم از وقتی که گذاشتید خسته نباشید

**Comment by zoghal** [comment]
متاسفانه مشکل از پاورپوینت است و فقط همین یک مورد نیست. اگر با باکس متن بازی کنید و فضای چپ و راست را کمی زیاد کنید قالبا مشکل حل می‌شود.

**Comment by rastikerdar** [comment]
پس از اونجایی که این مشکل ظاهرا به خود فونت مربوط نمیشه من این ایشو رو می‌بندم.
