### ISSUE TITLE
عدم شناسایی اختصاص این فونت به زبان فارسی

### ISSUE THREAD

**Issue by SMAH1** [rastikerdar/vazir-font#138]
سلام

هنگامی که در لینوکس دستور
`fc-list :lang:fa`
رو می زنیم،این فونت را جزء فونت های فارسی نمی شناسید.
همچنین در لاتک دستور
`\settextfont{Vazir}`
در نهایت باعث هشداری می شود که فوت وزیر مربوط به زبان فارسی نیست
که باید صریحا به شکل زیر تعریف شود تا هشدار ندهد
`\settextfont[Language=Default]{Vazir}`

**Comment by rastikerdar** [comment]
سلام
برای من با این دستور میاره
`fc-list :lang=fa | grep Vazir`

اگر نسخه وزیر شما قدیمیه این احتمال وجود داره که باگ داشته باشه. اما اگر جدیده پس هنوز یک مشکلی داره.

**Comment by SMAH1** [comment]
سلام
نسخه 18 بود
بروز کردم به نسخه 22 ،مشکل حل شد
متشکرم از راهنمایی شما
