### ISSUE TITLE
مشکل در دونیت

### ISSUE THREAD

**Issue by behdad222** [rastikerdar/vazir-font#14]
بعد از زرین پال این دیده میشه
![screenshot from 2015-12-30 23 28 48](https://cloud.githubusercontent.com/assets/3942191/12056590/4dce6054-af4d-11e5-81c5-005666fc993b.png)

**Comment by rastikerdar** [comment]
تشکر می کنم بابت دونیت. برای خطا هم باید یه صفحه پیدا کنم تا خطا نده. البته در روند دونیت مشکلی ایجاد نمی کنه.

**Comment by zoghal** [comment]
شما هم می‌تونید مثل من از سرویس https://www.payping.ir/d/DHee/Ok استفاده کنی

**Comment by rastikerdar** [comment]
زرین پال بعد از آپدیتشون کلا به هم ریخت و قطع شد. تغییرش دادم به همینی که صالح جان فرمود.
تشکر
