### ISSUE TITLE
افزودن به مخزن فدورا

### ISSUE THREAD

**Issue by msm1365** [rastikerdar/vazir-font#142]
سلام. برای ساخت بسته مختص فدورا احتیاج به شرایط لایسنس واضح داریم. توی توضیحات اولیه لایسنس به 3 بخش 
تقسیم شده. خود فونت که بیت استریم  نوشته شده. اما سطر بالا نوشته که گلیف و دیتا از فونت روبوتو لایسنس آپاچی دارند. 
امکانش نیست کل فونت یک لایسنس داشته باشه؟

**Comment by rastikerdar** [comment]
سلام. تشکر میکنم برای این ایشو.
- ابتدا فونت بیت‌استریم بوده با مجوز خودش. البته مجوزش در حد پابلیک‌دومین است.
- سپس دژاوو از آن استفاده و مواردی رو بهش اضافه می‌کنه به صورت پابلیک‌دومین.
- و بعد از آن وزیر دژاوو رو تغییر می‌ده به صورت پابلیک‌دومین.
-و در نهایت روبوتو‌گوگل تحت مجوز آپاچی به آن اضافه می‌شه. در واقع بخشی که مربوط به روبوتو میشه ذیل مجوز آپاچی قرار داره.

طبیعتا نسخه سورس و نسخه‌های خروجی بدون حروف‌لاتین نیازی به اون مجوز آپاچی ندارن و شاید بهتره که حذف بشه اما در حالت ترکیبی با لاتین نمیشه اون قسمت رو حذف کرد. در مورد بیت‌استریم هم چون اثری از آن در فونت نیست میشه حذفش کرد و بیشتر به لحاظ تاریخی مونده. در مورد دژاوو هم چون پابلیک‌دومین هست شاید بشه حذف کرد اما من شخصا علاقه‌ای به حذفش ندارم چون وزیر بر بستر اون ساخته شد. مابقی فونت‌ها نیز شرایط مشابه‌ای دارند. با این اوصاف نمی‌دونم برای مجموعه فدورا این موارد چه معنی‌ای می‌تونه داشته باشه یا چگونه قابل توضیح یا توجیه است.

**Comment by msm1365** [comment]
ممنون. حالا من هر دوتاشو گذاشتم . ببینیم چی میشه.

**Comment by msm1365** [comment]
سلام مجدد. بسته بندی فدورا یک فایل متا به طور مثال 
metainfo.xml
لازم داره. من خودم یک فایل ساختم اما حدس میزنم اصول فایل متا برای فونت توش رعایت نشده. امکانش هست چنین فایلی توی مخزن قرار بدید که مناسب فونت باشه؟

**Comment by msm1365** [comment]
فایلی که من ساختم این شکلیه :

​<?xml version="1.0" encoding="UTF-8"?>
​<component type="font">
​  <id>com.vazirfonts.Vazir</id>
​  <metadata_license>MIT</metadata_license>
​  <project_license>ASL 2.0</project_license>
​
​  <name>Vazir</name>
​  <summary>A persian font fam­ily</summary>
​  <description>
​    <p>
​      Vazir is a font fam­ily designed in the 2015 by saber rastikerdar. (“Vazir” means “Minister” in Persian).
​    </p>
​  </description>
​
​  <provides>
​    <font>Vazir Regular</font>
​    <font>Vazir Light</font>
​    <font>Vazir Medium</font>
​    <font>Vazir Bold</font>
​    <font>Vazir Thin</font>
    <font>Vazir Black</font>
​    ...
​  </provides>
​</component>

**Comment by msm1365** [comment]
​<?xml version="1.0" encoding="UTF-8"?>
​<component type="font">
​  <id>com.vazirfonts.Vazir</id>
​  <metadata_license>MIT</metadata_license>
​  <project_license>ASL 2.0</project_license>
​
​  <name>Vazir</name>
​  <summary>A persian font fam­ily</summary>
​  <description>
​    <p>
​      Vazir is a font fam­ily designed in the 2015 by saber rastikerdar. (“Vazir” means “Minister” in Persian).
​    </p>
​  </description>
​
​  <provides>
​    <font>Vazir Regular</font>
​    <font>Vazir Light</font>
​    <font>Vazir Medium</font>
​    <font>Vazir Bold</font>
​    <font>Vazir Thin</font>
    <font>Vazir Black</font>
​    ...
​  </provides>
​</component>

**Comment by rastikerdar** [comment]
سلام
من فکر می‌کنم بهتره که ابتدا به طور دقیق مطمئن بشین از مراحلشون. مثلا چند تا فونت معروف رو ببینین چه کار کرده‌اند و اینکه آیا  همشون این فایل رو دارند توی مخازنشون یا نه؟ البته کتابخانه گوگل هم برای ساختار مخزن فونت‌های مورد پذیرش خودش دستورالعملی داره.

**Comment by msm1365** [comment]
بله همه فونت ها لازم دارن. یک نمونش 

https://src.fedoraproject.org/rpms/adf-gillius-fonts/blob/master/f/adf-gillius.metainfo.xml

**Comment by rastikerdar** [comment]
ببینید اون مخزن خود نگهدارنده بسته فدورا هست و اون فایل‌ها توسط همان فرد مسئول اون بسته مدیریت میشه. ظاهرا درون پوشه سورس‌ها آرشیو منبع قرار داره. سایر بسته‌ها رو هم نگاهی بیندازید می‌بینید الگوی مشابهی دارند. من روالشون رو نمی‌دونم. شاید بهتر باشه اول طریقه ساخت بسته‌های فدورا و ارسال و ثبت و غیره رو در مستندات پروژه فدورا مطالعه بفرمایید.
مثلا
[https://fedoraproject.org/wiki/Package_maintenance_guide](https://fedoraproject.org/wiki/Package_maintenance_guide)
[https://fedoraproject.org/wiki/Package_Review_Process](https://fedoraproject.org/wiki/Package_Review_Process)
[https://docs.pagure.org/docs-fedora/rpm-packaging-basics.html](https://docs.pagure.org/docs-fedora/rpm-packaging-basics.html)
و ...

**Comment by msm1365** [comment]
من هم بر اساس دستورالعمل های فدورا پیش میرم
یک فایل متا نوشتم که ضمیمه میکنم. اگر بشه به مخزن اضافه بشه استاندارد بهتری به مخزن میده. البته اگر ویرایش هم لازم داشته باشه که خودتون انجام بدین بهتره. چون من متخصص فونت نیستم.
[1.pdf](https://github.com/rastikerdar/vazir-font/files/4440405/1.pdf)

یک موضوع دیگه. فایل کانف که فدورا لازم داره ساختارش با کانف شما فرق میکنه. من یک نمونش رو میذارم. اگر این هم بنویسید و برای مخزن بگذارید که دیگه عالی میشه.

https://pagure.io/fontpackages/blob/master/f/fontconfig-templates

https://pagure.io/fontpackages/blob/master/f/fontconfig-templates/basic-font-template.conf

https://pagure.io/fontpackages/blob/master/f/fontconfig-templates/fontconfig-generics.txt

الان مثلا برای تعیین جنریک فونت من دقیقا نمیدونم فونت زیر فانتزی محسوب میشه یا نمونه های دیگه؟

**Comment by msm1365** [comment]
بسته آر پی ام طبق الزامات فدورا ساخته و برای تایید ارسال شد.
یک فایل متا و یک فایل کانف جداگانه ساخته شد
به محض اینکه تایید شد اطلاعات نصب همین جا می گذارم تا در توضیحات صفحه اصلی اضافه بشه
