### ISSUE TITLE
مشکل خط تیره در میان متن

### ISSUE THREAD

**Issue by molaeiali** [rastikerdar/vazir-font#144]
زمانی که در میان متن خط تیره وجود داشته باشه، بعد از نوشتن کلمهٔ بعد از خط تیره و زدن فاصله، خط تیره به یک کارکتر کمی بلندتر تبدیل میشه که توی فونت وزیر نشون داده نمیشه
در واقع کاراکتر «-» درست نشون داده میشه ولی «–» درست نشون داده نمیشه

البته این اتفاق توی لیبره‌آفیس میوفته ولی به نظر میاد مشکل از فونت باشه، چون با فونتای دیگه (حتی فونت‌های دیگهٔ خود شما از جمله وزیر کد!) این مشکل وجود نداره
![Screenshot from 2020-04-17 22-41-10](https://user-images.githubusercontent.com/12999682/79600968-4c18db00-80fd-11ea-93f4-2c4fd687e900.png)

اینجا بعد از کلمهٔ «متن» یه فاصله زدم فقط
![Screenshot from 2020-04-17 22-41-14](https://user-images.githubusercontent.com/12999682/79600978-50dd8f00-80fd-11ea-84d1-ba278a5d248b.png)

امیدوارم بتونی مشکل رو باز تولید کنی. ممنون از وقت و کارای عالیت

**Comment by rastikerdar** [comment]
ممنونم برای ایشو
عجیبه لیبره آفیس برای من هم تبدیل میکنه. البته اون مربع رو نمیذاره و همون «–» رو به جای «-» می‌نویسه. برای همه فونت‌های عربی و فارسی هم همینجوره.
در واقع این نویسه هست:
[https://unicode-table.com/en/2013/](https://unicode-table.com/en/2013/)

مثلا نوتو سنس عربیک 2011 رو داره اما 2013 رو نداره.

توی ایشوی #143 به یه سری نویسه‌های مشابه اشاره شده که باید اضافه بشه اما این موردی رو که لیبره‌آفیس می‌گذاره، توی اون لیست نیست. نمی‌دونم اساسا برای چی لیبره‌آفیس تبدیل می‌کنه؟

**Comment by molaeiali** [comment]
شاید مشکل از لیبره‌آفیس باشه، من نسخه ۶.۴.۳ دارم، واسه شما چه نسخه‌ایه؟ روی اونم اگر بتونم تست کنم

**Comment by rastikerdar** [comment]
برای من 6.4.2.2 هست.

**Comment by molaeiali** [comment]
من روی ۶.۴.۲ هم امتحان کردم مربع نشون میده برام، کاراکتر رو هم کپی کردم توی پایتون یونیکود اسکیپ می‌کنم میگه 
b'\\u2013'
که همونه که شما هم گفتی، چرا حالا برای من مربع میشه برای شما نمیشه نمیدونم 🤔

من فونت رو می‌کنم Noto Sans Arabic (یا تقریبا هر فونت دیگه‌ای) خط رو درست نشون میده، ولی با Vazir مربع نشون میده

من فونت رو از گیت‌هاب میگیرم ها، نکنه یه ایرادی داره اونجا ولی فونتی که شما خودت الان رو لپ‌تاپت هست این ایراد رو نداره؟

**Comment by rastikerdar** [comment]
فونت من هم با گیتهاب یکیه.
شاید اگر یه بار کش رو پاک و دوباره لیبره‌آفیس رو اجرا کنید درست بشه
‍`fc-cache -rv`

**Comment by molaeiali** [comment]
این کار رو هم انجام دادم ولی بازم مشکل هست

من ورژنای قدیمی رو از ۱۸ شروع کردم تست کردن، تا نسخه ۲۰.۱.۱ این مشکل وجود نداره، از نسخه ۲۱.۰.۰ این اتفاق میوفته، شاید کمک کنه 🤔🤷🏻‍♂️

**Comment by rastikerdar** [comment]
نکته خوبی اشاره فرمودین چون نسخه ۲۱ تغییرات زیادی داشت.
اگه امکانش هست با نسخه بدون لاتین جدید هم تست بفرمایید.

**Comment by molaeiali** [comment]
روی WOL Black FD حتی Thin Light Medium این مشکل وجود نداده، فقط روی Vazir خالی مشکل هست

**Comment by saeidka** [comment]
چه جالب در 6.4.3.2 در ویندوز برای من برای همه فونتهای شما endash می‌شود hyphen mines

**Comment by saeidka** [comment]
جالبتر این که با همهٔ‌ فونتها حتی اریال در همهٔ‌ ویندوزها حتی آخرین نسخه ۱۰ و آخرین نسخه ورد ۲۰۱۹ هم همین اتفاق می‌افتد.

**Comment by saeidka** [comment]
چقدر خنگم من. این به دلیل اتوکارکت است آن را غیرفعال کنید. حل می‌شود.

**Comment by rastikerdar** [comment]
درست می‌فرمایید اما علی آقا می‌فرمایند چرا به صورت مربع نشان میدهد. البته من باز هم بررسی کردم اما نتونستم دلیلش رو پیدا کنم. شاید یک زمانی ناگهانی پیداش کردم.

**Comment by saeidka** [comment]
خب ایشان هم غیرفعال کنند ببیند باز مریع می‌آید؟

**Comment by molaeiali** [comment]
@saeidka 
دوست من صورت مساله رو که نمی‌خوایم پاک کنیم، اون کاراکتر باید درست نشون داده بشه به هر حال، نمیشه تو توضیحات نصب فونت به همه گفت برید این آپشن رو غیرفعال کنید که

**Comment by saeidka** [comment]
در برنامه واژه پرداز دیگری هم تست کردید؟ مثلا چیری شبیه نتپد در لینوکس

**Comment by rastikerdar** [comment]
امیدوارم توی نسخه جدید ۲۵.۰.۰ این مشکل برطرف شده باشه.
[https://github.com/rastikerdar/vazir-font/releases](https://github.com/rastikerdar/vazir-font/releases)

**Comment by molaeiali** [comment]
مشکل حل شده توی نسخه ۲۵، ممنون
