### ISSUE TITLE
میزبانی در یک سی‌دی‌ان جدید

### ISSUE THREAD

**Issue by alihardan** [rastikerdar/vazir-font#145]
<p dir="rtl">
همونطور که اطلاع دارید عمر RawGit داره به پایان می‌رسه:
</p>

https://rawgit.com/

**Comment by alihardan** [comment]
همین خوبه:

https://cdn.jsdelivr.net/npm/vazir-font@24.1.0/dist/font-face.css

**Comment by rastikerdar** [comment]
ممنونم برای ایشو
حق با شماست. باید مهاجرت کنیم به یک سی‌دی‌ان جدید. فکر می‌کنم از روش زیر استفاده بشه بهتره تا وابسته به ان‌پی‌ام نباشه. الان برخی پکیج‌ها توسط افراد دیگر ثبت شده که به روز یا خودکار نیستند.
[Migrating from RawGit to jsDelivr](https://www.jsdelivr.com/rawgit)
مثل:
[https://cdn.jsdelivr.net/gh/rastikerdar/samim-font@v4.0.5/dist/font-face.css](https://cdn.jsdelivr.net/gh/rastikerdar/samim-font@v4.0.5/dist/font-face.css)

**Comment by rastikerdar** [comment]
من صفحه اصلی این فونت و چند فونت دیگر رو بروزرسانی کردم. تشکر می‌کنم از شما برای گزارش این مورد.

**Comment by tofiqsp** [comment]
Failed to load resource: net::ERR_TIMED_OUT
https://cdn.jsdelivr.net/gh/rastikerdar/vazirmatn@v33.003/Vazirmatn-font-face.css
