### ISSUE TITLE
وزیر و گیومهٔ فارسی

### ISSUE THREAD

**Issue by neesti** [rastikerdar/vazir-font#148]
<div dir=rtl>
سلام. 

اگر خاطرتان باشد، مدتی پیش در صفحهٔ فونتِ «ساحل» دربارهٔ مشخصات گیومهٔ فارسی گزارشی خدمتتان فرستاده بودم. شما نیز قبول زحمت کردید و مشکل را حل فرمودید. 
آیا امکانش هست که این گیومه‌های نوک‌تیزِ فونتِ وزیر را نیز اصلاح بفرمایید تا بیشتر به گیومهٔ فارسی شبیه گردند؟
متشکرم.

**Comment by rastikerdar** [comment]
سلام
متشکرم برای این ایشو. در نسخه جدید وزیر یعنی ۲۶ گیومه اصلاح شد. البته من از همان شکل ساحل استفاده کردم ولی به نظر با قلم سازگار بود.
