### ISSUE TITLE
وزیر و نویسهٔ سریاء

### ISSUE THREAD

**Issue by neesti** [rastikerdar/vazir-font#149]
<div dir=rtl>
سلام. 

فونت وزیر برخلاف فونت ساحل نویسهٔ سریاء (یاءِ مرخم، مثلاً خانهٔ) را به‌صورت همزه (ششِ کوچک) نمایش می‌دهد که گمان نکنم صحیح باشد.

**Comment by rastikerdar** [comment]
سلام
ممنون می‌شم مشخصات محیطی که در آن به این مشکل برخوردید رو ذکر بفرمایید. چون برای من این مشکل قابل مشاهده نیست.
![Screenshot at 2020-05-09 05-16-43](https://user-images.githubusercontent.com/3116038/81459267-49694d00-91b4-11ea-989f-3f516144c90c.png)

**Comment by neesti** [comment]
<div dir=rtl>
حق با شماست. در واژه‌پردازها این مشکل نیست. 
راستش این مشکل را در نسحهٔ جدید تلگرام دسکتاپ (نسخهٔ ۲.۱.۳) دیدم. 
چنانکه می‌دانید در این نسخه از فونت وزیر استفاده می‌کنند. 
فونت را از این شاخه گرفته‌اند:
https://github.com/rastikerdar/vazir-font/tree/master/dist/Without-Latin

درجهٔ درشتیِ فونت را با استفاده از نوار لغزندهٔ تلگرام از ۱۰۰٪ به ۱۲۵٪ تغییر دادم و متوجه شدم که در این مقیاس‌پذیری نویسهٔ سریاء درست نمایش داده می‌شود. 
الان به شک افتادم. نمی‌دانم این مشکل در مقیاس‌پذیری ۱۰۰٪ واقعاً وجود دارد یا چون فونت ریزتر دیده می‌شود، به چشم من است که این‌طور می‌آید.

**Comment by neesti** [comment]
<div dir=rtl>
دوباره بررسی کردم. 
مطمئن شدم که وزیر در نمایش درست این نویسه مشکلی ندارد. 
فقط چون تلگرام از اندازهٔ کوچک آن برای نمایش کلمات استفاده می‌کند، به چشم من آن‌طور رسیده بوده. 
عذرخواهم که وقت شما را با بی‌دقتی‌ام گرفتم. حلال بفرمایید.
