### ISSUE TITLE
حرف ز و ی

### ISSUE THREAD

**Issue by miladmofficial** [rastikerdar/vazir-font#15]
حرف ز بسیار بزرگ و کدو شکل نمایش داده می شود، همچنین حروفی که به حرف ی منتهی می‌شوند به نسبت بزرگ هستند

**Comment by rastikerdar** [comment]
ممنونم بابت این ایشو
حرف ز در حالت ضخیم یا معمولی یا هر دو اینگونه به نظر می رسه؟

**Comment by miladmofficial** [comment]
در هر رو حالت

**Comment by Javid-Izadfar** [comment]
@miladmofficial منظورتون از "کدو" چی هست؟ من مشکلی نمیبینم!

**Comment by miladmofficial** [comment]
انتهای حرف ز چاق تر به نظر میرسه و همچنین نسبت به و کشیده تر شده...جای نقطه ز هم حتی نمایشش رو خراب کرده

**Comment by rastikerdar** [comment]
![screenshot from 2016-01-02 23-56-43](https://cloud.githubusercontent.com/assets/3116038/12076002/e4916a48-b1ac-11e5-8c8e-d93719924ddc.png)
![screenshot from 2016-01-02 23-57-26](https://cloud.githubusercontent.com/assets/3116038/12076003/e7993a54-b1ac-11e5-8585-efd534869274.png)

راستش من متوجه مشکل نشدم. انتهای ز ضخیم تر شده؟

**Comment by zoghal** [comment]
در وزن ۷۰۰ هم نقطه ها کوچیک هستند.

**Comment by miladmofficial** [comment]
در انحنا بله

**Comment by rastikerdar** [comment]
امیدوارم این نسخه آخر نظر شما رو تامین کرده باشه.
همچنین نقطه ها هم درشت تر شدند. تشکر از صالح جان

![screenshot from 2016-08-28 04-04-40](https://cloud.githubusercontent.com/assets/3116038/18030680/ac90e25c-6cd4-11e6-84c7-a1074f8700ab.png)

با سپاس از همگی

**Comment by zoghal** [comment]
حسودیم شد. چه ر توپی شده 👍
