### ISSUE TITLE
مشكل در كاراكتر "كشيده" (U+0640)

### ISSUE THREAD

**Issue by imiimiimi** [rastikerdar/vazir-font#153]
درود،
‫كاراكتر **U+0640** : ARABIC TATWEEL {kashida} خيلي كوتاه است و به تنهايي مثل نقطه ديده ميشه كه از سطح فاصله داره و در زمان چسبيدن به يه كاراكتر ديگه مثل كشيدگي خاصي اضافه نميكنه و بايد دوتا استفاده بشه تا تقريبا با فونت‌هاي ديگه برابري كنه.
بنظرم طولش دوبرابر بشه بهتره و بود و نبودش در يه متن بهتر نشون ميده و تعداد كاراكتر كمتري هم استفاده ميشه.
اين مشكل توي بقيه فونت‌ها هم بود (ساحل، شبنم، صميم، تنها، ناهيد، پرستو و گندم)

**Comment by rastikerdar** [comment]
درود
تشکر می‌کنم برای این ایشو. درست می‌فرمایید نسبت به سایر فونت‌ها کوتاه‌تره. یک دلیلش به خاطر این ایشو بود:
[https://github.com/rastikerdar/parastoo-font/issues/10](https://github.com/rastikerdar/parastoo-font/issues/10)

دلیل دیگر اینکه من احساس کردم اگر کوتاه‌تر باشه دست مخاطب فونت بازتره و با کشیدهٔ کوتاه‌تر، .اندازه‌های دلخواه بیشتری می‌تونه ایجاد کنه

**Comment by typoman** [comment]
به نظر من هم کشیده‌ی بزرگ مشکلات خودشو داره. موقع جاستیفای کردن اگه نرم‌افزار کشیده اضافه کنه و طول کشیده‌ها بزرگ باشه امکان داره فاصله‌ی سفید بیشتر دیده بشه نسبت به زمانی که کشیده کوچک هست!

**Comment by imiimiimi** [comment]
این موضوع که دوستمون میگه با فونت ایران‌سنس مقایسه کردم و درسته اگه جاستیفای معمولی بدون ایجاد کشیدگی خودکار انجام بشه فاصله سفید بیشتری میافته و با جاستیفای کم کشیدگی خيلي كمي ايجاد ميشه ولی توی حالت متوسط و زیاد با ایران‌سنس یکی میشه.
نمیدونم شاید این قسمت کار دیگه سلیقه باشه هم نکته مثبت داره هم منفي

**Comment by rastikerdar** [comment]
جالب بود. من این موضوع رو نمی‌دونستم و برام تازگی داشت.

**Comment by aminabedi68** [comment]
به این مسئله هم باید توجه کرد که وقتی فونت عوض میشه «نباید» طول نوشته‌های دارای کشیدگی نسبت به فونتای دیگه تو اندازه یکسان تغییر خیلی زیادی داشته باشه، بنابراین به نظر میرسه طول این کاراکتر باید نسبتی از ارتفاع الف تعریف بشه، ۳۰ تا ۴۰ درصد ارتفاع الف احتمالا

**Comment by rastikerdar** [comment]
در نسخه جدید طول این کاراکتر حدودا دوبرابر شد. با تشکر
![Screenshot at 2021-06-25 11-38-04](https://user-images.githubusercontent.com/3116038/123385223-91128a00-d5aa-11eb-960e-e9fa1e6e2a58.png)

https://github.com/rastikerdar/vazir-font/releases
