### ISSUE TITLE
Manufacturer

### ISSUE THREAD

**Issue by xmha97** [rastikerdar/vazir-font#154]
سلام، ممنون از فونت زیباتون
یه پیشنهاد داشتم:

لطفا تک `Manufacturer` رو از `Based on Dejavu fonts, by Saber Rastikerdar` به `Saber Rastikerdar` تغییر دهید.

![image](https://user-images.githubusercontent.com/23485114/83021351-1e4d7d00-a03f-11ea-94a7-12c9c3b1716e.png)

من فونت‌ساز نیستم اما فکر می‌کنم اطلاعات مربوط به کپی‌رایت باید در تگ `License` درج شود چون فونت‌هایی رو که دارم بدین صورت هستند.

با تشکر.

**Comment by rastikerdar** [comment]
سلام
احتمالا حق با شما باشه

**Comment by xmha97** [comment]
# چرا واسم مهمه؟
<div dir="rtl">

من همه‌ی فونت‌ها رو توسط یه اسکریپت فولدر بندی می‌کنم
**فولدر بندی:** دسته بندی فایل‌ها با استفاده از فولدرها

**الگو:**
<div dir="ltr">

[Manufacturer]\[Font Name] (v[Font Version])\[Font Face].ext
<div dir="rtl">

**مثال:**
<div dir="ltr">

Monotype Imaging Inc\Verdana Pro (v6.13)\VerdanaProBold.ttf
<div dir="rtl">

من می‌خواهم `Manufacturer` تمامی فونت‌هاتون `Saber Rastikerdar` شود که همه‌ی فونت‌هاتون رو در یک فولدر داشته باشم (نه چندین فولدر)

مانند تصویر زیر:

![Windows File Explorer](https://user-images.githubusercontent.com/23485114/83540863-26f5f580-a50e-11ea-8ff7-bad0b62b96f6.png)

آیا این تغییر اعمال میشه؟ (حداقل برای فونت وزیر)

**Comment by xmha97** [comment]
> 
> 
> درست می‌فرمایید. این مورد رو برای همه فونت‌ها اصلاح می‌کنم.
<div dir="rtl">

میدونم که اعمال کردن این تغییر برا ۱۲۱ عدد فونت چه کار وقت‌گیریه
و ازتون صمیمانه تشکر میکنم 😘

**Comment by rastikerdar** [comment]
خواهش می‌کنم. البته تمامی فایل‌های نهایی توسط یک اسکریپت ساخته میشن که قبلا نوشته‌ام. در واقع من فقط فایل‌های منبع رو دست می‌زنم. مثلا برای فونت وزیر ۶ تا فایل سورس رو اصلاح می‌کنم.
[github.com/rastikerdar/fontbuilder](https://github.com/rastikerdar/fontbuilder)

**Comment by xmha97** [comment]
<div dir="rtl">

چه خفن! خیلی حال کردم 👏

**Comment by rastikerdar** [comment]
این ایراد در نسخه ۲۷ اصلاح شد. با تشکر از شما
https://github.com/rastikerdar/vazir-font/releases

**Comment by xmha97** [comment]
> این ایراد در نسخه ۲۷ اصلاح شد. با تشکر از شما
> https://github.com/rastikerdar/vazir-font/releases

ممنون 😘

**Comment by xmha97** [comment]
سلام
گفته بودید برا همه‌ی فونت‌هاتون این تغییر رو انجام می‌دید.
امکان داره فونت وزیر کد رو تو اولویت قرار بدین؟
@rastikerdar
