### ISSUE TITLE
پشتیبانی از حروف ترکی

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#155]
بخشی از پیام آقای میثم مهدی‌پور در نامهٔ الکترونیکی‌ای که ارسال فرموده بودند (با کسب اجازه از خود ایشان):

> همانگونه که مستحضر هستید ترک‌های ایرانی همانند هم‌وطنان فارس خود از الفبای عربی استفاده می‌کنند لیکن برخی کاراکترها را بکار می‌بریم که جای خالی این کاراکترها در فونت‌های زیبای شما خالی‌ست. برای مثال:
ؽ
ۆ (oe)
ݣ و ڭ (اولویت با ݣ است که به کاف نون معروف است و صدای ng انگلیسی می‌دهد)
ې (e)
ۋ
ۉ
ھ
ى‍ ى
این حروف و البته حروف کامل یونی‌کد عربی

**Comment by pashai** [comment]
سلام  و درود 
ضمن تشکر از تیم طراحی فونت زیبای وزیر ، معمولا در ایران در بحث استفاده از فونت و پشتیبانی یک فونت از کاراکترهای بیشتر به مشکل برمی‌خوریم و مجبور می‌شویم بر خلاف تمایل از فونت هایی که زیبایی بصری‌ای  ندارند استفاده کنیم که کاراکترهای  بیشتری را  پشتیبانی می‌کنند. حقیقتا  فونت وزیر فونت بسیار زیبایی هست من هم بسیار خوشحال می‌شوم که این فونت از پشتیبانی کامل کاراکترها برخوردار شود، پیشنهاد جناب مهدیپور  بسیار عالی و ارزشمند است، تقاضا دارم لطفا این موارد را به فونت وزیر  حتما بیافزایید.

**Comment by jahangard** [comment]
ضمن آرزوی موفقیت برای شما و تشکر از بابت فونتهای زیبا
دو تا سئوال داشتم از خدمتتون. 
۱- آیا فونت داخل اپلیکیشن ویندوزی تلگرام فونت صمیم می باشد؟
۲- ما چگونه میتونیم فونتهای شما رو در اپلیکیشن هامون استفاده کنیم؟ آیا لایسنسی باید تهیه کنیم؟

**Comment by rastikerdar** [comment]
۱- فونت وزیر است
۲- این فونت برای استفاده کاملا آزاد هستند و نیاز به هیچ کار خاصی ندارید

**Comment by vaheedxp** [comment]
با سلام
زبان اوزبیکی افغانستان نیز تقریبا از همین حروف به اضافه‌ی حروف فارسی استفاده می‌کند. اگر این حروف هم در فونت اضافه شود عالی خواهد شد.

**Comment by rastikerdar** [comment]
پشتیبانی از این حروف در نسخه ۲۷ اضافه شد. با تشکر از دوستان
https://github.com/rastikerdar/vazir-font/releases
