### ISSUE TITLE
بهبود کارکتر دو نقطه

### ISSUE THREAD

**Issue by SajjadSM** [rastikerdar/vazir-font#157]
باسلام
احساس میکنم فاصله نقطه ها اگر کمتر باشه بهتر میشه

![Image of font](http://uupload.ir/files/xaiy_vazir_2.jpg)

**Comment by rastikerdar** [comment]
از کدام نسخه فونت وزیر استفاده می‌کنید؟
معذرت می‌خوام اما من نمی‌تونم بین دو تصویر بالا تفاوتی رو تشخیص بدم.

**Comment by ghasrfakhri** [comment]
به نظر میرسه فاصله بین دونقطه قبل از قیمت در تصویر پایین کمتر از تصویر بالا است.

**Comment by rastikerdar** [comment]
آهان درست می‌فرمایید. ممنونم. فکر می‌کنم اگر به روزرسانی کنند در نسخه‌های جدیدتر بهتر شده باشه.

**Comment by SajjadSM** [comment]
فونت رو به آخرین نسخه بروزرسانی کردم ولی تفاوتی نکرد (تصویر اول)ء

**Comment by rastikerdar** [comment]
مطمئنید؟ آخرین نسخه این شکلیه:  
![Screenshot at 2020-06-27 15-13-01](https://user-images.githubusercontent.com/3116038/85920422-e5483880-b888-11ea-8182-62b143eb960b.png)

اگر از علامت ﷼ یا همون شیفت+۴ استفاده کنید بهتر هم میشه:  
![Screenshot at 2020-06-27 15-13-16](https://user-images.githubusercontent.com/3116038/85920450-22acc600-b889-11ea-853d-5a30be085603.png)

اگر هم از اعداد فارسی استفاده کنید که دیگه خیلی بهتر میشه :)  
![Screenshot at 2020-06-27 15-14-11](https://user-images.githubusercontent.com/3116038/85920461-39531d00-b889-11ea-9321-47ffdcc0648c.png)
 
اگر هم از جداکننده هزارگان یا سه‌رقم سه‌رقم استفاده کتید که دیگه واویلا:  
![Screenshot at 2020-06-27 15-19-03](https://user-images.githubusercontent.com/3116038/85920524-aff01a80-b889-11ea-83d7-cbebb914134d.png)
