### ISSUE TITLE
مشکل در پرینت برخی حروف مثل گ ، ی و يـ

### ISSUE THREAD

**Issue by Ariodaad** [rastikerdar/vazir-font#158]
با سلام و خسته نباشید.
جناب راستی‌کردار اول از همه اینکه بابت زحماتتون سپاسگزارم. واقعا فونت وزیر زیبا و خواناست. من اینقدر این فونت رو دوست دارم که با هزار ترفند این فونت رو روی گوشیم نصب کردم و فونت اصلی گوشیم شده!

اما مشکل:
برخی حروف با وجود نمایش صحیح ، در پرینت با اشکال چاپ می‌شود.
http://s13.picofile.com/file/8401539850/WhatsApp_Image_2020_06_30_at_11_51_35_AM_1_.jpeg
http://s12.picofile.com/file/8401539876/WhatsApp_Image_2020_06_30_at_11_51_35_AM.jpeg

عین خود فایل و کلمات
http://s13.picofile.com/file/8401539726/Book1.xlsx.html

ویندوز 7
64 بیت
آفیس 2019
کیبورد فارسی استاندارد http://persian-computing.org/download/Iranian_Standard_Persian_Keyboard_(ISIRI_9147)_(Version_2.0).zip
وزیر نسخه 26.0.2

**Comment by rastikerdar** [comment]
با سلام و تشکر
ممنونم برای این ایشو. عجیبه که تنها در هنگام چاپ این مشکل برای شما به وجود آمده. به نظر میاد درایور پرینتر از روش مخصوص به خودش در پردازش متن استفاده می‌کنه یا اینکه اون نرم‌افزار (آفیس) هنگام تبدیل به متن قابل چاپ با وزیر این مشکلات رو به وجود میاره.
اگر می‌تونستید همین متن‌ها رو به نرم‌افزار دیگری هم برای چاپ بدهید معلوم می‌شد اشکال در کدام قسمت محتمل‌تره. یا اینکه تبدیل کنید به پی‌دی‌اف ببینید توی پی‌دی‌اف درست تبدیل شده یا خیر و همچنین چاپ.

راستی توی متن ایشو می‌تونید به راحتی با کلیک بر روی قسمت پایینی جعبه متن تصویر اضافه کنید.

**Comment by Ariodaad** [comment]
در پرینت با نرم افزار نوت‌پد و ورد هم مشکل داره. اما به جای کشیدگی دی حرف ی کلا چاپ نشد. مشکل حرف گ که فقط سرکش چاپ میشد به همون شکل تکرار شد. نوت‌پد اصولا کلیه کدهای اضافه متن رو حذف میکنه پس قاعدتا مشکل از آفیس نباید باشه و توی نرم‌افزارهای دیگه هم باید شاهد این مورد باشیم. حالا باز اگر شما حدس دیگری دارید میتونم مثلا لیبر آفیس هم نصب کنم و فایل اکسلم رو در اون اجرا و پرینت کنم و نتیجه رو بهتون بگم.

در تبدیل به پی‌دی‌اف دو اتفاق متفاوت افتاد. در بار نخست از طریق گزینه پرینت در اکسل عملیات پرینت رو طی کردم و نام دستگاه پرینتر رو تغییر دادم به نرم‌افزار مبدل پی‌دی‌اف.
نام این نرم‌افزار doPDF هستش.
 در فایل پی‌دی‌اف تولید شده به روش پرینت نرم‌افزاری همون مشکل وجود داشت و تا جایی که من از نحوه کارکرد این نرم‌افزار اطلاع دارم ابتدا فایل موجود رو تبدیل به یک ایمیج برای خودش میکنه و سپس تبدیل به پی‌دی‌اف میکنه تا به این روش همه زبان‌ها رو ساپورت کنه.
در بار دوم از طریق گزینه ذخیره کردن استفاده کردم و فایل پی‌دی‌افی که خود اکسل ساخت هیچ ایرادی نداشت که در پرینت از همین فایل پی‌دی‌اف ایجاد شده  با اکسل هم مشکلی رویت نشد که به نظر با توجه به ماهیت پی‌دی‌اف انتظار دیگه‌ای هم نمی‌رفت.

**Comment by rastikerdar** [comment]
پس میشه گفت مشکل دقیقا در پردازش برای چاپ اتفاق میفته و به خود نرم‌افزارها (آفیس و نوت‌پد و ...) ارتباطی نداره. فقط اگر براتون امکان داره یک بار هم با فونت «ساحل» امتحان بفرمایید و چاپ بگیرید روی همان نرم‌افزار مبدل پی‌دی‌اف یعنی همان
doPDF
یا روی کاغذ (فرقی نمی‌کنه) ببینید آیا باز هم این مشکل تکرار میشه یا خیر.
[rastikerdar.github.io/sahel-font](https://rastikerdar.github.io/sahel-font/)

**Comment by Ariodaad** [comment]
> پس میشه گفت مشکل دقیقا در پردازش برای چاپ اتفاق میفته و به خود نرم‌افزارها (آفیس و نوت‌پد و ...) ارتباطی نداره. فقط اگر براتون امکان داره یک بار هم با فونت «ساحل» امتحان بفرمایید و چاپ بگیرید روی همان نرم‌افزار مبدل پی‌دی‌اف یعنی همان
> doPDF
> یا روی کاغذ (فرقی نمی‌کنه) ببینید آیا باز هم این مشکل تکرار میشه یا خیر.
> [rastikerdar.github.io/sahel-font](https://rastikerdar.github.io/sahel-font/)

فونت ساحل رو هم استفاده میکنم. تا حالا چنین مشکلی ندیدم. اما فکر میکنم توی فونت صمیم هم مشکل مشابهی دیده بودم

**Comment by Ariodaad** [comment]
> > پس میشه گفت مشکل دقیقا در پردازش برای چاپ اتفاق میفته و به خود نرم‌افزارها (آفیس و نوت‌پد و ...) ارتباطی نداره. فقط اگر براتون امکان داره یک بار هم با فونت «ساحل» امتحان بفرمایید و چاپ بگیرید روی همان نرم‌افزار مبدل پی‌دی‌اف یعنی همان
> > doPDF
> > یا روی کاغذ (فرقی نمی‌کنه) ببینید آیا باز هم این مشکل تکرار میشه یا خیر.
> > [rastikerdar.github.io/sahel-font](https://rastikerdar.github.io/sahel-font/)
> 
> فونت ساحل رو هم استفاده میکنم. تا حالا چنین مشکلی ندیدم. اما فکر میکنم توی فونت صمیم هم مشکل مشابهی دیده بودم

امتحان کردم با فونت ساحل ایرادی نداره اما با فونت صمیم دقیقا عین مشکل وزیر وجود داره.

**Comment by Ariodaad** [comment]
توی صفحه زیر
https://codepen.io/aardrian/pen/dKrZdd/
با استفاده از سی‌اس‌اس با فونت وزیر همون کلمات رو وارد و از صفحه پرینت گرفتم. هیچ مشکلی نبود. این یعنی تحت وب مشکلی در پرینت نیست. فکر میکنم با این اوصاف فرضیه مشکل پردازش در چاپگر هم درست نباشه. 
فقط سوالی که هست توی وب از پسوند تی‌تی‌اف استفاده کردم. پسوند مورد استفاده در آفیس هم همینه یا فرق داره؟
![WhatsApp Image 2020-07-01 at 4 07 08 PM](https://user-images.githubusercontent.com/67626745/86239802-3c197f00-bbb5-11ea-997a-a7ec2e750d12.jpeg)

**Comment by rastikerdar** [comment]
خیلی متشکرم برای تصاویر و توضیحات. بلی همان نسخه است و فرقی ندارند. مشکل رو پیگیری می‌کنم اگر تونستم حل کنم همین‌جا به شما اطاع میدم.

**Comment by Ariodaad** [comment]
شما چک کنید شاید موردی هست شایدم به قطعیت رسیدید که هرچه هست یا سخت‌افزاری یا نرم‌افزاری از سمت بنده است!
 اما منم رو حساب حدس شما با یک پرینتر دیگه روی همین سیستم امتحان کردم. بدون مشکل پرینت گرفته شد. بعدش پرینتر خودم رو مجدد متصل کردم و صرفا جهت کنجکاوی پرینت گرفتم در کمال تعجب با پرینتر خودم هم بدون مشکل پرینت گرفت.
نمیدونم مشکل چیه اما این رو هم اضافه کنم که من وزیر رو از نسخه‌های اولیه داشتم و از همون ابتدا هم این مشکل رو داشتم و حالا که بعد از این همه مدت و نسخه‌های متعدد مشکل رفع نشد اکانت ایجاد کردم فقط به همین نیت!! 
حتی در این مدت یک بار ویندوزم رو هم کلا عوض کردم. میخوام بگم مشکل لُپی وجود نداشته که با قطع اتصال پرینتر و اتصال مجددش رفع شده باشه چون بارها در طول این مدت پرینتر من از سیستم جدا شده و گاهی از پرینتر دیگه‌ای هم استفاده کردم.

**Comment by rastikerdar** [comment]
فکر می‌کنم راه‌حل رو پیدا کردم. برای شما یک نسخه آزمایشی آماده کردم که اگر براتون امکان داره اون رو نصب و تست کنید و ببینید اگر مشکلات رفع شده که نسخه جدید رو منتشر کنم. این نسخهٔ آزمایشی نامش متفاوته:

[Vazirtest.zip](https://github.com/rastikerdar/vazir-font/files/4858353/Vazirtest.zip)

مواردی که من متوجه شدم ایراد داشتند رو مشخص کردم:
![vazir-test1](https://user-images.githubusercontent.com/3116038/86253294-99b7c680-bbc9-11ea-83a7-887e2edefbf8.jpeg)

![vazir-test2](https://user-images.githubusercontent.com/3116038/86253307-9e7c7a80-bbc9-11ea-8c67-27b1dbf6ef8b.jpeg)

**Comment by Ariodaad** [comment]
مقایسه سه فونت صمیم ، وزیر نسخه 26 و وزیر تست
![WhatsApp Image 2020-07-04 at 9 54 06 AM](https://user-images.githubusercontent.com/67626745/86505632-8f214b00-bddc-11ea-880f-f9bfd9c7b89d.jpeg)

**Comment by Ariodaad** [comment]
مقایسه فونت‌های صمیم ، وزیر نسخه 26 ، وزیر تست ، ساحل در دو حالت سبک و بولد. به نظر حالت بولد وزیر تست سبک‌تر از وزیر نسخه 26 بود.
![WhatsApp Image 2020-07-04 at 10 10 27 AM](https://user-images.githubusercontent.com/67626745/86505844-cee93200-bdde-11ea-8229-4257413c8cbc.jpeg)

**Comment by Ariodaad** [comment]
مقایسه فونت‌های صمیم ، وزیر نسخه 26 ، وزیر تست ، ساحل در دو حالت سبک و بولد. به نظر حالت بولد وزیر تست سبک‌تر از وزیر نسخه 26 بود.
![WhatsApp Image 2020-07-04 at 10 15 47 AM](https://user-images.githubusercontent.com/67626745/86505920-70708380-bddf-11ea-8cba-a4f6fbba1b87.jpeg)

**Comment by rastikerdar** [comment]
پس مشکل حل شد. اون ضخامت کمتر بولد به این خاطره که وزیرتست فقط وزن معمولی داشت و توسط خود نرم‌افزار بولد می‌شد اما وزیر ۲۶ یا ساحل وزن بولد رو هم دارند. توی نسخه جدید که منتشر میشه همه وزن‌ها اصلاح می‌شن. نسخه جدید که منتشر شد بهتون اطلاع می‌دم. البته اگر می‌خواهید هر زمان که نسخه جدیدی منتشر میشه به صورت خودکار مطلع بشین می‌تونید امکان پیگیری در بالای صفحه رو فعال کنید تا گیت‌هاب نسخه‌های جدید رو به آدرستون خبر بده.
![Screenshot at 2020-07-04 12-37-56](https://user-images.githubusercontent.com/3116038/86508219-7a03e680-bdf3-11ea-962b-73bf6834f5e0.png)

راستی هر زمان و تعداد که بخواهید می‌تونید ایشو و کامنت رو به راحتی ویرایش کنید (از طریق اون دکمه سه نقطه بالا سمت راست کامنت)

**Comment by rastikerdar** [comment]
این ایراد در نسخه ۲۷ اصلاح شد. با تشکر از شما برای پیگیری خوبتان
https://github.com/rastikerdar/vazir-font/releases
