### ISSUE TITLE
مشکل فونت در اینترنت اکسپلورر 9 به پایین فرمت eot

### ISSUE THREAD

**Issue by alirdn** [rastikerdar/vazir-font#16]
فرمت eot
که ارایه شده در هنگام لود شدن صفحه در اینترنت اکسپلورر 9 به پایین ارور زیر رو نمایش میده:
‍‍‍`CSS3111: @font-face encountered unknown error. `
که باعث میشه در نسخه 9 تنها ارور نمایش داده بشه و فونت به خوبی استفاده بشه و در نسخه‌های پایینتر فونت اصلا لود نشده. بررسی هایی که کردم به نظر میرسه ابزاری که برای تبدیل به فرمت ای-او-تی استفاده میکنید
 NAME table
هارو به درستی ایجاد نمیکنه و این مشکل رو ایجاد میکنه. برای رفع این مشکل یا میتونید از ابزار زیر:
[ttf2eot](https://code.google.com/p/ttf2eot/downloads/list)
یا از ابزار آنلاین زیر:
[font2web](http://www.font2web.com/)
برای گرفتن فونت به فرمت 
eot
استفاده کنید.

**Comment by rastikerdar** [comment]
ابتدا تشکر می کنم بابت گزارش این اشکال.

ابزار نخست را که نتوانستم کامپایل کنم. خطا داشت. برای نسخه جدید از ابزار آنلاینی که معرفی فرمودید یا این برنامه استفاده می کنم:
[npmjs.com/package/ttf2eot](https://www.npmjs.com/package/ttf2eot)

باز هم ممنونم. اجازه بدین ایشو تا زمان رفع مشکل باز بمونه.

**Comment by rastikerdar** [comment]
خب کاملا حق با شما بود. در نسخه جدید با ابزار جدید ساخته شد که با آی ای ۸ بررسی کردم مشکل رفع شده

از شما ممنونم و عذرخواهی می کنم از اینکه رسیدگی به این ایشو اینقدر طولانی شد.
با اجازه ایشو رو می بندم اگر مشکلی بود در خدمتم.
