### ISSUE TITLE
rlig to ccmp

### ISSUE THREAD

**Issue by aminabedi68** [rastikerdar/vazir-font#160]
سلام صابر جان
من متوجه شدم برای تمام فونتهایی که طراحی و اجراش با شماست برای جایگزینی ترکیب اعراب از
```rlig```
استفاده شده. تعریف لیگیچر اعراب به این شکل مشکلاتی رو توی بعضی از سیستمها بوجود میاره(مثل اندروید). بهتر و حتی ضروریه که به جای این  ویژگی از
```ccmp```
در حالت لیگیچر استفاده بشه. علاوه بر این از دو تا جدول برای این کار استفاده شده که میشه با هم ادغام کرد.
فونت وزیر از نظر فنی نسبت به نسخه های قبلی خیلی بهتر شده. قابل تحسینه. ممنون به خاطر این فونت زیبا

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو. تمام فونت‌ها از روی وزیر ساخته شده‌اند، برای همین ساختارشون شبیه به همه. در نسخه آتی رسیدگی می‌کنم.

**Comment by rastikerdar** [comment]
در نسخه ۲۷ اصلاح شد. ممنونم امین جان.
https://github.com/rastikerdar/vazir-font/releases
