### ISSUE TITLE
افزودن حرف «ڪ» به فونت

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#161]
در توییتر از طرف مخاطبی به نام احمد درخواست شده که حرف «ڪ» نیز اضافه شود. [لینک](https://twitter.com/HosseinborAhmad/status/1285942300695072770)

**Comment by Saeed854** [comment]
این حرف مال زبان سندی هستش که توی پاکستان ازش استفاده میشه.
[زبان سندی در ویکیپدیا](https://fa.wikipedia.org/wiki/%D8%B2%D8%A8%D8%A7%D9%86_%D8%B3%D9%86%D8%AF%DB%8C)

**Comment by rastikerdar** [comment]
در نسخه ۲۷ اضافه شد
https://github.com/rastikerdar/vazir-font/releases
