### ISSUE TITLE
افزودن حروف زبان ازبکی افغانستان

### ISSUE THREAD

**Issue by vaheedxp** [rastikerdar/vazir-font#162]
با سلام و خسته نباشید.
اگر ممکن است دو کاراکتر خاصی که در زبان ازبکی رایج در افغانستان استفاده می‌شود را در فونت اضاف کنید.
حروف:
ۉ
ې
با تشکر

**Comment by Saeed854** [comment]
اینا مال پشتو نیستن؟

**Comment by vaheedxp** [comment]
نخیر این حروف با حروف خاص پشتو تفاوت داره. فونت وزیر حالا از پشتو پشتیبانی می‌کنه ولی از ازبکی نه.
نمونه‌ی متن ازبیکی رو در سایت ما می‌توانید ببینید.
gahwara.com/uz

**Comment by vaheedxp** [comment]
جناب راستی‌کردار عزیز. واقف هستم که مصروفیت‌هایتان بسیار است؛ اما اگر به این درخواست رسیدگی کنید ممنون می‌شوم.

**Comment by rastikerdar** [comment]
ببخشید که دیر پاسخ می‌دم. امکانش هست چند صفحه وب (مثل ویکی پیدا) که با این زبان نوشته شده معرفی کنید تا بتونم تست کنم. برای نسخه جدید وزیر.

**Comment by vaheedxp** [comment]
خواهش می‌کنم.
لینک زیر به زبان ازبکی افغانستان است. البته زبان ازبکی رایج در خود ازبکستان با حروف لاتین یا سرلیک است اما ازبکی رایج در افغانستان با حروف فارسی است.

[gahwara.com/uz](https://gahwara.com/uz)

**Comment by rastikerdar** [comment]
در نسخه ۲۷ این حروف اضافه شد. با تشکر از شما. اگر کمبود یا ایرادی مشاهده فرمودید ممنون میشم اطلاع بدین.
https://github.com/rastikerdar/vazir-font/releases
