### ISSUE TITLE
مشکل نمایش در گوشی شیائومی

### ISSUE THREAD

**Issue by habibnajafi** [rastikerdar/vazir-font#163]
سلام 
فونت وزیر در تم استور شیائومی هست بسیار هم زیبا و‌مدرن هست اما تنها مشکلش اینن که بعضی جاها درست نمایش داده نمیشه
![Screenshot_2020-07-29-20-46-28-418_com whatsapp](https://user-images.githubusercontent.com/714767/88825252-9c173b80-d1dc-11ea-9728-29c0a73ecb84.jpg)

مثل تاریخ وضعیت واتساپ‌ به نظر فونت کمی پایین طراحی شده که کلمه امروز نصفه نمایش داده شدهبه نظز فضاهای اضافی تو طراحی کلمات هست یا توی طراحی حروف پایینتر قرار گرفن ولی فونت هایی مثل روبوتو‌ غیره درست نمایش داده میشه لطفا اصلاح بفرمایید
ممنون

**Comment by rastikerdar** [comment]
سلام
از شما تشکر می‌کنم برای گزارش این مسئله.
بلی متاسفانه این مشکل #150 راه‌حل کاملی نداره و هر روشی مشکلات خاص خودش رو داره. مثلا می‌تونیم ارتفاع نمایشی فونت رو کم کنیم که در اون صورت در برخی محیط‌ها قسمتی از حروف و اِعراب بریده میشن و همچنین در خطوط پشت‌سر‌هم اعراب و حروف در هم فرو می‌روند. و یا اینکه حروف فارسی رو کوچکتر کنیم که در اون صورت تناسب فارسی با لاتین به هم می‌خوره. و یا اینکه فارسی و لاتین رو با هم کوچک کنیم که تناسبش با دیگر فونت‌های لاتین به هم می‌خوره. هر کاری کنیم باز به مشکل بر می‌خوریم.

**Comment by habibnajafi** [comment]
سلام 
فونت روبوتو نسخه فارسی چرا این مشکل را نداره نمیشه ویرایش اصلاح شده ای برای  گوشی ها قرار بدهید؟
هم نسخه بولد هم عادی حداقل نسخه عادی

**Comment by rastikerdar** [comment]
روبوتو نسخه فارسی نداره. اندروید برای حروف فارسی از فونت دیگری استفاده می‌کنه که بسته به گوشی شما متفاوته. اما اندازه‌ها بر مبنای فونت پیش‌فرض یا همان فونت اولیه (فونت اصلی) در نظر گرفته میشه. یعنی فونت روبوتو معیار در نظر گرفته میشه و متریک‌های فونت ثانویه که می‌تونه عربی/فارسی/هندی و ... باشه نادیده گرفته میشه. حالا اگر همان فونت ثانوی رو به عنوان فونت اصلی گوشی انتخاب کنید مشکلات نمایان می‌شود. البته برخی فونت‌های عربی هم هستند که جمع و جور و هم‌اندازه با لاتین طراحی شده‌اند مثل تاهوما و دژاوو و سامسونگ و ...

**Comment by habibnajafi** [comment]
پس ینی این مشکل حل شدنی نیست؟ و‌ باید باهاش کنار بیایم
نمیشه ین نسخه ویرایش شده برای گوشی ها بذارید؟ که بولد و معمولی داشته باشه؟
برنامه همچین‌کاری رو‌‌ندارید؟

**Comment by rastikerdar** [comment]
یک نسخه با ارتفاع کم در بسته فشرده قلم قرار داده شد.
درون پوشه UI
با تشکر از شما
https://github.com/rastikerdar/vazir-font/releases
