### ISSUE TITLE
Arabic fonts do not support all letters of Arabic scripts

### ISSUE THREAD

**Issue by MuratKaribay** [rastikerdar/vazir-font#164]
Is it possible to change fonts to fully support Arabic scripts or add letters to the Vazir font used by Telegram?

![image](https://user-images.githubusercontent.com/40431755/90313101-97b48780-df2b-11ea-9ae0-15552a8fef49.png)

Can you add Arabic letters for Kazakh (Arabic), Uyghur.
And is it possible without the Arabic language ligature as in the screenshot below

![image](https://user-images.githubusercontent.com/40431755/90319490-7a4ae200-df5a-11ea-8504-f0e81ebf033e.png)

**Comment by MuratKaribay** [comment]
@rastikerdar please can you help me?

**Comment by rastikerdar** [comment]
Sorry for the late reply. There are requests to add languages to the font. Developing and maintaining a complete Typeface family is a difficult task, especially when the work is free and unsupported. I will try to add new glyphs to the font but I do not think I can add those Arabic ligatures (in the picture) at this time.

**Comment by MuratKaribay** [comment]
> Sorry for the late reply. There are requests to add languages to the font. Developing and maintaining a complete Typeface family is a difficult task, especially when the work is free and unsupported. I will try to add new glyphs to the font but I do not think I can add those Arabic ligatures (in the picture) at this time.

@rastikerdar sorry, but Arabic ligatures don't need to be added. I meant to add all Arabic letters without Arabic ligatures.
Since many languages that use the Arabic alphabet use a Perso-Arabic Style that does not need Arabic ligatures.
Can I help you with adding letters to Vazir fonts?

**Comment by MuratKaribay** [comment]
> Sorry for the late reply. There are requests to add languages to the font. Developing and maintaining a complete Typeface family is a difficult task, especially when the work is free and unsupported. I will try to add new glyphs to the font but I do not think I can add those Arabic ligatures (in the picture) at this time.

I have experience working with FontCreator and creating fonts.
Can I add glyphs to the Vazir font and send them to you?

**Comment by rastikerdar** [comment]
Thanks for this issue and thanks again for those glyphs. Added to Vazir 27.0.0.
https://github.com/rastikerdar/vazir-font/releases
