### ISSUE TITLE
 جدا شدن حروف به هنگام جاستیفای یا تراز از دو طرف در سری ۲۵ به بالا

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#168]
یکی از خوانندگان محترم وبلاگ در [پیامی](http://rastikerdar.blog.ir/1394/09/29/%D9%82%D9%84%D9%85-%D9%88%D8%B2%DB%8C%D8%B1-2#comment-W9pvi6RwUug) آورده‌اند:
>وقتی متن رو justify می‌کنم، کاراکترها کاملاً در طول خط، متصل کشیده نمی‌شن، بلکه بین کاراکترها فاصله دیده می‌شه. یعنی justify می‌شه، ولی کشیدگی کلمات درست انجام نمی‌شه و کاراکترها از هم منفصل دیده می‌شن.

این مشکل رو من تصادفا در یک مورد از صفحات وب با سری ۲۵ دیده‌ام، اگر چه در مورد فونت دیگری هم مشاهده کرده‌ام. شاید مربوط بشود به تغییر شیوه کرنینگ در سری ۲۵. اگر چه اطلاع ندارم که این موضوع در سری‌های قبل هم دیده می‌شود یا خیر.

**Comment by aminabedi68** [comment]
ظاهرا موضوع مربوط به اعمال اشتباه کرنینگ اسپیس توسط مرورگر کروم هست
(مرورگر کروم مشکل قدیمی و عمیقی با اجرای اپن تایپ روی کاراکتر فاصله داره)
(تصویر از نسخه 26 وزیر- مرورگر کروم-سایت زومیت)

![chrome_2020-09-16_00-26-43](https://user-images.githubusercontent.com/25493297/93258751-0c414700-f7b4-11ea-9011-db35193f7897.png)

**Comment by rastikerdar** [comment]
امیدوارم نرخ تکرارش پایین باشه. چون تا الان دو بار گزارش شده مگر اینکه نسخه ۲۵ به بعد هنوز رایج نشده باشه.

**Comment by rastikerdar** [comment]
به دلیل گزارشات متعدد این ایراد متاسفانه کرنینگ «ر» و فاصله در نسخه ۲۷ حذف شد. احتمالا وقتی کروم مشکلش را حل کرد این کرنینگ مجددا به فونت برگرده
