### ISSUE TITLE
Missing initial and medial forms of U+066E, U+066F, and U+06BA

### ISSUE THREAD

**Issue by dscorbett** [rastikerdar/vazir-font#169]
U+066E ARABIC LETTER DOTLESS BEH, U+066F ARABIC LETTER DOTLESS QAF, and U+06BA ARABIC LETTER NOON GHUNNA are dual-joining, but in this font, they are missing their initial and medial forms. The following image shows them in initial and medial contexts with U+0640 ARABIC TATWEEL.
![ٮـ ـٮـ ٯـ ـٯـ ںـ ـںـ](https://user-images.githubusercontent.com/1124347/94218912-89a34080-feb3-11ea-8aa3-04197ee6281e.png)

**Comment by rastikerdar** [comment]
Thanks for this issue. Those forms added to Vazir 27.0.0.
https://github.com/rastikerdar/vazir-font/releases
