### ISSUE TITLE
جداشدن حروف و جابجا شدن حروف

### ISSUE THREAD

**Issue by mojtabamoradi** [rastikerdar/vazir-font#172]
وقتی یه قسمتی از متن رو انتخاب میکنی حروف جدا و جابجا می شوند.

**Comment by mojtabamoradi** [comment]
![Untitled](https://user-images.githubusercontent.com/40674226/98778856-39068900-2408-11eb-85c3-a2fc6411497a.png)

**Comment by mojtabamoradi** [comment]
![Untitled2](https://user-images.githubusercontent.com/40674226/98778891-43c11e00-2408-11eb-8944-fdfed5f7d0c9.png)

**Comment by rastikerdar** [comment]
متشکرم برای این ایشو.
درست می‌فرمایید. در نسخه جدید که به زودی منتشر میشه این مشکل رفع میشه. این به دلیل اضافه شدن کرنینگ «ر» و «فاصله» بود که علی‌رغم مفید بودنش ناچارا به خاطر همین مشکل نمایش در کروم باید حذف بشه.

**Comment by mojtabamoradi** [comment]
سپاس از توجه شما، ازینکه به موقع پاسخگو بودید.

**Comment by rastikerdar** [comment]
در نسخه ۲۷ این مشکل مرتفع شد.
https://github.com/rastikerdar/vazir-font/releases
