### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#173]
Vazir has been in public domain so far. I don't know which license is more appropriate for this font? CC0 or OFL? Which one is better for the font/typeface community? Sometimes people ask me for permission (the license) and i have to explain to them what exactly public domain means!
What do you recommend for the next release? CC0 or OFL or something else?

**Comment by zoghal** [comment]
A font license can only contain one of 3 possible values:

- license: "APACHE2"
- license: "OFL"
- license: "UFL"

I myself choose the OFL license, so offer it to you

----

UFL example:



```
Universal Forfeit License (UFL)
Pronounced "awful"
Version 2.0

Copyright (c) [four digit year] [copyright holders]
(Based on the WTFPL, copyright 2004 Sam Hocevar)

Anyone is permitted to copy, distribute, or modify this license. More 
information at http://geekwagon.net/ufl.

This license grants more rights than possible to the general public in any
jurisdictions; known or unknown, real or fictional, and past or future. This is
not limited to governing bodies, planet, galaxy, universe, dimension, or any
other jurisdiction that can exist that has not yet been discovered.

You can copy, modify, distribute, sublicense, rename, and/or perform the work,
even for commercial purposes, without asking permission or referencing the 
original.

This work and license is provided without warranty.
```

**Comment by rastikerdar** [comment]
Thank you Saleh, OFL seems to be the best choice.
