### ISSUE TITLE
مشکل در پرینت حروف با وزیر نسخه 27 و اعداد با Vazir-FD-WOL

### ISSUE THREAD

**Issue by Ariodaad** [rastikerdar/vazir-font#176]
با سلام.
با وجود حل مشکل در فونت ارسالی در ایشیوی قبلی (وزیر تست) اما در نسخه 27 مشکل در چاپ همچنان پا بر جاست. البته مشکل ی پایانی حل شده است.
![signal-2020-11-25-100500](https://user-images.githubusercontent.com/67626745/100193178-8a367280-2f08-11eb-92fe-96c6f67489ba.jpeg)
تصویر آنچه که در پرینت حاصل شد

![sshot-72](https://user-images.githubusercontent.com/67626745/100193250-a508e700-2f08-11eb-8eb4-84af601a49d7.png)
آنچه که در خروجی قبل از پرینت در مانیتور نمایش داده می‌شود.

(قسمتهای Hide شده به علت حساسیت اطلاعات است.)

فونت بخش اسامی و اعداد آخرین نسخه وزیر 27 می‌باشد.
فونت اعداد بخش جمع ، به علت نمایش به صورت انگلیسی از وزیر با اعداد فارسی در پکیج نسخه 27 استفاده شده است.
(Vazir-FD-WOL 27)

**Comment by rastikerdar** [comment]
سلام
متشکرم برای این ایشو. متاسفانه من يـ ـيـ عربی رو فراموش کرده بودم اصلاح کنم. نسخه تمام ارقام فارسی هم اصلاح شد.
در نسخه ۲۷.۰.۲:
https://github.com/rastikerdar/vazir-font/releases

شاید بهتر باشه که نسخه قبلی رو مجددا پاک کنید. اگر باز هم مشکلی بود بفرمایید.

**Comment by Ariodaad** [comment]
> 
> 
> سلام
> متشکرم برای این ایشو. متاسفانه من يـ ـيـ عربی رو فراموش کرده بودم اصلاح کنم. نسخه تمام ارقام فارسی هم اصلاح شد.
> در نسخه ۲۷.۰.۲:
> https://github.com/rastikerdar/vazir-font/releases
> 
> شاید بهتر باشه که نسخه قبلی رو مجددا پاک کنید. اگر باز هم مشکلی بود بفرمایید.

مشکلات عنوان شده قبلی به نظر میاد رفع شده باشه. باز اگر مورد استثناء دیدم گزارش میدم. ممنون از شما بابت پیگیری و اعمال تغییرات با این سرعت. فقط موردی که عجیب به نظر میاد اینه که "ی" آخر با وجود اینکه با کیبورد استاندارد فارسی تایپ شده و عربی نیست اما در فونت وزیر ي نمایش داده میشه که عربی هستش و البته این مورد فقط در نرم افزار من اینطور هست و در نرم‌افزار‌های آفیس یا تحت وب این مورد رو ندیدم. مشکل نسخه ارقام تمام فارسی هم حل شده. با سپاس از شما
