### ISSUE TITLE
اشتباه در نام فونت نصب شده ارقام تمام فارسی بولد

### ISSUE THREAD

**Issue by Ariodaad** [rastikerdar/vazir-font#177]
![sshot-73](https://user-images.githubusercontent.com/67626745/100539026-8d06cf80-3248-11eb-94b9-a25ddfaa9288.png)
با سلام 
همانطور که در تصور مشخص است به نظر می‌اید پس از نصب فونت نسخه ارقام تمام فارسی بولد نام فونت اشتباه درج شده است. چون دو فونت با نام
Vazir FD-WOL
و
Vazir FD-WOL FD-WOL
به لیست فونت اضافه شده است.

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای گزارش این مورد. در نسخه ۲۷.۰.۳ این ایراد در تمامی حالات برطرف گردید. باز هم اگر ایرادی مشاهده فرمدید ممنون میشم اطلاع بدین.
https://github.com/rastikerdar/vazir-font/releases
