### ISSUE TITLE
Mispositioned marks above U+066E and U+066F

### ISSUE THREAD

**Issue by dscorbett** [rastikerdar/vazir-font#178]
Marks are placed too high above U+066E and U+066F; compare to their placement on U+0628. Also, they are placed too far left above U+066F.
![ٮَ بَ ٯَ قَ](https://user-images.githubusercontent.com/1124347/100547246-ae10f580-3233-11eb-9ab0-c43f4c012a28.png)

**Comment by rastikerdar** [comment]
Thank for this issue. Fixed in version 27.1.0.
