### ISSUE TITLE
U+FBBF and U+FBC0 should be spacing

### ISSUE THREAD

**Issue by dscorbett** [rastikerdar/vazir-font#179]
U+FBBF ARABIC SYMBOL RING and U+FBC0 ARABIC SYMBOL SMALL TAH ABOVE are standalone symbols. They should have spacing glyphs. However, in this font, they currently combine with adjacent letters.
![د﮿د﯀](https://user-images.githubusercontent.com/1124347/100547390-7787aa80-3234-11eb-8647-755e1260c36f.png)

**Comment by rastikerdar** [comment]
Thank for this issue. Fixed in version 27.1.0.
https://github.com/rastikerdar/vazir-font/releases
