### ISSUE TITLE
مشکل با font-size

### ISSUE THREAD

**Issue by amin3d** [rastikerdar/vazir-font#18]
به نام خدا، سلام ، وقتی فونت بصورت درصدی داد می شود، و مثلا 75 درصد وارد می شود،مشکلی  روی حرف حمزه متصل به ی بوجود می آید و حمزه را نمایش نمی دهد. من اینو در هنگام استفاده از label در bootstrap متوجه شدم.

**Comment by rastikerdar** [comment]
ابتدا تشکر می کنم برای این گزارش
در نسخه جدید همزه روی ی رو مقداری ضخیم تر کردم. احتمالا مشکل رفع شده باشه.
اگر همچنان مشکل پابرجاست مرا در جریان بگذارید.
ممنون

**Comment by amin3d** [comment]
به نام خدا، سلام، مشکل کماکان پابرجاست، وفتی سایز 75 درصد تعیین می شود دیگر ئـ دیده نمی شود

**Comment by rastikerdar** [comment]
در نسخه جدید به مقدار قابل توجهی ضخیم ترش کردم. امیدوارم مشکل برطرف شده باشه.
باز هم اگر دیده نمی شود بفرمایید تا فکری برایش کنیم.

**Comment by rastikerdar** [comment]
خب فکر می کنم توی ورژن جدید این مشکل برطرف شده باشه.
ممنونم برای گزارش این ایراد.

[rastikerdar.github.io/vazir-font/](http://rastikerdar.github.io/vazir-font/)
