### ISSUE TITLE
‫کانفیگ Fontconfig برای فونت وزیر

### ISSUE THREAD

**Issue by alihardan** [rastikerdar/vazir-font#186]
‫سلام.

‫با توجه به اینکه این فونت بین کاربران گنو/لینوکس پرطرفدار هست، شاید خوب باشه برای کانفیگ ساده‌تر، فایل fontconfig از قبل آماده و ارائه بشه تا کاربران بتونن به راحتی فونت پیش‌فرض دسکتاپ رو وزیر قرار بدن. اگر صلاح می‌دونید، میشه توضیحات این کار رو به بخش HELP یا README اضافه کرد. من اینجا کانفیگ خودم رو می‌ذارم. اگر لازم و مفید می‌دونید، شما کامل‌ترش کنید:

``` xml
~/.config/fontconfig/fonts.conf:

<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match target="font">
    <edit mode="assign" name="antialias">
      <bool>true</bool>
    </edit>
    <edit mode="assign" name="embeddedbitmap">
      <bool>false</bool>
    </edit>
    <edit name="autohint" mode="assign">
      <bool>true</bool>
    </edit>
    <edit mode="assign" name="hinting">
      <bool>true</bool>
    </edit>
    <edit mode="assign" name="hintstyle">
      <const>hintslight</const>
    </edit>
    <edit mode="assign" name="lcdfilter">
      <const>lcddefault</const>
    </edit>
    <edit mode="assign" name="rgba">
      <const>rgb</const>
    </edit>
  </match>

  <!-- Default sans-serif font -->
  <match target="pattern">
    <test qual="any" name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="same"><string>Vazir UI</string></edit>
    <edit name="family" mode="append" binding="same"><string>Roboto</string></edit>
  </match>

  <!-- Fallback fonts preference order -->
  <alias>
    <family>sans-serif</family>
    <prefer>
      <family>Vazir UI</family>
      <family>Roboto</family>
    </prefer>
  </alias>

</fontconfig>
```

‫تغییراتی که لازم داره:

* ‫افزودن پشتیبانی از Serif
* ‫افزودن پشتیبانی Monospace بوسیله‌ی Vazir Code

**Comment by rastikerdar** [comment]
سلام
ممنونم برای پیشنهادتون. به نظر میاد فایل راهنما جای بهتری باشه. مثلا یه سوال جدید به انتهای سوالات اضافه بشه و پاسخش هم نوشته بشه. البته شاید بد نباشه گفته بشه که چجوری فونت دلخواه لاتین داشته باشیم. نمیدونم مثلا این درسته یا نه:  
```xml
 <match target="pattern">
    <test qual="any" name="family"><string>sans-serif</string></test>
    <edit name="family" mode="prepend" binding="same"><string>Ubuntu</string></edit>
    <edit name="family" mode="prepend" binding="same"><string>Vazir UI</string></edit>
  </match>
```

**Comment by alihardan** [comment]
‫شاید این کدی که نوشتید بهتر باشه. صفت mode در هر دو رو prepend گذاشتین؛ فکر کنم prepend به این صورت کار می‌کنه که هر مورد رو در ابتدای لیست اولویت فونت‌ها اضافه می‌کنه. (یعنی فونت Ubuntu در ابتدا و قبل از همه‌ی اولویت‌ها قرار می‌گیره و سپس فونت Vazir UI قبل‌تر از اون واقع میشه).

‫این نکته مهمه که حتما در نمونه‌ای که قرار می‌گیره فونت وزیر مقدم باشه چون بعضی فونت‌ها (مثل DejaVu Sans) حروف فارسی/عربی هم دارن.

**Comment by rastikerdar** [comment]
بالاخره هر کی بخواد تغییر بده با اندکی دقت دستش میاد. هرچی فکر می‌کنید درسته بگذارید. حالا اگر روبوتو دوست نداشت از نسخه بدون لاتین استفاده کنه یا اینکه اول فونت دلخواه لاتین خودش رو قرار بده و بعد وزیر.

**Comment by alihardan** [comment]
‫بسیار خوب پس باید توضیحات لازم درج بشه تا کاربر راحت‌تر بتونه در کانفیگ دست ببره. ولی یک کانفیگ پیشفرض و پیشنهادی لازم هست ارائه بشه تا بدون کلنجار رفتن استفاده کنن و بره.

‫الان سؤال اینه که در نمونه کانفیگ -اگر ارائه بشه در HELP.md- چه فونت پیشفرض لاتینی برای فونت Serif قرار داده بشه؟ در مورد Sans-Serif که مشخص هست؛ فونت پیشنهادی وزیر Roboto هست و حروف لاتینش هم در فونت وزیر گنجونده شده. در مورد Monospace هم وضعیت به همین صورت هست؛ فونت Vazir Code به همراه Inconsolata یا Hack. ولی برای Serif چیزی پیشنهاد نشده. فونتی می‌خوایم با این ویژگی‌ها:

* ‫هم‌وزن Vazir UI باشه از نظر اندازه و شکل و شمایل و زیبایی.
*  ‫ فونتی رایج و پرطرفدار باشه و از مخازن توزیع‌ها قابل نصب باشه.

**Comment by rastikerdar** [comment]
راستش روبوتو فونت پیشنهادی وزیر نیست. بیشتر برای رفع مشکلات مربوط به کمبود حروف لاتین اضافه شده. البته که روبوتو انصافا فونت خوبی به ویژه برای موبایل است. در واقع وزیر خنثی است نسبت به لاتین. اما خب من فکر می‌کنم شما برای شروع همان چیزی که خودتان استفاده کرده‌اید بگذارید به مرور زمان اگر فرصت کردید با بازخوردها یا نظرات دیگران اون رو به روز کنید. حتی میشه به یک حالت حداقلی بسنده کرد و توضیحات بیشتر رو به یک مطلب آموزشی مفصل و پایدار ارجاع داد. برای وزیرکد هم بهتره که لینک صفحه مربوطه‌اش رو هم قرار داد تا کاربر بدونه که اگر مایل به استفاده از اونه باید اون رو جداگانه نصب کنه.
در مورد سریف هم شاید بد نباشه به حالت پیش‌فرش خود سیستم بسنده کرد.
