### ISSUE TITLE
حروف انگلیسی

### ISSUE THREAD

**Issue by amin3d** [rastikerdar/vazir-font#19]
به نام خدا، سلام، فکر می کنم اگر روی حروف انگلیسی یک تجدیدنظری شه خیلی خوب است، مخصوصا وقتی با حروف فارسی در کنار هم قرار می گیرند، مناسب نیستند، یعنی بقولی هارمونی ندارند
![1](https://cloud.githubusercontent.com/assets/1720529/13981666/142b063e-f103-11e5-985a-53d279e4dcd9.jpg)

**Comment by aziz** [comment]
<p dir="rtl" align="right">
قلم وزیر کاراکترهای انگلیسی ندارد. شما باید با تعریف Font-stack مناسب قلم حروف انگلیسی را تعیین کنید وگر نه مروگر بسته به سیستم عامل یک قلم Fallback برای شما استفاده می‌کند.
</p>

**Comment by amin3d** [comment]
به نام خدا، سلام، ممنون من اطلاعی نداشتم، اگر می شه یک مقدار توضیح دهی ممنون می شم، می شه این فونت استک را با فونت فیس تعریف کرد؟

**Comment by zoghal** [comment]
فکر میکنم منظور عزیز font-family بوده.
شما برای تعریف فونت فالبک باید به صورت زیر اقدام کنید. 
```
html {
    font-family: vazir,arial,tahoma;
}
```
فونت اول رو مرورگر انتخاب میکنه اگر در فونت کاراکتر مورد نظر نبود مثل انگلیسی میره سراغ فونت دوم که میشه آریل و به همین ترتیب تکرار میشه.

**Comment by ilius** [comment]
در فایرفاکس همچین امکانی وجود ندارد
ضمن اینکه در فایرفاکس به تفکیک زبان فونت ست می‌شود و زبان فارسی هم ندارد
در قسمت زبان عربی هم فونت وزیر را لیست نمی‌کند، ظاهراً فقط فونت‌هایی که پشتیبانی کامل از عربی دارند را لیست می‌کنپ

چرا کاراکترهای فارسی فونت وزیر را با فونت کاملی مثل
DejaVu Sans
که سبک و سیاقش به فونت وزیر می‌خورد قرار نمی‌دهید؟
تا یک فونت کامل و مناسب به دست بیاید
این فونت مجوزش هم با فونت وزیر یکی است

**Comment by zoghal** [comment]
>در فایرفاکس همچین امکانی بطور استاندارد و پیش‌فرض وجود ندارد
ضمن اینکه در فایرفاکس به تفکیک زبان فونت ست می‌شود و زبان فارسی هم ندارد

این مورد بحثش فرق می‌کند سعید خان.
شما در اصل دارید در مورد فونت نصب شده روی سیستم صحبت می‌کنید.

>در تنظیمات فونت زبان عربی هم فونت وزیر را لیست نمی‌کند، ظاهراً فقط فونت‌هایی که پشتیبانی کامل از عربی دارند را لیست می‌کند

@rastikerdar  رستگار این مشکل مربوط به کد پیج فونت هست. نباید همچین مشکلی باشه.


>چرا کاراکترهای فارسی فونت وزیر را با فونت کاملی مثل
DejaVu Sans
که سبک و سیاقش به فونت وزیر می‌خورد قرار نمی‌دهید؟

هر گردی گردو نیست. مشکل اصلی این هست که اکثرا فکر می‌کنند یک نوع فونت پاسخگوی همه نیاز ها هست.
همین موردی که شما میگید در وب مشکل ساز می‌شود.
در اصل نیاز هست برای کاربرد‌های مختلف نسخه‌های متعدد ایجاد شود. که این کار بسیار سخت و زمانبر می‌شود.
تا اونجا که من میدونم هدف اولیه رستگار وب هست. پس دلیلش می تونه این باشه.

از طرفی هماهنگی حروف لاتین با فارسی یک بحث دیگر هست که سلیقه در آن بسیار دخالت دارد.که خودش یک داستانی جدا برای پیاده سازی و .... دارد.

**Comment by ilius** [comment]
من می‌تونم فقط از یک فونت استفاده کنم در همه جا: مرورگر، دسکتاپ و برنامه‌ها، آفیس و غیره
غیر از کدنویسی که به فونت مونو نیاز هست، مطلقاً همه‌جا از یک فونت استفاده می‌کنم
چون چشمم عادت می‌کنه و اکثر برنامه‌ها (مثل خود دسکتاپ) امکان ست کردن لیست فونت‌ها رو ندارن
ضمن اینکه چون چشم‌هام ضعیف هست خوانایی برام خیلی مهمه
به همین دلیل حداقل سال‌هاست که از فونت ترافیک فارسی‌وب استفاده می‌کنم که خوانایی و زیبایی خیلی خوبی داره، استاندارد هست و انگلیسی هم داره. اما آزاد نیست

اگر بخوام فونت وزیر یا شبنم (که خوانایی بیشتری از بقیه دارن) رو جایگزین ترافیک کنم مجبورم خودم دو فونت آزاد رو با هم ترکیب کنم
به هر حال خواستم اول پیشنهاد بدم

**Comment by rastikerdar** [comment]
تشکر خیلی خیلی ویژه از آلن عزیز و صالح گرامی.

سعید جان تمام مواردی که صالح جان گفت حرف دل من هم هست.
اما در مورد ضعیف بودم چشم ها من هم مثل خودت هستم. عینکی بدجور!
در مورد حروف لاتین به نظرت خود فونت دژاوو که وزیر از روش ساخته شده چطوره؟ اگر فقط به همون تعداد محدود گلیف های اصلی لاتین رضایت بدی میشه توی یک پوشه مجزا قرار داد.

**Comment by rastikerdar** [comment]
راستی صالح جان این کد پیج فونت رو من نمی دونم چیه :P

**Comment by zoghal** [comment]
@rastikerdar اینجا رو میگم. https://www.dropbox.com/s/5g3ypqzlwd2hgs7/Screenshot%202016-04-01%2006.22.54.png?dl=0

**Comment by Javid-Izadfar** [comment]
دوستان ساخت یک فونت استک کار سختی نیست.
فرض کنید کسی فونت لاتین اضافه شده رو مناسب ندونه. اینطوری مجبوره حجم زیاد فونت انگلیسی رو اوِر رایت کنه.

**Comment by rastikerdar** [comment]
با اجازه ایشو رو می بندم.

صالح جان ممنون. کد پیج رو توی نسخه جدید اصلاحش کردم.
