### ISSUE TITLE
ایده وزیر ایموجی

### ISSUE THREAD

**Issue by mimsadAlef** [rastikerdar/vazir-font#195]
سلام به نظرم فونتی که انقدر دسته های مختلف داره می تونه یه دسته هم برای ایموجی داشته باشه
من خودم شخصا توی این موضوع خیلی مشکل داشتم ، توی سایت ایموجی هر کسی یه جوره
اگه ایموجی های توییتر باشه خیلی بهتره
https://github.com/twitter/twemoji

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو
این دسته‌های مختلفی که وزیر داره از سر ناچاری بوده و استاندارد نیستند. هر چه بخواهیم موارد بیشتری رو اضافه کنیم بستهٔ فونت بزرگ‌تر و نگهداریش سخت‌تر میشه. ایده ایموجی جالبه اگرچه خیلی سلیقه‌ای هست اما به هر حال شاید به عنوان یک گزینه بتونه مطرح باشه.

**Comment by mimsadAlef** [comment]
سلام آقای راستی کردار یه سوال
چجوری میشه یه فونت رو بایه فونت دیگه ترکیب کرد توی فونت فورج
من می خوام فونت وزیر رو با [این فونت](https://github.com/mozilla/twemoji-colr) ترکیب کنم تا وزیر ایموجی رو بسازم
ممنون می شم راه نماییم کنید
یه نکته ای که بگم اینه که این می خوام با github workflow پیادش کنم برای همین نیاز به روش کامند لاینی دارم

**Comment by rastikerdar** [comment]
در این لینک چند روش بیان شده:  
https://superuser.com/questions/490922/merging-two-fonts

خود وزیر از این طریق انجام میده:  
https://github.com/rastikerdar/vazir-font/blob/master/scripts/build.py

البته با دستورات فونت فورج هم خیلی ساده می‌شه انجام داد:
https://fontforge.org/docs/tutorial/scripting-tutorial.html#merging-a-type1-and-type1-expert-font-and-creating-appropriate-gsub-tables
```
#!/usr/local/bin/fontforge
Open($1)
MergeFonts($2)
Generate("output.ttf")
```
