### ISSUE TITLE
وزیرکد

### ISSUE THREAD

**Issue by morezafard** [rastikerdar/vazir-font#199]
سلام
بهتر نیست وزیرکد هم درون بسته دانلودی فونت وزیر قراربگیره؟

**Comment by mimsadX** [comment]
فونت وزیر کد فونتی کاملا مجزا از فونت وزیره دوست عزیز

**Comment by morezafard** [comment]
حالا من خیلی دقیق نمیدونم ولی به نظرم بجز مونواسپیس بودن تفاوت چندانی ندارن.
اگه به بسته دانلودی توضیحاتی اضافه بشه که وزیرکد بعنوان یه فونت مونواسپیس چه استفاده ای داره سرعت جاافتادنش در جامعه کاربرانی که از رسم الخط عربی استفاده میکنن شتاب دوچندانی پیدا میکنه و همچنین از نظر ساختار که همون فونت وزیره.

**Comment by morezafard** [comment]
> فونت وزیر کد فونتی کاملا مجزا از فونت وزیره دوست عزیز

حالا من خیلی دقیق نمیدونم ولی به نظرم بجز مونواسپیس بودن تفاوت چندانی ندارن.
اگه به بسته دانلودی توضیحاتی اضافه بشه که وزیرکد بعنوان یه فونت مونواسپیس چه استفاده ای داره سرعت جاافتادنش در جامعه کاربرانی که از رسم الخط عربی استفاده میکنن شتاب دوچندانی پیدا میکنه و همچنین از نظر ساختار که همون فونت وزیره.

**Comment by rastikerdar** [comment]
سلام
ممنونم برای پیشنهادتون.
میم صاد درست می‌فرمایند. وزیرکد سالها پیش بر مبنای وزیر نسخه قدیمی ساخته شد. عملا در حال حاضر اشتراکی بین وزیر و وزیرکد وجود نداره. وزیرکد هم دیگه توسعه پیدا نکرد.
