### ISSUE TITLE
Smoothing problem

### ISSUE THREAD

**Issue by salarcode** [rastikerdar/vazir-font#2]
قبل از هر چیز از زحماتتون تشکر می کنم
این عکسی هست از وبسایت که من میبینم
http://8pic.ir/images/wghal6xx33k03lkg3lzt.png

همونطور که نقاط قرمز نشون میده، اسموتینگ درست انجام نشده در چند نقطه
مثل اینکه در سایز کوچیک این موارد دیده میشه

تنظیمات مرورگرم جهت اطلاع:
Firefox/41.0 Windows10 x64 
Direct2D Enabled	true
DirectWrite Enabled		true
AzureCanvasBackend	direct2d 1.1

**Comment by rastikerdar** [comment]
درست می فرمایید. به نظر می آید این مشکل منحصرا در فایرفاکس تحت ویندوز و آی ای دیده می شود. البته در اندازه های خاص.  متاسفانه برای تصحیح این موضوع شکل یا حالت طراحی حروف مورد نظر باید دستخوش تغییراتی گردند. که بهای این تغییر ممکن است به از دست رفتن زیبایی یا انسجام فعلی حروف بینجامد. به هر روی اجازه دهید این گزارش باز بماند تا شاید راه حلی برایش یافت شود.

سپاسگزارم از اینکه گزارش فرمودید.

**Comment by salarcode** [comment]
به نظر من مشکل به خاطر 
Hardware Rendering
هست که کروم بهتر از بقیه انجام میده.
در هر صورت مثل اینکه راه حلی براش وجود داره و در این فونت اصلاح شده، مشکلی نیست
www.zoomit.ir/media/fonts/yekan.woff

**Comment by rastikerdar** [comment]
@salarcode 
فکر می‌کنم در نسخه ۱.۴.۴ وضعیت بهتر شده باشد. اگر برایتان مقدور است بررسی بفرمایید.

**Comment by salarcode** [comment]
بله اون زائده های اضافی حذف شدند و بهتر از قبل شد ولی همچنان نرمی کروم رو نداره
من تست کردم فونت تا اندازه 20پیکسل همین گونه هست و در 21پیکسل درست میشه
منظورم: font-size: 21px;

**Comment by rastikerdar** [comment]
من دو تصویر از سایتی که فرمودید برای مقایسه  آماده کردم. بر روی دستگاه من این چنین نشان می دهد.

![zoomit ir-yekan-font](https://github-cloud.s3.amazonaws.com/assets/3116038/10565600/5821299c-75e1-11e5-85d6-ffe2a3ceaa86.png)
![zoomit ir-mirza-font](https://github-cloud.s3.amazonaws.com/assets/3116038/10565602/5edd130e-75e1-11e5-92b4-d88e14acd4aa.png)

هر دوی این تصاویر در فایرفاکس تحت ویندوز ۷ تهیه شده اند.
فونت میرزا نسخه 1.4.4 می باشد.
نمی‌دانم در دستگاه شما نیز این چنین به نمایش در می‌آید یا خیر. عنایت داشته باشید من به جز نوع فونت هیچ چیز دیگری مانند رنگ یا اندازه را تغییر ندادم.
فکر می کنم موردی که اشاره فرمودید به طراحی و استایل فونت بر می گردد و سعی می کنم راه حلی برایش پیدا کنم.

اجازه دهید این ترد باز بماند. سپاسگزارم

**Comment by salarcode** [comment]
بله در اون سایت همانطور نمایش داده میشه یا این فرق که فونت یکان اصلاح شده کمی بهتر از سیستم شما در سیستم من نمایش داده میشه.
این هم سیستم من
![yekan vs mirza](https://github-cloud.s3.amazonaws.com/assets/1272095/10566101/9161e22e-75ea-11e5-866b-2d9a26da3e4d.png)

"هر چند که خوشبختانه هر دوی این فونت ها در مرورگرهای دیگر از جمله کروم و یا حتی فایرفاکس در گنولینوکس و سیستم عامل های موبایل دارای نمایش مطلوبی می باشند."
به گمانم شاید از دیگر دلایل ارتباط داشتن این موضوع به 
Hardware Rendering
مروگر هست.

"اجازه دهید این ترد باز بماند. سپاسگزارم"
البته، من از شما متشکرم

**Comment by salarcode** [comment]
یه اتقاف جالب
من افزونه 
Anti-Aliasing
رو نصب کردم و با انجام تنظیمات زیر تونستم فونت رو به درستی تو صفحه نمایش بدم
نمی دونم امکان این هست که این تنظیمات داخل خود فونت اعمال بشه یا نه ولی گفتم که یه بررسی بکنید
تو این صفحه توضیحاتی در این مورد هست ولی من تخصصی در طراحی فونت ندارم که ببینم میشه یا نه
تنظیم بخش symmetric smoothing
https://github.com/fontforge/fontforge/wiki/How-TT-Hinting-Works

افزونه:
https://addons.mozilla.org/en-us/firefox/addon/anti-aliasing-tuner/

نتیجه تنظیم:
![font](https://cloud.githubusercontent.com/assets/1272095/10877557/8070b51c-815c-11e5-9288-2e1c2e5c6d11.png)

**Comment by geminorum** [comment]
من این مشکل رو با ‍‍`Noto Naskh Arabic` هم دارم. ظاهرن مشکل از خود فایرفاکس هست.

**Comment by salarcode** [comment]
نه مشکل فایرفاکس نیست.
فایرفاکس و اینترنت اکسپلورر از تنظیمات سیستم استفاده می کنه در حالی که کروم اینطوری نیست و مستقل عمل می کنه.
می تونید این قضیه رو تو  اینترنت اکسپلورر هم تست کنید.

**Comment by rastikerdar** [comment]
دوستان لطفا این صفحه آزمایشی رو یه نگاهی بیندازید به نظر میاد توی آی ای مشکل کاملا رفع شده اما توی فایرفاکس خیلی جزئی! البته فکر می کنم شاید فایرفاکس روی ویندوز من مشکل داشته باشه

[http://rastikerdar.github.io/vazir-font/testhint/](http://rastikerdar.github.io/vazir-font/testhint/)

سالار عزیز! متشکرم بابت اون لینک راهنما. مراحلش رو توی قسمت اولش که توضیح داده بود رفتم اما نتیجه چندان رضایتبخش نبود. بهتر می شد اما توی کروم بدتر می شد. نمی دونم مشکل کجا بود. حتی برخی داده های فونت یکان رو که داده بودی تست کردم اما نتیجه همان بود. مسئله اینه که خود فونت فورج خوب هینتیگ رو انجام نمی ده اما خب بایه برنامه دیگه به اسم زیر خروجی گرفتم به نظر خیلی خوب انجام میده. ولی توی فایرفاکس  خیلی نشون نمیده که نمی دونم چرا.
[http://www.freetype.org/ttfautohint/](http://www.freetype.org/ttfautohint/)

به هر حال صفحه آزمایشی بالا به نظرتون بهتر شده؟

اگر این مشکل حل بشه قدم بزرگی برداشتیم.

**Comment by salarcode** [comment]
می تونم بگم که مشکل حل شد! تبریک می گم :+1:  :-)

نتیجه:
![font](https://cloud.githubusercontent.com/assets/1272095/10919644/333c87fa-8281-11e5-82bc-2ec81cd8e1d0.png)

**Comment by rastikerdar** [comment]
در نسخه 1.10 با درجه پایینی، این قابلیت اضافه گردید. خوشبختانه در کروم و آی ای بدون مشکل است. اگر در فایرفاکس مشکلی داشتید بفرمایید تا مقدار آن را بالا ببرم اگر نه که به خیر و سلامتی 
:D

با تشکر

**Comment by salarcode** [comment]
بسیار عالی، الان در فایرفاکس همانند کروم نشون میده. ولی در اینترنت اکسپلورر و اج کمی تارتر هست
نمی دونم دیگه این قضیه طبیعی هست یا نه

**Comment by salarcode** [comment]
با سایت زوم ای تی تست کردم
بله طبیعی هست
