### ISSUE TITLE
mpv مشکل رندر فونت در

### ISSUE THREAD

**Issue by Masishta** [rastikerdar/vazir-font#20]
هنگام پخش زیرنویس‌های فارسی در ام پی وی
۱- دابل کوتیشن‌های اول خط هم به صورت کاراکتر‌های مربعی نمایش داده می‌شن 
۲- اگر خطی عدد لاتین توش داشته باشه کاراکترهای فارسی بعد از عدد لاتین نمایش داده نمی‌شن

این مشکل تنها با فونت وزیر اتفاق می‌افته و با ورژن قدیمی‌تر آن میرزا مشکلی نداره

![bug_01_mirza](https://cloud.githubusercontent.com/assets/16443319/14457389/5c2b2a06-00bf-11e6-99c9-bd46d3c8d6a8.jpg)
![bug_01_vazir](https://cloud.githubusercontent.com/assets/16443319/14457381/501374c6-00bf-11e6-99a9-e41875f003d4.jpg)
![bug_02_mirza](https://cloud.githubusercontent.com/assets/16443319/14457385/523a52e2-00bf-11e6-9321-825ee2621760.jpg)
![bug_02_vazir](https://cloud.githubusercontent.com/assets/16443319/14457384/51622084-00bf-11e6-9b2c-1d5cbdea3ed8.jpg)

**Comment by zoghal** [comment]
علت اینه که فونت وزیر فونت فارسی هست. و زبان لاتین رو پوشش نمیده. شما باید از فونت مکمل استفاده کنید. یکی برای انگلیسی و یکی برای فارسی
یا فونتی که هر دو زبان رو پشتیبانی کند.:)

**Comment by Masishta** [comment]
یعنی فونت میرزا لاتین رو پوشش می‌داد؟
تا اونجایی که هم یادم میاد mpv از کتابخانه libass استفاده می‌کنه یعنی وقتی 
فونتی زبانی رو پشتیبانی نکنه پیش فرض خودش کاراکتر‌ها رو جایگزین می‌کنه

**Comment by rastikerdar** [comment]
تشکر می کنم بابت گزارش این مورد.
فونت میرزا گلیف های ارقام و علائم لاتین رو داشت. البته حروف رو نداشت. توی وزیر ارقام و علائم حذف شدند. هدف این بود که کلا گلیف های لاتین رو به سلیقه خود کاربر واگذار کنیم به ویژه در حوزه استفاده وب.
اینجا هم قاعدتا همانطور که فرمودید باید خودش جایگزین می کرد اما عجیب است که چنین نشده.
۱. آیا با فونت دیگری هم که گلیف لاتین نداشته باشه چنین مشکلی دارید؟
۲. اگر در لینوکس هستید این دستور رو یه بار بزنید و برنامه رو دوباره اجرا کنید شاید مشکل حل بشه:
fc-cache -f -v
این دستور کش فونت ها رو تازه می کنه.

**Comment by Masishta** [comment]
فونت دیگه‌ای که گلیف لاتین نداشته باشه سراغ ندارم. پیشنهادی ندارید؟
من توی نوت پد  پلاس پلاس این مشکل رو آزمودم
اونجا این مشکل نبود
۲- من بدبختانه توی ویندوز هستم

**Comment by rastikerdar** [comment]
پس باید یه فایل جدا با گلیف های لاتین هم توی بسته فونت لحاظ کنیم. خبرتون می کنم.
اما قبلش با این فونت معروف تست کنید ببینید مشکل برقراره؟
[DroidNaskh-Regular.ttf.zip](https://github.com/rastikerdar/vazir-font/files/220776/DroidNaskh-Regular.ttf.zip)

**Comment by Masishta** [comment]
بله با این فونت هم همین مشکل هست

**Comment by zoghal** [comment]
من قدیما در kvm و الان هم در https://potplayer.daum.net/ تو تنظیماتش یک گزینه تو تنظیمات زیر نیویس ها داشتم و دارم.
https://www.dropbox.com/home/Screenshots?preview=Screenshot+2016-04-15+19.42.10+(zoghal-god%27s+conflicted+copy+2016-04-15).png

فونت اصلی رو فونت فارسی و آلترنیتیو رو ... 

مشکلی ندارم. درکل potplayer رو هم پیشنهاد میکنم. معرکست.

**Comment by rastikerdar** [comment]
خب از اونجایی که در ورژن جدید حروف لاتین و علائم نیز به قلم اضافه شد دیگر مشکلی در این زمینه نخواهید داشت.
باز هم تشکر می کنم برای این ایشو.

اگر مشکلی مشاهده فرمودید ممنونم میشم در میان بگذارید.
[rastikerdar.github.io/vazir-font/](http://rastikerdar.github.io/vazir-font/)

**Comment by Masishta** [comment]
سپاس
