### ISSUE TITLE
Placement of diacritics with uni25cc dotted circle

### ISSUE THREAD

**Issue by adamiturabi** [rastikerdar/vazir-font#200]
The placement of diacritics with uni25cc Dotted Circle may need to be optimized.

Current placement:
![image](https://user-images.githubusercontent.com/61895563/118388588-d1432c00-b63e-11eb-9229-31b57e66d063.png)

Preferred placement:
![image](https://user-images.githubusercontent.com/61895563/118388537-950fcb80-b63e-11eb-8a00-f3ea9aeeb8c3.png)

**Comment by adamiturabi** [comment]
Also uni25cc displays ok in HTML on Firefox. But it does not display correctly in PDF:
![image](https://user-images.githubusercontent.com/61895563/118623624-dd1b2380-b7e1-11eb-945a-dfc9c82db04f.png)
Is the glyph missing for it?
Thanks!

**Comment by rastikerdar** [comment]
Added in the last version. Thank you.
![Screenshot at 2021-06-25 11-34-47](https://user-images.githubusercontent.com/3116038/123385435-c4edaf80-d5aa-11eb-8849-54d768cfe3bf.png)

https://github.com/rastikerdar/vazir-font/releases
