### ISSUE TITLE
فونت ساحل

### ISSUE THREAD

**Issue by habibnajafi** [rastikerdar/vazir-font#202]
سلام فونت ساحل اصلا بهینه سازی نشده برای گوشی و رابط کاربری
این فونت به مراتب از فونت وزیر زیبا تره ولی بهینه سازی نشده  و حروف نصفه نمایش داده میشه و خیلی پایین هستند حتی از نسخه متغیر هم استفاده کردیم ولی نشد فونت وزیر هم همین مشکل رو داشت
اما نسخه متغیر فونت وزیر این مشکل رو نداشت
لطفا این‌فونت رو‌بهینه سازی کنید تا حروف کمی بالاتر قرار بگیره 
اگر مثل نسخه متغیر فونت وزیر باشه خوبه
ممنون

**Comment by AbbasAlimi** [comment]
> سلام فونت ساحل اصلا بهینه سازی نشده برای گوشی و رابط کاربری این فونت به مراتب از فونت وزیر زیبا تره ولی بهینه سازی نشده و حروف نصفه نمایش داده میشه و خیلی پایین هستند حتی از نسخه متغیر هم استفاده کردیم ولی نشد فونت وزیر هم همین مشکل رو داشت اما نسخه متغیر فونت وزیر این مشکل رو نداشت لطفا این‌فونت رو‌بهینه سازی کنید تا حروف کمی بالاتر قرار بگیره اگر مثل نسخه متغیر فونت وزیر باشه خوبه ممنون

سلام
این فونت‌ها را امتحان کنید.
https://bayanbox.ir/download/7346626180324388433/Fonts.7z
