### ISSUE TITLE
تداخل خط آندرلاین با نقطه ها

### ISSUE THREAD

**Issue by Farshidmi** [rastikerdar/vazir-font#205]
با سلام و تشکر از یاسر گرامی
خط آندر لاین در نسخه های اخیر بهبود پیدا کرده است اما بازهم با نقطه ها برخورد می کند.

![image](https://user-images.githubusercontent.com/45791173/122702998-df035700-d265-11eb-9efc-0fcf5241259e.png)

با احترام
فرشید، آموزش های رایگان اسکرچ برای بچه های ایران
www.farsaran.com/scratch

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای این ایشو. در نسخه اخیر پایین‌تر آمد. ممنون
![Screenshot at 2021-06-25 11-36-19](https://user-images.githubusercontent.com/3116038/123385693-10a05900-d5ab-11eb-9871-0cfc567bedc3.png)

https://github.com/rastikerdar/vazir-font/releases
