### ISSUE TITLE
مشکل احتمالی در نمایش اعداد فارسی

### ISSUE THREAD

**Issue by emsisoftiran** [rastikerdar/vazir-font#206]
<p>با سلام</p>
<p>در ابتدا تشکر بابت فونت بسیار عالی تان</p>
<p>من یک مشکل احتمالی با فونت پیش فرض وزیر دارم. در توضیحات ثبت شده است که اگر اعداد را با کیبورد فارسی تایپ کنیم، فارسی نمایش میدهد و اگر با کیبورد انگلیسی تایپ کنیم، انگلیسی نمایش میدهد. حالا من در وبلاگ از این فونت استفاده میکنم. این قاعده در بعضی از بخش ها رعایت میشود و در بعضی از بخش ها رعایت نشده است و با اینکه من با کیبورد فارسی بارها و بارها تایپ کردم، کماکان اعداد مربوطه را انگلیسی نمایش میدهد. آیا میشود این مشکل را بررسی کنید. لینک نمونه دو مطلب در ارتباط با این مشکل در زیر است.</p>
<p><a href="https://emsisoft.co.ir/blog/security/how-to-create-manage-store-passwords">https://emsisoft.co.ir/blog/security/how-to-create-manage-store-passwords</a></p>
<p><a href="https://emsisoft.co.ir/blog/security/how-to-prevent-phishing-attacks">https://emsisoft.co.ir/blog/security/how-to-prevent-phishing-attacks</a></p>
<p>&nbsp;</p>
<p>با احترام و تشکر ویژه بابت پیگیری شما</p>
<p>محمد عابدی</p>

**Comment by rastikerdar** [comment]
با سلام و احترام
این مشکل شما به خود فونت مربوط نمی‌شود. مگر اینکه فقط با فونت وزیر این مشکل رو داشته باشید.

**Comment by emsisoftiran** [comment]
بله حق با شما بود. من فونت های دیگر را نیز بررسی کردم و این مشکل وجود داشت. ممنون از پاسخ شما
آیا شما ایده ای برای وجود این مشکل دارید؟ من از سیستم مدیریت محتوای وردپرس استفاده میکنم

**Comment by rastikerdar** [comment]
متاسفانه خیر
