### ISSUE TITLE
حرف م و حرف ر

### ISSUE THREAD

**Issue by AbbasAlimi** [rastikerdar/vazir-font#208]
سلام
به نظرم حرف م به این شکل باشد زیباتر است.
![Untitled](https://user-images.githubusercontent.com/54225036/123537275-d4ecc700-d743-11eb-9791-bc97c5f39108.png)
![Untitled2](https://user-images.githubusercontent.com/54225036/123537280-d918e480-d743-11eb-81b6-ac209baf16b4.png)

**Comment by rastikerdar** [comment]
سلام
احتمالا همچین شکلی مد نظر شماست:
![Screenshot at 2021-06-27 16-36-12](https://user-images.githubusercontent.com/3116038/123543875-e0e98080-d765-11eb-8618-99a310ae00b3.png)

**Comment by AbbasAlimi** [comment]
بله منظورم چنین شکلی بود. به نظر شما بهتر نیست؟

**Comment by AbbasAlimi** [comment]
و به نظرم اگر قسمتی از حرف ر که زیر خط زمینه قرار دارد انحنایش را کم کنید زیباتر می‌شود.
![01](https://user-images.githubusercontent.com/54225036/123583480-dde9a100-d7f4-11eb-9458-c331b926d0bb.png)
![02](https://user-images.githubusercontent.com/54225036/123583484-e17d2800-d7f4-11eb-9f68-ab92a459cb28.png)

**Comment by rastikerdar** [comment]
عباس عزیز، تغییراتی که می‌فرمایید خوب است اما حدس می‌زنم الگوی شما فونت خوب ایران‌سنس است. پیشنهاد می‌کنم اون فونت رو از فروشگاهش بخرید.

**Comment by AbbasAlimi** [comment]
آن فونت را خریداری کرده‌ام. ولی منظورم فرمی بهتر از ایران‌سنس است. انحنای وسط حرف م آن فونت، زاویه کمی دارد و زیباتر همانی بود که شما رسم کردید. در مورد حرف ر انحنای انتهای آن کم است که بیشتر شود زیباتر است.
به نظر من پیشرفت همین‌گونه بوجود می‌آید که همه کارهای پیشین را در نظر بگیریم و ارتقا دهیم.

**Comment by rastikerdar** [comment]
ببینید عباس آقای عزیز، هر تایپ‌فیسی یک سبکی داره و طراح تلاش می‌کنه تمامی حروف رو هماهنگ با هم در یک قالب طراحی کنه. شکستگی «ر» در کل تایپ‌فیس ایران‌سنس وجود داره و هماهنگه. وزیر هم سبک خودش رو داره.

نکته دوم اینکه خب اگر قراره کاری ارتقا پیدا کنه این چرا همان کار نباشه که هنوز در حال توسعه هست؟ شما با طراح همان فونتی که مد نظرتونه صحبت کنید و پیشنهاد بدین کارش رو ارتقاء بده.

در هر صورت من با اجازه برای اینکه به خاطر این ایشو شائبه‌ای پیش نیاد، می‌بندمش و تاکید می‌کنم تایپ‌فیس وزیر از ایران‌سنس الگو نگرفته. یاد گرفتن از کارهای دیگران خوبه اما شبیه شدن بهشون به ویژه وقتی که در حال توسعه و فروش هستند صحیح نیست.

تشکر می‌کنم از شما برای وقتی که گذاشتید.
