### ISSUE TITLE
هم راستا نبودن کلمات و تنظیم نبودن لاین هایت

### ISSUE THREAD

**Issue by dehghani-mehdi** [rastikerdar/vazir-font#209]
در تصویر زیر به نظر دو ایراد وجود دارد
1. فاصله حرف "ع" با پایین کمتر از فاصله حروف "و" و "ل" است. به نظر تمام کلمات باید هم راستا باشند.
2. مهتر از ایراد بالا، عدم یکسان بودن فاصله کلی کلمات از بالا و پایین است. این تصویر مربوط به یک دکمه (باتن) در صفحه وب است، این عدم تناسب باعث ایجاد نمایشی می شود که ایراد طراحی محسوب می شود و در تمامی پروژه ها مجبور به استفاده از استایل خاص برای یکسان سازی این فواصل هستیم که زمانبر است و روش مناسبی نیست.
![vazir bug](https://user-images.githubusercontent.com/9152330/125420831-c0137665-8680-4169-a25d-533ae13c5b08.png)

ضمنا استایل های اعمال شده بر روی دکمه بالا به شرح زیر است:

```
button {
    padding: 0;
    border: 0;
    display: flex;
    align-items: center;
}
```

**Comment by rastikerdar** [comment]
تشکر می‌کنم برای این ایشو
مورد اول اگر چه مفیده اما الزامی نیست. یعنی در طراحی حروف فارسی یا عربی چنین الزام یا پیشنهادی نیامده که پایین حروف باید همراستا باشه. مفیده اما طراحی آن مشکلاتی دارد. این لینک رو ببینید:
https://fonts.google.com/?subset=arabic&preview.text=%D9%86%D9%88%D8%B9%20%D8%B3%D9%88%D8%A7%D9%84&preview.text_type=custom

در مورد نکته دوم هم بلی واقعا این یک مشکل اساسی است و راه حلی مشخصی براش پیدا نکرده‌ام. ارتفاع دیگر حروف مثل «گ آ أ» رو هم در نظر بگیرید. تازه به این حروف دیگر زبان‌ها رو هم اضافه کنید مثل «ڤ ݣ». این ایشو رو ببینید:
https://github.com/rastikerdar/vazir-font/issues/110
