### ISSUE TITLE
نمایش داده شدن حروف زیری وقتی متن شفاف است

### ISSUE THREAD

**Issue by babakfp** [rastikerdar/vazir-font#210]
سلام وقت بخیر
ممنون از فونت خییییلی خوبتون. میخواستم ببینم امکانش هست که این مشکل رو برطرف کرد؟ البته فکر میکنم شاید دلیلی وجود داشته باشه که اومدین همچین طراحیش کردین.
![Screenshot 2021-07-23 161114](https://user-images.githubusercontent.com/44144724/126849536-86a54243-8a74-463c-964e-958e0a2a4270.png)
ممنون

**Comment by PersianPolaris** [comment]
من با همچین مشکلی بر نخورد!
تو چه محیطی استفاده کردین که منم تست کنم

**Comment by babakfp** [comment]
سلام
تو Adobe XD به این صورت:
![Screenshot 2021-07-24 093945](https://user-images.githubusercontent.com/44144724/126875241-0f975286-c376-4013-af37-ad2a25316767.png)

**Comment by rastikerdar** [comment]
سلام وقت شما نیز بخیر
راستش هنوز راهی پیدا نکرده‌ام. آیا با سایر فونت‌های فارسی یا عربی چنین مشکلی ندارید؟

تشابه ایشو: #72 و #38

**Comment by babakfp** [comment]
سلام وقت بخیر

> آیا با سایر فونت‌های فارسی یا عربی چنین مشکلی ندارید؟

با فونت های زیر برسی کردم و بله ظاهرا با همه فونت ها همینطوریه:

![Artboard – 1-min (2)](https://user-images.githubusercontent.com/44144724/126912927-bf04c9b7-2acb-458d-a7c1-53a483d14c84.png)


این مشکل رو همینجا توی گیتهاب برسی کردم و دقیقا همونطور بود که تو #38 گفتید.
وقتی به متن اوپسیتی داده میشه, مشکلی نیست ولی وقتی از آرجی‌بی استفاده میشه, اون نقاط اتصال دیده میشن.

با Opacity:
![Screenshot 2021-07-25 132209](https://user-images.githubusercontent.com/44144724/126912360-d852803f-f1bd-41b6-8054-ea7ab7cfc6b9.png)

با RGBA:
![Screenshot 2021-07-25 132357](https://user-images.githubusercontent.com/44144724/126912394-2be59107-7764-4f9d-93ee-d2cb2d3d45eb.png)

البته من تو ادوبی ایکس‌دی از آر‌جی‌بی‌ای استفاده نکردم, از اوپسیتی استفاده کردم.


> https://github.com/rastikerdar/vazir-font/issues/72#issuecomment-321453085

اگه همچین مشکلی وجود داشته باشه که قطعا تصمیمی که گرفته شده, تصمیم درستیه.
طبق تجربه ای که تو ادوبی ایکس‌دی داشتم این بود که وقتی ۲ تا المنت/شیپ رو میزاشتم کنار هم و زوم‌آوت میکردم, یه فاصله ای بین اون ۲ شیپ دیده میشد, در حالی که هیچ فاصله ای وجود نداشت و شیپ‌ها به هم چسبیده بودند. (با شیپ ها و المنت های خاصی این مشکل پیش میاد).
دقیقا برای حل این مشکل, مجبور میشدم که شیپ زیری رو یکم ببرم زیر شیپ بالایی.


اطلاعات فونت وزیر که استفاده میکنم:
![Screenshot 2021-07-25 132623](https://user-images.githubusercontent.com/44144724/126912936-9d52c485-e37a-468f-b160-91d4997055c8.png)

**Comment by babakfp** [comment]
خب دیگه اینو میبندم. دلیلی نداره باز بمونه.
