### ISSUE TITLE
پاک کردن فونت های پیش‌ساخته

### ISSUE THREAD

**Issue by eshagh79** [rastikerdar/vazir-font#212]
سلام.
ممنون بابت این قلم عالی.
یه پیشنهاد دارم که باعث افزایش کار نگهدارنده‌گان این فونت و راحت تر شدن کار استفاده کنندگان فونت وزیر میشه.
فکر میکنم که پوشه ‫dist نباید در سورس مخزن باشه، چون کسایی که از مخزن استفاده میکنن، احتمالا میخوان اونو توسعه و تغییر بدن و خودشون از ابتدا فونت رو کامپایل کنن، پس وجود پوشه ‫dist فقط باعث افزایش حجم مخزن میشه.
منطقا کسایی مثل من که فقط از فونت وزیر استفاده میکنن نیازی به دانلود خود مخزن ندارن.

مشکل بعد اینه که اگه بشه هر نوع از فونت هارو در یک پرونده فشرده جدا قرار داد، دانلود اون برای استفاده کنندگان راحتتر میشه.
مثلا من فقط نیاز به نسخه ضحیم و معمولی وزیر با فرمت ‫ttf دارم، ولی مجبورم که کل فونت‌ها با انواع مختلف فرمت و اندازه و ضخامت رو دانلود کنم.
اگه لطف کنید فونت‌ها رو بر اساس نوع مثلا ضخیم، ایتالیک، نازک و... جدا کنید و جداگانه بسته بندی کنید، خیلی به من و امثال من لطف میکنید.
ممنون

**Comment by rastikerdar** [comment]
سلام
راستش قرارگیری فایل‌های خروجی در مخزن فونت‌ها (و حتی دیگر انواع مخازن مثل کتابخانه‌های جاوااسکریپت و ...) امر رایجی است. کافیست نگاهی به مخازن فونت‌ها در گیت‌هاب بیندازید. در واقع خود پوشه دیستِ وزیر هم از ابتدا به درخواست کاربران برای استفاده عمومی در سی‌دی‌ان ها و همچنین عرضه به صورت ان‌پی‌ام ساخته شده.

در مورد دسته‌بندی درست می‌فرمایید. شیوه متداول در اغلب مخازن فونت‌ها جدا سازی بر اساس نوع فایل یا همان پسوند است. این موضوع چند بار گفته شده اما من هنوز برایش اقدامی نکرده‌ام و باید اسکریپت ساخت فونت رو تغییر بدم. قطعا بهتر است ساختار بسته‌بندی نهایی فونت تغییر کنه و مرتب‌تر بشه.
