### ISSUE TITLE
بروزرسانی فونت ساحل

### ISSUE THREAD

**Issue by habibnajafi** [rastikerdar/vazir-font#215]
سلام آقای راستیکردار 
فونت ساحل خیلی فونت زیبایی هست و من روی گوشی ازاون استفاده میکنم گرچه فونت وزیر بهینه شده هست اما زیبایی فونت ساحل بیشتره و حالت رسمی تری داره
اما شما انگار دست از فونت ساحل کشیدید و برنامه ای براش ندارید لطفا این فونت رو بهینه کنید و حاشیه ها رو کم کنید تا مثل نسخه متغیر فونت وزیر برای گوشی بشه استفاده کرد
ممنون

**Comment by rastikerdar** [comment]
Duplicate of #202 
سلام. تشکر می‌کنم برای این ایشو.
برای نسخه جدید ساحل احتمالا باید صبر ایوب داشته باشید چون کار اساسی و زمانبری احتیاج داره که در آینده نزدیک اتفاق نخواهد افتاد. در ثانی احتمال بازنشستگی فونت‌های وزیر و ساحل هم زیاده. پس پیشنهاد می‌کنم فونت‌های تجاریِ دارای پشتیبانی تهیه کنید یا از فونت رایگانی مثل استعداد استفاده کنید.
پیروز باشید

**Comment by habibnajafi** [comment]
سلام 
فعلا زوده برای بازنشستگی
اگر هم قراره بازنشسته بشن بهینه بشن که قابل استفاده باشه برای دستگاه های موبایل 
که اگر اپدیت هم نشد مشکلی پیش نیاد الان فونت ساحل خیلی پایینه و تو خیلی جاها نصفه نمایش داده میشه
وزیر هم نسخه متغیر خیلی خوبه برای گوشی
ممنون از زحماتتون
خدا خیر بده به شما

**Comment by rastikerdar** [comment]
من برای شما یک نسخه سفارشی با ارتفاع کم ضمیمه کردم. امیدوارم همون چیزی باشه که می‌خواهید. اگه مشکلی داشتید بگید:
[Sahel-Customized.zip](https://github.com/rastikerdar/vazir-font/files/7187435/Sahel-Customized.zip)

**Comment by habibnajafi** [comment]
سلام ممنون از ژحمت شما متاسفانه این نسخه هم مشکل داره مثل روی واتساپ تست کردم و برخی جاها اصلا متن رو نمایش نمیده
![IMG_20211117_133402](https://user-images.githubusercontent.com/714767/142179885-a7ac2053-d3d4-4ca7-aeac-87989ace7af3.jpg)
اما فونت وزیر خوب نمایش داده میشه مخصوصا نسخه متغیر که عالی هست اگر طبق نسخه متغیر ویز بود عالی میشد
اما فونت ساحل خیلی قشنگ و زیبا هست برای استفاده روی گوشی
