### ISSUE TITLE
اسکریپت ساخت قلم جدید

### ISSUE THREAD

**Issue by eshagh79** [rastikerdar/vazir-font#222]
سلام
من یه اسکریپت بش ساده‌تر از اسکریپت فعلی که برای ایجاد قلم‌ها استفاده میکنید نوشتم، اگه وقت دارید اون رو امتحان کنید.
اگه مشکلی هم در اون هست بگید تا اصلاحش کنم.(البته مشکل که زیاد داره)
روش استفاده‌اش هم اینطوره که، اسکریپت رو در پوشه اصلی(نه پوشه اسکریپت‌ها) قرار میدین و در خط فرمان `‎./makefont.sh all` رو میزنید.
این اسکریپت چند تا گزینه هم داره که میتونید استفاده کنید، برای دیدن گزینه‌ها هم دستور `‎./makefont.sh help` رو بزنید.
و اینکه سه تا حالت مختلف برای درست کردن پرونده‌های فشرده داره. بر اساس پوشه، نوع، و قالب، که به صورت پیشفرض بر اساس پوشه؛ قلم ها رو جدا و فشرده میکنه.

امیدوارم که با این کار کمکی به این پروژه کرده باشم.
[makefont.zip](https://github.com/rastikerdar/vazir-font/files/7532395/makefont.zip)

**Comment by rastikerdar** [comment]
سلام
ممنونم برای این ایشو و اسکریپتی که نوشتید.
ببخشید دیر پاسخ میدم. راستش قراره این پروژه با اسکریپت جدید در مخزنی دیگر منتشر بشه و چون ساختاز خروجی‌ها عوض شده من سعی می‌کنم تا اونجایی که بتونم تغییرات شما رو در اونجا اعمال می‌کنم.

**Comment by eshagh79** [comment]
اینشالا که به کارتون بیاد.
