### ISSUE TITLE
فاصله کاراکترها در ios

### ISSUE THREAD

**Issue by hdd064** [rastikerdar/vazir-font#23]
سلام
اسکرین شات ها از سایت فارس نیوز در آفون ۵ با ios نسخه ۹.۳ گرفته شده. فقط تیتر این مشکل رو داره و باقی متن مشکلی نداره.
![img_1221](https://cloud.githubusercontent.com/assets/1020603/15074321/8ac662fc-13b3-11e6-9b29-65696fae0593.PNG)
![img_1222](https://cloud.githubusercontent.com/assets/1020603/15074322/8acdb430-13b3-11e6-933b-363099a7fcb2.PNG)

**Comment by rastikerdar** [comment]
سلام
از شما تشکر می کنم برای گزارش این ایراد.
آیا با صفحه نخست وزیر هم این مشکل رو دارید؟
[http://rastikerdar.github.io/vazir-font/](http://rastikerdar.github.io/vazir-font/)

نسخه ای که در فارس استفاده میشه سری یک (قدیمی) وزیر هست اما مشکلش عجیبه! متاسفانه من هم دسترسی به دستگاه آیفون ندارم.

**Comment by hdd064** [comment]
سلام
فونت داخل صفحه وزیر رو الان با آیفون تست کردم بدون مشکل نمایش داده میشه.
ممنون از شما
