### ISSUE TITLE
خطا در فایرفاکس

### ISSUE THREAD

**Issue by mahmoudmy** [rastikerdar/vazir-font#24]
با سلام
در مرورگر فایرفاکس نسخه 47 هنگام بارگذاری نسخه بولد خطای زیر در کنسول ظاهر می‌شود:
`downloadable font: MATH: failed to parse MathVariants table, table discarded (font-family: "Vazir" style:normal weight:bold stretch:normal src index:1) source: http://localhost:3000/assets/fonts/Vazir-Bold.woff`
داستان چیست؟

**Comment by rastikerdar** [comment]
سلام مشتکرم برای این ایشو
عجیبه! وزیر نسخه ۳ منتشر شده. شاید توی نسخه جدید دیگر این مشکل نباشه
حقیقتش اصلا نمی دونم معنیش چیه. ندیده بودم تا حالا!

**Comment by geminorum** [comment]
نمیدونم دقیقن مرتبطه یا نه اما ظاهرن
- گیت، لاین اندیگ فایل‌های فانت رو هم دست میزنه. من از حالت اتوماتیک گیت دراوردم.
- فایل فانت دروید نسخی که روی پروژه‌ام بوده رو تغییر داد و روی سافاری لود نمیشد.
- بعد، گیت اتریبیوتز اضافه کردم برای پسوند‌های فانت‌ها تا اونها رو باینری در نظر بگیره:
‍‍`.gitattributes`

```
*.woff binary
*.woff2 binary
*.ttf binary
*.eot binary
```

**Comment by mahmoudmy** [comment]
به نظر میاد در ورژن جدید (3.1.0) این مشکل حل شده

با تشکر

**Comment by rastikerdar** [comment]
توی نسخه بعدی امیدوارم تصحیح بشه.

**Comment by rastikerdar** [comment]
امیدوارم توی این نسخه های اخیر این مشکل برطرف شده باشه. اگر همچنان ایراد برقرار بود ایشو را دوباره باز بفرمایید.
با تشکر از آقا ناصر برای راهنمایی های خوبشون.

سپاس از همگی
