### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by Javid-Izadfar** [rastikerdar/vazir-font#25]
آروان کلود یک کتابخانه به عنوان سی‌دی‌ان در ایران راه انداخته که وزیر هم داخلش هست
https://lib.arvancloud.com/vazir

**Comment by rastikerdar** [comment]
به نظر میاد آروان فونت‌ها رو آپدیت نمی‌کنه. روشی که سی‌دی‌ان‌های دیگر به ویژه برای تحویل نسخه بروز کتابخانه‌ها ارائه می‌دهند بسیار کارآمد و مفید است. فکر می‌کنم آروان هم بهتره روشی مشابه رو پیگیری کنه.
