### ISSUE TITLE
فونت وزیر همون فونت صمیم هست!

### ISSUE THREAD

**Issue by mortaza7khat** [rastikerdar/vazir-font#26]
با تشکر از شما که این فونت ها رو ازاد منتشر کردید
لطفا خودتون صفحه مقایسه رو یه چک بکنید فونت صمیم و وزیر یکی هستند !!! فقط فونت وزیر ضخیم تر هست و سایزش بزرگتر به نظر میرسه!!!

**Comment by rastikerdar** [comment]
حق با شماست. در نمای کلی شبیه به صمیم است اما در جزيیات تفاوت زیادی دارند. برای مثال شکل ی و ـی را در هر دو مقایسه کنید یا الف، فـ، ط، ...
هر چه اندازه فونت را بزرگتر نمایید تفاوت ها بیشتر و آشکار تر می گردد به طوری که یکی را بر دیگری ترجیح می دهید.

وزیر سری ۱ با صمیم تفاوت آشکاری داشت اما در وزیر ۲ و ۳ شکل قلم دچار تغییرات زیادی شد و خب به صمیم نزدیک شد.
اکنون برخی وزیر یک را بیشتر می پسندند و برخی سه! شاید یه روز یه نفر سری یک رو جداگانه توسعه بده.

متشکرم برای نظرتون.

**Comment by rastikerdar** [comment]
خب ورژن جدید فونت یعنی نسخه ۴ تغییرات زیادی پیدا کرد و سعی شد تا حدودی دوباره به سبک وزیر سری یک برگردد.
امیدوارم این شباهت کاسته شده باشه.
[rastikerdar.github.io/vazir-font/](http://rastikerdar.github.io/vazir-font/)

اگر ایرادی در قلم مشاهده فرمودید خوشحال میشم در میان بگذارید. با اجازه این ایشو رو میبندم.
