### ISSUE TITLE
کم بودن ارتفاع فونت ها

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#27]
یکی از دوستان در پیامی فرموده اند که فونت های وزیر و شبنم و ... عموما ارتفاع کمی دارند.
لااقل برای وزیر و ساحل خود من هم چنین احساسی دارم.

**Comment by zoghal** [comment]
دقیقا منضور از ارتفاع چیه؟ ارتفاع حروف؟ ارتفاع کلی خط ؟ ارتفاع حروف کشیده نسبت به سایر حروف؟ یک اسکرین شات بزار دقیقا بفهمیم برادر مشکل چیست.

**Comment by rastikerdar** [comment]
البته دوستمون به این هم اشاره کردند که:
**اگه ارتفاع دندانه ها بیشتر بود خیلی بهتر شاید میشدند.**

**Comment by rastikerdar** [comment]
یا مثلا ر و ص ...
یا چشمی ها مثلا درشت تر بود

**Comment by zoghal** [comment]
اصولا در  سبک‌های منولاین و خطوط غیر تحصیلی  ارتفاع دندانه ها ۱/۲ ارتفاع الف هست.
در خطوط تحصیلی و آنهایی که سبک نسخ و نستعلیق دارند (دور زیادی دارند) کمی کوتاه تر گرفته میشه که بد قیافه نشه دندانه ها.

اما اینها متغییر هستند و به نیاز و انتخاب طراح میتونه کم و زیاد شوند.
در نتیجه هرچی آشپزش بگه همونه

**Comment by rastikerdar** [comment]
انتهای قضیه اینه که فونت چشم نواز بشه ولی ای کاش صالح جان یه روزی این گونه اطلاعات یا دانش مربوط به طراحی حروف رو که داری برای جامعه مستند کنی حالا چه تجاری چه رایگان چون خیلی کمک می کنه.

**Comment by rastikerdar** [comment]
با تغییراتی که توی ارتفاع گلیف های مختلف در فونت ها دادم فکر می کنم این مشکل برطرف شده باشه.
از صالح عزیز هم تشکر می کنم.

**Comment by zoghal** [comment]
> انتهای قضیه اینه که فونت چشم نواز بشه ولی ای کاش صالح جان یه روزی این گونه اطلاعات یا دانش مربوط به طراحی حروف رو که داری برای جامعه مستند کنی حالا چه تجاری چه رایگان چون خیلی کمک می کنه.

پوزش من متوجه این نشده بودم. دقیقا همینکارو دارم میکنم و خوشبختانه تموم شد. فقط باید در قالب یک سند رسمی تنظیم بشه و به کتابخانه ملی تحویل داده بشه.
و البته یک نسخه نمایشی هم داره. که دارم روش فکر میکنم چه طوری بهتر هست نمایش داده بشه این داکیومنت ها.
