### ISSUE TITLE
واو آخر چسبان

### ISSUE THREAD

**Issue by WebNashr** [rastikerdar/vazir-font#28]
به نظر می رسد ضخامت محل اتصال واو آخر چسبان اندکی از ضخامت بقیه فونت بیشتر است و در اندازه های بزرگ دیده می شود. مثلا:
![default](https://cloud.githubusercontent.com/assets/7099274/17464178/989c7442-5ced-11e6-927f-89d8d250579b.png)

**Comment by rastikerdar** [comment]
اگر امکانش هست یه نگاه کوچولو بیندازید ببینید آیا در آخرین نسخه دچار این مشکل می باشید یا خیر؟
تا اگر چنین باشد در نسخه آتی که نسخه کاملتر فونت شامل حروف لاتین خواهد بود این اشکال برطرف گردد.

متشکرم
لطفا باز هم اگر اشکالی دیدید یا پیشنهادی به ویژه در مورد ظاهر قلم داشتید ممنون میشم در میان بگذارید.

**Comment by WebNashr** [comment]
من هم می خوام از شما بابت این فونت تشکر کنم :)

**Comment by rastikerdar** [comment]
یه نسخه جدید از فونت منتشر شد که تغییرات فراوانی در ظاهرش داره اگرچه احتمالا مشکلاتی داشته باشه. اما امیدوارم این مشکل برطرف شده باشه.
اگر دیدید بهتر نشده لطفا در جریان بگذارید تا در نسخه های بعدی مد نظر قرار یگیره.
[rastikerdar.github.io/vazir-font/test.html](http://rastikerdar.github.io/vazir-font/test.html)

**Comment by WebNashr** [comment]
این مشکل در نسخه جدید برطرف شده باز هم ممنون
