### ISSUE TITLE
Persian Digits Are Gone?!

### ISSUE THREAD

**Issue by ykh** [rastikerdar/vazir-font#29]
Hi
I just got the latest version `^3.1.0` via Bower, but I could not found that version which supported Persian Digits!

**Comment by rastikerdar** [comment]
سلام
نسخه تمام ارقام فارسی توی باور نیست. آخه فکر نمی کردم کسی برای وب نیاز داشته باشه.
حالا توی نسخه آتی قرار شد حروف لاتین هم اضافه بشه.
مدیریت نسخه های متعدد حالت های فونت آن هم برای ۵ وزن یکم داره برایم سخت میشه.

**Comment by behdad** [comment]
> مدیریت نسخه های متعدد حالت های فونت آن هم برای ۵ وزن یکم داره برایم سخت میشه.

You need a build system.  Check out Khaled Hosny's fonts for example:
https://github.com/khaledhosny

**Comment by rastikerdar** [comment]
درسته همینطوره که می فرمایید آقا بهداد. بابت پیشنهادتون ممنونم
امیدوارم بتونم هم یادش بگیرم هم پیاده کنم.

**Comment by rastikerdar** [comment]
از اونجایی که نسخه‌های متعدد در درون بسته و همچنین مخزن قرار داده شده که چه از طریق سی‌دی‌ان و چه از طریق نصب بواسطه ان‌پی‌ام قابل استفاده می‌باشند و البته منسوخ شدن باور در این دوره، فکر می‌کنم عملا این ایشو حل شده باشه. در غیر اینصورت ایشو رو مجددا باز بفرمایید.

همچنین بیلد سیستم مجتمع توانست کار مدیریت فونت‌ها رو ساده‌تر کنه. با تشکر از آقا بهداد عزیز برای پیشنهاد خوبشون.

**Comment by ykh** [comment]
چهااار سال بعد :smile: 
حتی فراموش کرده بودم که باور ـی بوده کلا
نوستالژی شد
ممنون، موفق باشید
