### ISSUE TITLE
وضوح در سایز پایین

### ISSUE THREAD

**Issue by abisar** [rastikerdar/vazir-font#30]
سلام و تشکر برای وقتی که گذاشتین برای بهتر کردن نوشتار وب.
از انتشار فونت تهوما 22 سال میگذره ولی هنوز هیچ فونت فارسی نیست که وضوح وخوانایی تهوما رو در اندازه 14 پیکسل داشته باشه:

![12](https://cloud.githubusercontent.com/assets/18389149/17526520/d191cf78-5e7c-11e6-9973-90b3374cf4cf.png)

ـــــــــــــــــــــــــــــــــــــــــ

![11](https://cloud.githubusercontent.com/assets/18389149/17526524/d75f06f0-5e7c-11e6-96c1-ecc88deb017f.png)

برای وزیر هم همینطوره. دلیلش چیه؟

**Comment by zoghal** [comment]
با اجازه صابر خان:
از نظر وضوع (نمایش و کیفیت ضاهری)که در یک حد هستند.

اما اگر منظور شما مواردی همچون فواصل بین حروف و درشت بودن هیکل حروف هست. با یک تست ساده می‌تونید متوجه علت شوید. سایز فونت رو بالا ببرید. آن موقع هم وزیر از نظر زیباشناسی باز مورد قبول واقع می‌شود. اما تاهوما خیر.
در اصل تاهوما برای سایز‌های ریز با خصوصیات خاص (نمایشی/زیباشناسی حروف)طراحی شده. اما وزیر برای مصارف بیشتر از چند سایز  به همین خاطر باید از پس  حالات دیگر هم بر بی آید.

**Comment by mrasekh** [comment]
خیر، متاسفانه با نظرتون مخالفم. به این چند مورد توجه کنید:


![2222](https://cloud.githubusercontent.com/assets/18389149/17582734/80888dbe-5fc2-11e6-8a52-7c815feb0434.png)


فقط وزیر اینطور نیست. همه فونت‌های ایرانی انگار که مقداری مات و غیر شفافند (مخصوصا در نقطه‌ها و جاهایی که خمیدگی هست). فقط هم با مقایسه با تهوما یا فونت سِگوُ میشه تفاوت رو  به خوبی دید.

اندازه ۱۴پیکسل بیشتر از ۹۰ درصد وب رو تشکیل میده و وقتی این غیرشفافی که به نظر خیلی جزئی میاد در چند پاراگراف قرار میگیره خیلی خودشو نشون میده.

**Comment by rastikerdar** [comment]
سلام.
تشکر می کنم برای این ایشو. 
قبل از هر چیز اشاره کنم امیدوارم در نسخه چهار فونت وزیر که امروز منتشر شد وضعیت بهتری مشاهده بفرمایید.

من با اجازه یه توضیح اضافه در ادامه صحبت صالح جان عرض می کنم:
کاملا درست می فرمایید. فونت های فارسی کمی مات می باشند. این در فونت های لاتین هم دیده میشه. برخی بسیار شفاف یا شارپ هستند. خب در واقع این نوع فونت ها بیت مپی می باشند:
[https://en.wikipedia.org/wiki/Computer_font#Bitmap_fonts](https://en.wikipedia.org/wiki/Computer_font#Bitmap_fonts)
توی این نوع فونت ها یه سری آرایه مربوط به همه گلیف ها برای نمایش در سایز های مختلف ذخیره شده. مثلا سایز ۸ و ۱۰ و ۱۴ و ... در واقع موقع رندر صرفا این آرایه ها نگاشت میشن به پیکسل ها.
اگر دقت کنید همین فونت تاهوما در همه اندازه شکل یکسان نداره و وقتی خیلی بزرگش کنید شکل جدیدی میبینید چرا که اساسا نحوه رندر فونت عوض میشه و از حالت بیت مپی خارج میشه.

اما اینکه برای رندر فونت چه اتفاقاتی میفته و چه مکانیزم هایی درگیر ماجرا میشه اجمالا توی این لینک ها می توانید بخوانید و ببینید:
[https://www.typotheque.com/articles/hinting](https://www.typotheque.com/articles/hinting)
[تایپوگرافی مناسب در وب](http://novin-it.net/%d8%aa%d8%a7%db%8c%d9%be%d9%88%da%af%d8%b1%d8%a7%d9%81%db%8c-%d9%85%d9%86%d8%a7%d8%b3%d8%a8-%d8%af%d8%b1-%d9%88%d8%a8/)

توی این لینک یک نفر اومده فونت های مختلفی رو برای کد نویسی مقایسه کرده که می تونید ببینید در بخش نخست، فونت های غیر بیت مپی هستند که اندکی مات می باشند اما بخش آخر فونت های بیت مپی نمایش داده که کاملا شارپ اما خب پیکسلی هستند.
[http://charlesleifer.com/blog/monospace-font-favorites/](http://charlesleifer.com/blog/monospace-font-favorites/)

**Comment by mrasekh** [comment]
تشکر برای پاسخ خوبتون.
در نسخه ۴ وزن لایت، ضخامت و شفافی خیلی بهتر شده ولی هنوز مقداری ماتی مخصوصا در حروف "س" و "ش" و بعضی از نقطه‌ها وجود داره
ولی تا همین‌جا هم شخصا این فونت را به فونت‌های مشابه مثله ایران‌سنس ترجیح میدم.

البته یه مورد قابل توجه هم اینه که هر وزن از این نوع فونت‌های ماکروسافت حدود ۸۰۰کیلوبایت هست که بیشترش بخاطر تعداد کاراکتر هاست ولی باز نمیشه با ۸۰ کیلوبات این فونت مقایسه کرد.

**Comment by mrasekh** [comment]
اگه امکانش هست لطفا یک نسخه که کاراکتر‌های لاتین را نداشته باشه رو بزارین که فقط شامل فارسی باشه.
الان در نسخه چهار نمیشه در استایل فونت انگلیسی رو تغییر داد.

**Comment by rastikerdar** [comment]
@mrasekh 
نسخه ای که مد نظر شماست در بسته اصلی دانلود فونت موجود می باشد.
توی صفحه اصلی فونت روی دانلود کلیک کنید:
[rastikerdar.github.io/vazir-font/](http://rastikerdar.github.io/vazir-font/)

فایل رو که باز کنید چند نسخه از فونت وجود داره که هر کدام مناسب بود استفاده بفرمایید.

**Comment by rastikerdar** [comment]
خب فکر می کنم به این ایشو به نوعی رسیدگی شد. اگر همچنان مشکل دارید ایشو را مجددا باز بفرمایید.
با تشکر از همگی
