### ISSUE TITLE
woff2

### ISSUE THREAD

**Issue by WebNashr** [rastikerdar/vazir-font#31]
البته این بیشتر یک پیشنهاده ولی ظاهرا در مرورگر های جدید از فونت های
 woff2 
پشتیبانی می شه که از نظر حجم هم کمتر از فرمت های دیگه است لطفا فونت رو با این فرمت هم منتشر کنید.

**Comment by sIiiS** [comment]
منم موافق هستم
این فرمت جدیدتر هست و حجم کمتری داره

**Comment by hamidabbaszadeh** [comment]
اگر این فرمت هم اضافه بشه که عالی خواهد شد. البته تفاوت حجم چشم‌گیری بین woff و woff2 وجود ندارد.

**Comment by zoghal** [comment]
@rastikerdar  صابر جان اگر لینوکس کار می‌کنی می‌تونی از این ابزار برای ایجاد این فرمت استفاده کنی 👍 
https://github.com/google/woff2
اگر ویندوز کار میکنی بگو تا برات فایل‌های exe رو ارسال کنم. روی ویندوز کامپایل کردنش کمی داستان داره.

**Comment by sIiiS** [comment]
نمیشه از سایت‌هایی که واسه تبدیل فونت هستند استفاده کرد؟
مثلا : https://everythingfonts.com/woff-to-woff2

**Comment by rastikerdar** [comment]
در ورژن اخیر اضافه گردید. متشکرم.
