### ISSUE TITLE
رفتن اعراب زیر تشدید

### ISSUE THREAD

**Issue by Navid-9696** [rastikerdar/vazir-font#312]
با سلام و خسته نباشید
من یک سوالی داشتم ممنون میشم راهنمایی کنید
فونت به صورت عادی مثلا b nazanin همه چیش درسته ولی وقتی حتی تغییری توش ایجاد نمیکنم با برنامه fontlab و fontcreator pro اکسپورت که میزنم هر اعرابی که میزنم میره میچسبه به تشدید
به عنوان مثال میخوام بنویسم امّا من خِیلی خوابم میاد اینطور مینویسه امِّا من خیلی خوابم میاد
یا میخواستم راهنمایی کنید جهت برطرف کردن این موضوع یا به شما سفارش بدم برام انجام بدید

**Comment by zoghal** [comment]
فونت‌های سری بی قدیمی هستند و اوپن تایپ اونها وقتی تو ادیتورها باز میشه چون خطا دارند در خروجی ایگنور میشن.

**Comment by typoman** [comment]
> با سلام و خسته نباشید من یک سوالی داشتم ممنون میشم راهنمایی کنید فونت به صورت عادی مثلا b nazanin همه چیش درسته ولی وقتی حتی تغییری توش ایجاد نمیکنم با برنامه fontlab و fontcreator pro اکسپورت که میزنم هر اعرابی که میزنم میره میچسبه به تشدید به عنوان مثال میخوام بنویسم امّا من خِیلی خوابم میاد اینطور مینویسه امِّا من خیلی خوابم میاد یا میخواستم راهنمایی کنید جهت برطرف کردن این موضوع یا به شما سفارش بدم برام انجام بدید

در استاندارد  w3c اینجوری نوشته شده و فونت وزیر هم همین استانداردو دنبال می‌کنه:

https://www.w3.org/TR/alreq/#h_diacritics
