### ISSUE TITLE
align نبودن متون فارسی و انگلیسی

### ISSUE THREAD

**Issue by sinatajikjs** [rastikerdar/vazir-font#319]
As a Frontend developer who uses Vazirmatn i expect the font to align english and persian texts properly. as you can see in the image below the "IOS" stands upper than "دانلود برای"
<br/>
![Screenshot from 2024-03-12 12-40-49](https://github.com/rastikerdar/vazirmatn/assets/102314451/e9c6dadd-ef63-4cec-8da3-2903082bc9e1)
```
<p>دانلود برای IOS</p>
```

**Comment by Borderliner** [comment]
This has been a problem since forever. Put each part in different <p> tags and margin-top the English one.

**Comment by mrezakootvaal** [comment]
> As a Frontend developer who uses Vazirmatn i expect the font to align english and persian texts properly. as you can see in the image below the "IOS" stands upper than "دانلود برای" ![Screenshot from 2024-03-12 12-40-49](https://private-user-images.githubusercontent.com/102314451/312010939-e9c6dadd-ef63-4cec-8da3-2903082bc9e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3ODM1MjksIm5iZiI6MTcxNTc4MzIyOSwicGF0aCI6Ii8xMDIzMTQ0NTEvMzEyMDEwOTM5LWU5YzZkYWRkLWVmNjMtNGNlYy04ZGEzLTI5MDMwODJiYzllMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxNDI3MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjY0NmIwMDNkNzhlNTQ4ZDA3MTEwYjQyZWVkYmRjMTI1ZDk2ZDlhNjcxODcyOWU4ZDU4NjFhNjBiNWIwMmU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.a9GkyjhIts4xdyXmTviPyE7UGVmDlwWqFikjIuhlShg)
> 
> ```
> <p>دانلود برای IOS</p>
> ```

Hello. The creator of this font (Saber Rastikerdar) recently passed away due to cancer .🤦‍♂️😔. This project is currently orphaned and will not be updated.
For more Information check out his wikipedia page: 
https://en.wikipedia.org/wiki/Saber_Rastikerdar

**Comment by sinatajikjs** [comment]
Thank you for informing us, and may Saber Rastikerdar rest in peace. 🙏😔
