### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by SMAH1** [rastikerdar/vazir-font#32]
![1](https://cloud.githubusercontent.com/assets/21136680/17829111/df813652-66b8-11e6-8304-05687874cee3.png)
![2](https://cloud.githubusercontent.com/assets/21136680/17829112/df87d3c2-66b8-11e6-82cd-d80ee0ce0e07.png)
![3](https://cloud.githubusercontent.com/assets/21136680/17829113/df8ac4a6-66b8-11e6-972b-b06a55df5472.png)

**Comment by zoghal** [comment]
@rastikerdar صابر جان هنگام استفاده از ttfautohinting از پارامتر n- هم استفاده کن.

>   -n, --no-info              don't add ttfautohint info

تو ویندوز وقتی یک فونتی که قبلا نصب شده و نسخه جدیدش رو نصب می‌کنی یکی از آیتم‌هایی که ویندوز به اون دقت میکنه برای رفرش کردن کش فونت همین متاتگ version هست. اگر این گزینه ثابت بمونه برای اعمال فونت جدید باید ریستارت کنه تا سرویس فونت کش ویندوز رفرش بشه.

**Comment by rastikerdar** [comment]
تشکر می کنم برای گزارش این مورد.

خیلی عجیبه صالح جان چون من الان بررسی کردم دیدم ورژن همشون ۴ هست! نمی دونم دیگه کدوم متاتگ رو باید به روز می کردم.

**Comment by zoghal** [comment]
در سورس همه چی درست هست. اما وقتی  خروجی ها رو با ttfautohinting، هینتینگ میدی این اتفاق می‌افته. که راهش رو گفتم. با استفاده از اون پارامتر مشکل حل میشه.

**Comment by rastikerdar** [comment]
توی نسخه جدید یعنی 4.1.0 طبق روشی که صالح عزیز اشاره کرد انجام دادم امیدوارم مشکل برطرف شده باشه.
اگر مشکل همچنان برقرار بود ایشو رو دوباره باز بفرمایید.

متشکرم از همگی
