### ISSUE TITLE
ورژن متوسط؟

### ISSUE THREAD

**Issue by sIiiS** [rastikerdar/vazir-font#34]
در نسخه نهایی که الان هست یعنی 4.1 ورژن متوسط دیده نمیشه و داخل بسته وجود نداره
برداشته شده کلا یا فراموش شده؟

**Comment by rastikerdar** [comment]
سری چهار چون تغییرات زیادی کرد وزن های ضخیم و نازک دوباره ساخته شد. دیگه فرصت نکردم متوسطش رو هم ایجاد کنم.

اجازه بدین ایشو باز و در لیست نیازها بمونه.
با تشکر

**Comment by sIiiS** [comment]
ممنون از شما
اگر باشه که خیلی خوب میشه تا بسته به صورت کامل و استاندارد در بیاد

**Comment by rastikerdar** [comment]
در ورژن اخیر اضافه گردید. متشکرم.
