### ISSUE TITLE
همزه

### ISSUE THREAD

**Issue by mihan2** [rastikerdar/vazir-font#35]
ممنون از زحماتتان
نمی‌دونم چرا وقتی با فونت‌های شما با چاپگر لیزری پرینت می‌گیرم همزه می‌پرد بالا و جایش عوض می‌شود 
البته در پی دی اف درست است 

![hamze](https://cloud.githubusercontent.com/assets/20745136/18754714/7d7e511c-80f6-11e6-9380-33d743380bfb.png)

**Comment by zoghal** [comment]
@mihan2 این مشکل دیگه آخرش بود:)) انتظار هر چیزی رو داشتم الا این شکلی شو.
دوست عزیز راهنمایی میکینید و توضیح میدید در چه سیستم عاملی؟
با چه نرم افزاری کار می‌کنید؟
و اینکه همین دو کلمه رو میشه دقیقا همینجا کپی پیست کنید؟ تا دقیقا ببینیم چی وارد شده وعلت چیست.
نکته بعدی اینکه ایا امکان خروجی گرفتن به فرمت png مقدور هست یک نمونه بگیرید ببینید مشکل وجود داره یا نه.

**Comment by mihan2** [comment]
سیستم عامل ویندوز ۷ 
هم ورد ۲۰۱۳ و هم ایندیزاین
هرچه همزه هست جایش عوض می‌شود 
چاپگر ۲۰۵۵ اچ پی و ام ۴۰۱ اچ پی
البته در پی دی اف درست است
من از چاپ شده عکس گرفتم
خروجی های دیگر درست است
وقتی فونتهای ایشان به پرینتر فرستاده می‌شود احتمالاً ویزگی مارک به هم می‌ریزد 
که جالب است و تاکنون ندیده بودم
شاید مشکل از فونت فورج باشد

**Comment by rastikerdar** [comment]
عجیبه! چون الان پرینت گرفتم مشکلی نداشت. هممممم. یعنی از چی می تونه باشه!
![hamzeh](https://cloud.githubusercontent.com/assets/3116038/18788118/89934f2c-81b2-11e6-9e8e-48fe16f59aed.jpg)

**Comment by zoghal** [comment]
از اونجا که واقعا عجیبه پیشنهاد میکنم مودم Adsl تان  را خاموش روشن نمایید  :)))

@mihan2  ایا میشه وزن‌های دیگه رو تست بگیرید، ببینید آنها هم مشکل دارند، و فونت ساحل هم همچنین. چون نباید این اتفاق بیوفته. کاملا غیر عادی هست و حتی منطقی . مگر یک حالت که شما برای وارد کردن ی مکسوره از کلید استفاده نکرده باشید و و اومده باشید کاراکتر ب داد لس+ همزه رو استفاده کرده باشید. که بعید میدونم تو وزیر همچین کدی تعریف شده باشه.

@rastikerdar کاراکتر beh dotless داری تو گلیف هات؟

**Comment by mihan2** [comment]
ببخشید من سرم شلوغ بود و دیر پاسخ دادم
همه وزن‌ها همین است 
در فونت ساحل چنین نیست ولی در فونت صمیم هست

معمولی تایپ کردم همزه و از ی بدون نقطه استفاده نکردم
 
اگرچه این فونت این گلیف را دارد
عجیب است که در فونت انگور که جدید است هم چنین است
و در فونت فرید این گونه نیست
فونت فربد با چه برنامه‌ای کار شده است؟

**Comment by rastikerdar** [comment]
متشکرم از اونجایی که اسم فونت ساحل رو آوردید فکر می کنم متوجه شدم که مشکل از کجاست چون توی ساحل یه سری تغییرات اعمال شده بود.

در نسخه بعدی فونت ها این مشکل رفع خواهد شد.

**Comment by mihan2** [comment]
ممنون.
وقت کردید بیشتر توضیح بدهید من خودم کنجکاو شدم
ضمن این که شما را برای این که با این برنامه فونت فورج کار می‌کنید تحسین می‌کنم
به نظرم کار با این برنامه به نسبت دیگر برنامه‌های طراحی فونت سخت است

**Comment by mihan2** [comment]
نسخه جدید هم آمد ولی این مشکل همچنان برقرار است البته خوشبختانه در نسخه جدید فونت **پرستو پرینت** که این مشکل حل شده است
صابر گرامی موفق و پیروز باشی

**Comment by rastikerdar** [comment]
@mihan2 ای داد من فکر می‌کردم مشکل از ارجاع‌ها باشه. پس واقعا مشکلی هست که من دلیلشو نمی‌دونم. اگر پیدا کردم شما رو در جریان می‌گذارم.
از لطفتون ممنونم.

**Comment by mihan2** [comment]
خب صابرجان با پرستو و ساحل مقایسه کن ببین در آنها چه کردی 
موفق و پیروز باشی

**Comment by zoghal** [comment]
@mihan2 میشه این مورد رو تست کنید؟ یک پی دی اف پرینتر نصب کنید و یک خروجی پی دی اف یا xps بگیرید و لینکش رو بدید تا بشه بیشتر بررسی کرد؟

**Comment by saeidka** [comment]
همانگونه که در اولین مطلب نوشتم وقتی از فایل خروجی پی دی اف بگیریم چه از ورد باشد چه از ایندیزاین مشکلی نیست و فقط هنگام چاپ با چاپگر لیزری این مشکل رخ می‌دهد 
و همانگونه که صابر نوشته است در فونت ساحل اینگونه نیست و با مقایسه این دو فونت مطمئناً او باید دریافته باشد که مشکل از کجاست

**Comment by zoghal** [comment]
از چه پرینتری استفاده می‌کنید؟ ایا درایورش آپدیت هست؟
پاسخ این سوالات رو برای پژوهشنامم نیاز دارم بخشی برای راهنمایی مشکلات فونت فارسی داره که مشکلات احتمالی رو بررسی می‌کنم و راه حل ها رو ارائه میدم.
ممنون میشم پاسخ بدید و من رو همیاری بدید :)
سپاس

**Comment by saeidka** [comment]
از
hp 2055d و hp 400 m401
بله آپدیت است
از فونت بهداد چه خبر؟

**Comment by rastikerdar** [comment]
با توجه به اینکه از اون تاریخ تا الان این فونت تغییرات زیادی داشته و جداولش اصلاح شده احتمالا این مشکل هم رفع شده باشه. اگر فکر میکنید یا مطمئنید چنین است ایشو رو ببندیم.

**Comment by saeidka** [comment]
نه مشکل همچنان هست و در چند کامپیوتر و چند پرینتر متصل که همه نرم‌افزارهای مشابهی دارند همین اتفاق می‌افتد. شاید چیزی نصب است که چنین می‌شود. البته همانگونه که چندبار گفتم و شما عنایت نکردید با ساحل این مشکل نیست. ممنون

**Comment by rastikerdar** [comment]
این مشکل در آخرین نسخه وزیر برطرف شد چون ریشه مشکل پیدا شد. در فونت‌های دیگر نیز این مشکل از نسخه‌های جدیدشون رفع خواهد شد. اگر باز هم ایرادی دیدید ممنون میشم اطلاع بدهید.
https://github.com/rastikerdar/vazir-font/releases

**Comment by saeidka** [comment]
برای من این مشکل حل شده بسیار ممنون. ولی کاش فاصله حروف را کم می‌کردید الان اندکی زیاد است.

**Comment by rastikerdar** [comment]
فاصله بین حروف که کمتر از این نمیشه کرد چون به هم می‌چسبند. اگر منظورتان فاصله بین کلمات است که در نسخه جدید اندکی کاهش یافته. راستش بیشتر از این احساس کردم به خوانایی لطمه می‌خوره. عرض ر هم کمتر شده که به دنبالش طول متن هم کمتر شده. اما خب کرنینگ ر و فاصله حذف شد به دلیل مشکل نمایش و به هم ریختگی در مرورگر کروم.

**Comment by saeidka** [comment]
ممنون از زحمات شما. فکر کنم خیلی خیلی کم باز هم بشه پهنای فاصله رو کم کرد. در نسخه بعدی ساحل هم اگر زحمت بکشید پهنای فاصله رو کم کنید که خیلی خوب است.

**Comment by Ariodaad** [comment]
> 
> 
> این مشکل در آخرین نسخه وزیر برطرف شد چون ریشه مشکل پیدا شد. در فونت‌های دیگر نیز این مشکل از نسخه‌های جدیدشون رفع خواهد شد. اگر باز هم ایرادی دیدید ممنون میشم اطلاع بدهید.
> https://github.com/rastikerdar/vazir-font/releases

متاسفانه مشکل همزه میانی پا برجاست. در فونت وزیر تست مشکل رفع شده بود. امیدوار بودم در نسخه جدید مشکلی نباشه اما متاسفانه مشکل در پرینت نمایان شد.

**Comment by rastikerdar** [comment]
احتمالا فونت جدید درست نصب نشده. همه فونت‌های وزیر رو پاک کنید و از ابتدا نصب کنید. راستش من اطمینان دارم که فونت درست شده چون دوباره تست کردم دیدم مشکل رفع شده و دقیقا این مشکل رو آقا سعید هم داشتند که فرمودند حل شده :confused:

**Comment by Ariodaad** [comment]
> 
> 
> احتمالا فونت جدید درست نصب نشده. همه فونت‌های وزیر رو پاک کنید و از ابتدا نصب کنید. راستش من اطمینان دارم که فونت درست شده چون دوباره تست کردم دیدم مشکل رفع شده و دقیقا این مشکل رو آقا سعید هم داشتند که فرمودند حل شده confused

تأیید میشه. بعد از حذف و نصب مجدد فونت وزیر نسخه 27 مشکل چاپ همزه رفع شد.
