### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by SMAH1** [rastikerdar/vazir-font#37]
آیا ممکن است یک علاوه بر
bower
بر روی
npm
هم منتشر شود؟

**Comment by morealaz** [comment]
<div dir="rtl">
تا اونجایی که من میدونم npm برای ماژول های Node.js استفاده میشه که همگی به زبان JavaScript هستند.
</div>

**Comment by bardiarastin** [comment]
+1

**Comment by rastikerdar** [comment]
امیدوارم با تغییر اخیر مشکل رفع شده باشه.
از شما ممنونم برای این ایشو.

**Comment by sajaddp** [comment]
سلام
در حال حاضر نسخه قابل دریافت از
npm
نسخه فونت دارای اعداد فارسی رو نداره وهمین نسخه موجود در گیت هاب هست.
ممنون میشم در صورت امکان ساختار رو به نحوی تغییر بدید که امکان استفاده از تمام حالت های فونت وجود داشته باشه.
چون برای مثال بنده معمولا برای قالب هایی که کار میکنم از حالت 
FD
استفاده می کنم و ناچارم هر بار نسخه رو دانلود کنم و در ساختار بندی قالب قرار بدم.
در حالیکه اگر در پکیج موجود باشه تنها با یک دستور اطمینان پیدا میکنم که نسخه آخر در پروژه اضافه شده.

**Comment by behnoodk** [comment]
مدیر محترم 
@rastikerdar 
باید با هر
release
نسخه های دیگر فونت رو هم در فولدر
dist
قرار بدهند تا قابل دسترس از طریق پکیج
npm
باشد. بنده هم علاقه دارم بدانم آیا دلیل خاصی وجود دارد که نسخه های دیگر فونت را فقط از طریق دریافت فایل
zip
امکان پذیر کرده اند؟

**Comment by rastikerdar** [comment]
سلام
حقیقتش یکی از دلایلش این بود که به طریقی موضوعِ فونت‌های غیر استاندارد، به همان بستهٔ اصلیِ دانلود محدود بشه و مبدل به رویکردی عام گونهٔ تحت وب نشه. واقعا نمی‌دونم راه درستش چیه.
از سوی دیگه هم این که شما تو زحمت بیفتین خوب نیست و هدف این ابزارها از جمله همین فونت اینه که کار آدم‌ها رو راحت کنه نه اینکه بخواد چیزی یا روشی رو به کاربر تحمیل کنه.

**Comment by behnoodk** [comment]
کنجکاوی من این بود که اگر قرار است فایلی ارائه شود، بهتر است همه جای پروژه یکسان باشد. 
وگرنه من خودم در چندین پروژه اخیرم از سه نسخه استنادارد و بولد و لایت وزیر استفاده کردم و هنوز نمی دانم نیاز به بقیه نسخه ها چیست؟ 
اعداد فارسی هم درست نشان داده می شوند با نسخه اصلی فونت وزیر. انتخاب 
Roboto
هم برای حروف لاتین انتخابی با سلیقه بوده. 
دلیل اینکه این نسخه های به قول شما غیر استاندارد ساخته شدند رو هم کنجکاوم بدانم.

**Comment by rastikerdar** [comment]
خب بیشتر به خاطر عدم استفاده از ارقام فارسی به جای لاتین و عربی در هنگام نمایش هست.
همه جا مثلا در پایگاه‌های داده (البته به درستی) با کد اسکی یعنی همون لاتینش ذخیره شده و برای نمایش به فارسی نیاز به تبدیل اون هست که این:
- یا غیر ممکنه
- یا به راحتی امکان پذیر نیست
- یا ازش غفلت میشه

برای حالت سوم مثلا در میان اسناد و متون فارسی، از ارقام لاتین (با کیبورد اشتباهی) استفاده میشه که خب در واقع اشتباه است.
در هر صورت فونت غیر استاندارد ظاهرا طرفداران زیادی داره.

**Comment by behnoodk** [comment]
ممنون از توضیحتون
