### ISSUE TITLE
نقد و بررسی

### ISSUE THREAD

**Issue by reza1615** [rastikerdar/vazir-font#4]
سلام
تعدادی از کاربران در پیوند زیر در مورد این قلم نظر دادند. در صورت امکان لطفا آنها را اصلاح نمائید.
https://fa.wikipedia.org/w/index.php?title=%D9%88%DB%8C%DA%A9%DB%8C%E2%80%8C%D9%BE%D8%AF%DB%8C%D8%A7:%D9%82%D9%87%D9%88%D9%87%E2%80%8C%D8%AE%D8%A7%D9%86%D9%87/%D9%81%D9%86%DB%8C&oldid=16082017#.D9.82.D9.84.D9.85_.D9.85.DB.8C.D8.B1.D8.B2.D8.A7

**Comment by rastikerdar** [comment]
سلام
تشکر می کنم از اینکه اشاره فرمودید.
خب زیبایی کاملا سلیقه ای هست. ممکن است دوستی فونت میرزا را زیبا بداند و دوستی دیگر خیر. برای مثال من انبوهی بازخورد محبت آمیز مبنی بر زیبا بودن فونت دریافت کرده ام حال آنکه ممکن است بسیاری هم نپسندند. مواردی که ایشان اشکال گرفته اند از جمله خوانایی اعراب، صحیح است اما در مورد زیبایی خود فونت کاری از دست من بر نمی آید. دیگر شکل فونت قابل تغییر نیست. مگر به طور کلی فونتی دیگر طراحی شود.
من دو تصویر یکی با فونت تاهوما و دیگری میرزا می گذارم. هر دو تحت یک شرایط بدون تغییر هیچ پارامتری در پنجره نمایش مرورگر کروم بر روی ویندوز ۷ تهیه شده اند.
تاهوما:
![with-tahoma-font](https://cloud.githubusercontent.com/assets/3116038/10618550/73d4b09e-777d-11e5-85c4-4329c909983f.png)

میرزا:
![with-mirza-font](https://cloud.githubusercontent.com/assets/3116038/10618554/7aa66eee-777d-11e5-989d-711108188d17.png)

لازم به ذکر است که شکل ممیز در نسخه جدید یعنی ۱.۶ باز طراحی شده است.

لینک مطلب آمده در تصویر:
https://fa.wikipedia.org/wiki/%D8%B2%DB%8C%D8%A8%D8%A7%DB%8C%DB%8C
باز هم ممنون

**Comment by rastikerdar** [comment]
@reza1615
در نسخه جدید یعنی ۱.۷ شکل ویرگول و نقطه ویرگول باز طراحی و همچنین اصلاحات کاملی بر روی اعراب انجام شد.

سپاسگزارم برای نقد و بررسی

**Comment by ho3ein-mola** [comment]
خیلی زیبا و ساده

**Comment by rastikerdar** [comment]
اگر چه این ایشو بسته شد اما خب چون چالش زیبایی در سری نخست فونت وزیر قابل رفع نبود از این رو سری دوم این فونت کلید خورد که تلاش گردید بسیاری از مشکلات سری نخست رفع گردد.

![screenshot from 2016-04-01 04-47-16](https://cloud.githubusercontent.com/assets/3116038/14194618/a13db83c-f7c5-11e5-9771-20526e2224e8.png)

برای مقایسه:
[vazir-font/test.html](http://rastikerdar.github.io/vazir-font/test.html)

عذرخواهی می کنم از ثبت مجدد نظر در این ایشو.

**Comment by parsedarweb** [comment]
‫خوبه هر بحثی در مورد وزیر که می‌شه، به گوش توسعه دهنده هاش هم برسه:

http://planet.sito.ir/%D8%AA%D8%B1%DA%A9%DB%8C%D8%A8-%D9%81%D9%88%D9%86%D8%AA-%D9%87%D8%A7/
