### ISSUE TITLE
پیشنهاد برای نسخه ۵

### ISSUE THREAD

**Issue by zoghal** [rastikerdar/vazir-font#41]
صابر  صابر خیلی پرفکت شده ایولا

چندتا پیشنهاد:
- ح‍ و ‍ح‍ خیلی سرشون خوابیده یکجوری هست به نظرم!
-  قوس نون کمی بزرگ هست 
- شرو ع زایده بالای ی خیلی کوتاه شده یکم بیشتر بکشش سمت راست بهتر میشه.

نقاط قوت: 
- ‍ه عالی شده، گذاشتمش تو نمونه ها
- ‍ع هم خیلی عالی شده، من خیلی باهاش حال کردم.

خسته نباشی

**Comment by rastikerdar** [comment]
تشکر می‌کنم برای ایشو.

شکل و شمایل وزیر رو کلا بردم به سمت وزیر نسخه یک. برای همین حـ اینجوری شده. در واقع برای هماهنگی و خوانایی. مزیتش به نظرم اینه که توی شکل فونت کاملا ادغام یا حل شده. اما خب یه جوری هست. ساختار شکنی کرده
:D
باز هم روش کار می کنم.

ن و ی هم حق با شماست. اصلاح میشه.
به نظرم مشکل ـع اینه که کلش یه کم زیادی بالاست.

باز هم ممنون.

**Comment by rastikerdar** [comment]
توی نسخه جدید هم قوس نون اصلاح شد. هم شروع زایده ی. 
همچنین شکل حـ کمی بهبود پیدا کرد. 
ارتفاع ـع نیز اندکی کمتر شد. 
شکل ـه بنا به درخواست دوستان به حالت سابق بازگشت.

[rastikerdar.github.io/vazir-font/test2.html](http://rastikerdar.github.io/vazir-font/test2.html)
با تشکر از صالح عزیز

**Comment by zoghal** [comment]
وای وای صابر چرا اینکارو کردی آخه، خداییش عالی شده بود اون نسخه :( 
میشه لطف کنی یک دمو از این نسخه و  نسخه قبلی کنار هم بزاری تا بشه بهتر مقایسه کرد؟

**Comment by rastikerdar** [comment]
این شکل فعلی هم خواناست. دیگه کلا بیخیال شکل قبلی شدم. سپردمش به بوته فراموشی. 
:)
