### ISSUE TITLE
پیشنهادهایی درباره فونت وزیر

### ISSUE THREAD

**Issue by Mohammad-777** [rastikerdar/vazir-font#44]
<html>
<head>

</head>
<body > 

<p align="right" >
با سلام

<p align="right" >
آقا صابر عزیز چند پیشنهاد درباره فونت وزیر داشتم که نمی دونم قابل عملی شدن است یا نه چون من از اصول خط فارسی و خوشنویسی آگاهی ندارم و بر اساس سلیقه خودم نظر میدم

<p align="right" >
الف) چرا در تمام فونت های معروف، نقطه مثلا حرف " تـ " در وسط نیست چون ما همیشه با دست که یک چیزی رو می نویسیم اون رو در وسط قرار میدیم. شما عکس زیر رو نگاه کن

https://i.imgsafe.org/f977d86450.jpg
<p align="right">
اولی با فونت وزیر نوشته شده که نقطه ها در راست ترین قسمت قرار داره اما دومی همون فونت وزیر هستش که من با نرم افزار  Fontcreatorنقطه های حرف " تـ " و " نـ " رو در وسط قرار دادم (البته نه به صورت دقیق فقط برای توضیح دادن به شما) به نظر من کلمه "تنها" دومی زیباتر و به دست نوشته های
ما نزدیک تر است.
<p align="right">
مشکلی هم که وجود داره این هست که وقتی نقطه ها رو به وسط آوردم به علامت سرکش حرف "ک" می چسبه که در صورتی که خواستی نظر من رو پیاده سازی کنی باید یه فکری به حال حرف "ک" و یا احیانا حروف دیگه ای که این مشکل رو
ممکنه پیدا کنن بکنی
<p align="right">
حروفی مثل " بـ " و ... هم به نظرم اگه نقطشون وسط باشه بهتره همچنانکه شما نقطه حرف " ن " رو در وسط قرار دادی
<p align="right">
ب ) من " لا" کلمه " تلاش" رو در فونت شبنم زیباتر می بینم که به دست نوشته ما نزدیکتره البته حرف الف اون کامل نچسبیده که من کامل چسبیده اون رو می پسندم

https://i.imgsafe.org/f980341832.jpg
<p align="right">
پ) شما به عکس زیر دقت کن

https://i.imgsafe.org/f983e56978.jpg
<p align="right">
هیچ فونتی پیدا نکردم که تا الان این ه دو چشم رو زیبا طراحی کرده باشه بعضی ها همین شکلی هستن ولی چسبیده هستن و شما فاصله قرار دادی و بعضی ها هم مثل فونت  B Yekanمثل دو تا چشم طراحی کردن که جالب نیست اگه روی این ه دو چشم  کار کنی و زیباترش کنی به نظرم بهتر هست
<p align="right">
ت ) به عکس زیر نگاه کن

https://i.imgsafe.org/f98c0057f4.jpg
<p align="right">
حرف "ر" در کلمه "سمر"  با دو حرف قبلی تناسب لازم رو نداره و کوچکتر به نظر می رسه
<p align="right">
برای حل این مشکل دو راه داری یا حرف "ر" رو بزرگتر کنی یا فاصله دندانه ها در حرف "س" و دیگر فاصله ها رو در حرف های "سـ" و "مـ" کمتر کنی که به تناسب روی تمام حرف ها باید این رو اعمال کنی که ممکنه فونت شما اصلا عوض بشه بنابراین شما خودت بهتر می دونی که باید چیکار کنی
<p align="right">
ث) همین الان شما به شکل  عدد  5در فونت وزیر دقت کن به نظرم اصلا زیبا نیست زیباترین عدد  5در فونت B yekan هست

https://i.imgsafe.org/f9941eb7f6.jpg
<p align="right">
عدد 1 کج تایپ می شه حالا نمی دونم از اصول خط فارسیه یا سلیقه طراحه و به همین خاطر عدد 4 کجه و مثلا در عدد 97 ، عدد 7 بسیار زیباست و راسته اما 9 کجه به همین خاطر عدد 97 زیبا نیست
<p align="right">
ج) به عکس زیر توجه کن

https://i.imgsafe.org/f9a72caf86.jpg
<p align="right">
به نظر من ه دو چشم باید چسبیده باشه تا زیباتر به نظر برسه و باز هم مشکل عدم تناسب حرف ها دیده می شه که کلمه "همرا" کمی بزرگتر از "ه" نشون داده می شه
این نکته رو یادآوری کنم که یکی از زیبایی های فونت شما همین فاصله در حروف هست که برای چشم زیباتر جلوه می کنه حالا من نمی دونم که اگه شما بخوای این فاصله ها رو برای تناسب کم کنی آیا از زیبایی های این فونت کم می شه یا نه و یا اگه "ه" رو بزرگتر کنی تو ذوق می زنه یا نه
<p align="right">
چ) به عکس زیر توجه کن

https://i.imgsafe.org/f9acba6a9f.jpg
<p align="right">
اول اینکه حرف "ب" نمی دونم چرا اون تناسب رو نداره و طرف چپش کمی بالاتر قرار گرفته ولی اگه به صورت تنها یعنی به این صورت "ب" بنویسیم تناسب داره یعنی حرف "ب" در عکس بالا زیبا نیست.
<p align="right">
یکی دیگه از نقاط ضعف فونت "وزیر" به اعتقاد من حرف های "حـ " ، " جـ " ، " چـ " و " خـ " است که جدا از نقطشون زیبا نیستن و این در تمام فونت های خوب فارسی وجود داره که اگه شما بتونی یه "حـ " زیبا طراحی کنی خیلی خوب می شه
<p align="right">
ح) به عکس زیر توجه کن

https://i.imgsafe.org/f9b0fed487.jpg
<p align="right">
در تما فونت های مطرح این "ی" وقتی متصل می شه به این صورت در میاد که زیبا نیست مثلا الان من این حرف رو به صورت تنها می نویسم با همین فونت وزیر شما می بینی که هم زیباست و هم در موقع چسبیدن باید مثل عکس زیر باشه

https://i.imgsafe.org/f9b497791f.jpg
<p align="right">
خ) به عکس زیر توجه کن

https://i.imgsafe.org/f9b75ee5fa.jpg
<p align="right">
حرف " حـ " کمی بزرگتره و با کل کلمه متناسب نیست
<p align="right">
د) به عکس زیر توجه کن

https://i.imgsafe.org/f9bc154624.jpg
<p align="right">
حرف "ژ" به غیر از نقطه هاش کمی متمایل شده به سمت شکل حرف " تـ " به نظرم نباید انقدر گرد باشه که به نقطه های "یا" نزدیک بشه کلا حرف "ر" هم همین مشکل رو داره یعنی باید کمی از گردی اون کاسته بشه
<p align="right">
ذ) به عکس زیر توجه کن

https://i.imgsafe.org/f9c11231d5.jpg
<p align="right">
حرف "د" در فونت شما بهترین حرف "د" است که تا حالا دیدم ولی شما تست کن ببین اگه خیلی خیلی کم اگه مایل به پایین باشه چطوری می شه اگه بهتر نشد که بزار همونطوری باشه شاید چشم من مشکل داشته باشه ولی باز هم من فکر می کنم
حروف تناسب ندارن یعنی حرف "و" کمی بزرگتر از حروف دیگر است که باعث می شه حرف "د" اول رو بزرگتر از حرف"د" آخر ببینیم در حالی که هر دو کاملا هم اندازه هستن
<p align="right">
ر) به عکس زیر توجه کن

https://i.imgsafe.org/f9c5922ea5.jpg
<p align="right">
به نظر من اگه دندونه اول در حرف "شـ" که شما کمی بزرگتر نسبت به دو دندونه دیگه گرفتی یکمی کوچیکتر بشه بهتره ولی همچنان باید از دو دندونه دیگه کمی بزرگتر باشه همچنین دندونه های حرف "شـ" در اول کلمه متناسب هستن
هم از نظر فاصله و هم از نظر شکل اما دندونه سوم در حرف "ش" با دندونه های اول و دوم هم راستا و به یک شکل نیست
<p align="right">
ز) به عکس زیر توجه کن

https://i.imgsafe.org/f9ca080128.jpg
<p align="right">
کلا حرف "کـ" خوب طراحی نشده انگار حرف "د" رو یه سرکش بهش اضافه کرده باشن به نظر من کمی باید سرکش حرف "کـ" درازتر باشه و اون قسمت
شبیه "د" باید متناسب و زیباتر باشه در "گـ" هم این مشکل وجود داره
<p align="right">
ژ) به عکس زیر توجه کن

https://i.imgsafe.org/f9cf1624a9.jpg
<p align="right">
"ف" هم به نظر من آخرش زیبا نیست کمی شبیه قایق شده باید کمی صاف تر باشه چون اصولا فونت شما صاف طراحی شده

https://i.imgsafe.org/f9d2e76f8c.jpg
<p align="right">
در عکس بالا حرف "د" کمی بلندتر از حرف "یـ" است
<p align="right">
دو نکته :
<p align="right" >
الف) به نظر من چون شما یک طراح هستی و به تدریج فونت های بیشتری درست می کنی بهتره یک نام واحد قبل از فونت های خودت قرار بدی چون وقتی مثلا در ورد داریم کار می کنیم یه راست بریم سر فونت های شما و اونطوری فونت های شما همه پشت سرهم در یک مکان قرار می گیره و هم برای ما کار راحت تر می شه و هم فونت های شما متمایز از فونت های دیگران می شه
<p align="right" >
 نمونش هم فونت های B-Nazanin و B-Yekan که همگی پشت سر هم هستن و البته پیدا کردن این نام اول سخته

<p align="right">
مثلا  saber-samim ، saber-vazirکه من با خودم می گم این پروژه رو می خوام از فونت های آقاصابر استفاده کنم و می رم saberرو پیدا می کنم و بعد از اون فونت دلخواهم رو انتخاب می کنم که شما به جای  saberهر کلمه ای رو می تونی استفاده کن

<p align="right">
در ضمن از روی فونت شما و 11 فونت درجه یک فارسی هم یک صفحه پرینت گرفتم و اون رو به اعضای خانوادم نشون دادم گفتم زیباترین نوشته مربوط به
کدوم نوشته است که همه صفحه ای رو که با فونت وزیر تایپ شده بود رو انتخاب کردن ( اسم فونت ها رو هم بالاش ننوشته بودم تا کسی ندونه اسم فونت چیه)
<p align="right">
برای شما و خانواده محترمت آرزوی سلامتی می کنم و امیدوارم که هم در زندگی و هم در این راه موفق باشی
<p align="right">
دوستدار شما
<p align="right">
محمد

</body>
</html>

**Comment by zoghal** [comment]
@Mohammad-777  توضیحاتتون رو خوندم، لذت بردم از اینکه پیدا میشن افرادی که اینقدر به حروف با دقت نگاه می‌کنند، گفتم تشکر کنم ازتون. جدا از توضیحاتتون لذت بردم.

**Comment by rastikerdar** [comment]
ممنونم محمد آقا
چند مورد رو که در سری ۵ و ۶ اعمال شد. ممکنه دقیقا اون چیزی که فرمودید نشده باشه اما سعی شد که نزدیک بشه.
مثلا
![screenshot from 2016-12-13 16-32-59](https://cloud.githubusercontent.com/assets/3116038/21141356/e5e1e520-c151-11e6-9626-594d0f3c32c8.png)
البته وزیر به روند بهبود ادامه میده.

**Comment by Mohammad-777** [comment]
<p align="right">
از آقا صالح تشکر می کنم به خاطر لطفی که به بنده داشتن و همچنین از شما آقا صابر که برای نظرات مبتدیانه من ارزش قائل شدین 
<p align="right">
تا اینجا فونت وزیر، بهترین فونت فارسیه و به نظر من باید از این به بعد، فونت های یکان، تاهوما و ... برن کنار و فونت کامل شده وزیر جای اونا رو بگیره
اگه این فونت تکمیل بشه سایتی مثل ویکی پدیا باید از این فونت استفاده کنه و همچنین همه سایت های دیگه مثل سایت های خبری و ورزشی
<p align="right">
همچنین به نظر من باید از طرف فرهنگستان زبان و ادب فارسی یک جایزه ای به آقا صابر تعلق بگیره برای این کار ارزنده ای که برای زبان پارسی انجام داده و امیدوارم کسانی  هم که توانایی مالی خوبی دارن حتما یک مبلغی رو برای زحمتی که آقاصابر کشیده اختصاص بدن  
<p align="right">
من اگه در زمینه درسی پیشرفت کنم خودم رو مدیون شما می دونم آقا صابر و فکر می کنم در آینده، فونت شما باعث پیشرفت خیلی ها در زمینه درسی بشه و خوب در کل باعث پیشرفت جامعه می شه
<p align="right">
همچنین فونت وزیر باعث می شه که چشم کمتر اذیت بشه و به نوعی همه استفاده کننده های این فونت ، کمتر آسیب دیدن چشمشون رو مدیون این فونت خواهند بود
<p align="right">
آقا صابر هنرمند، در یک کلام خیلی دوسِت دارم

**Comment by rastikerdar** [comment]
شما خیلی لطف دارید. البته از وزیر بهتر هم زیاد هست.
اگر به نظرتان وزیر خوب شده از خوبی شما و همه دوستان بوده. یک کار دلی که در واقع به فرد خاصی تعلق ندارد.
این فونت هم فقط یک وسیله یا ابزار برای نمایش متن هست و شاید بی‌تاثیر. مولفه اصلی و حقیقی، اراده و همت شما برای تحصیل موفقیت می‌باشد.

امیدوارم این موهبت یعنی روحیه شاداب و محبت‌آمیزتان رو در همه مراحل زندگی حفظ کنید.
پیروز و سربلند باشید.

**Comment by rastikerdar** [comment]
محمد آقا عزیز فونت وزیر از اون نسخه تا الان تغییرات زیادی داشته. اگر فکر می‌کنید به آنچه که می‌پسندین نزدیک شده ایشو رو ببندیم در غیر اینصورت باز بمونه
![sample](https://user-images.githubusercontent.com/3116038/80286849-126e5280-8743-11ea-88f2-5fa8fa5ea413.png)
