### ISSUE TITLE
نمایش نقطه های اضافی در برنامه اور نوت

### ISSUE THREAD

**Issue by ghost** [rastikerdar/vazir-font#47]
من از فونت وزیر به عنوان فونت پیشفرض ویندوز استفاده میکنم، خیلی زیبا شده ویندوز با این فونت! فقط یک مشکلی وجود داره نمیدونم گزارش کردن یا نه! و اون اینه که در برنامه اور نوت در عنوان نوت ها نقطه های اضافی در فونت دیده میشه. که در کلمات انگلیسی تعداد این نقطه ها به مراتب بیشتر از فارسی هست. 
با تشکر
![english-vazir](https://cloud.githubusercontent.com/assets/22021877/21580602/7a2ea1ee-d018-11e6-9ac7-4ce831f74908.png)
![persian-vazir](https://cloud.githubusercontent.com/assets/22021877/21580603/827696c2-d018-11e6-9582-cfa11304b71e.png)

**Comment by zoghal** [comment]
@yonessafari درود بر شما، دقیقا میشه بفرمایید منظورتون از نقطه اضافه چی هست؟
 من هر چی مقایسه کردم نتونستم متوجه بشم داستان دقیقا چیه! کنجکاوی خفم کرد گفتم فضولی کنم بپرسم :)
با پوزش از صابر عزیز

**Comment by yonessafari** [comment]
درود بر استاد طوفان
انگار کاراکترها رو با یه میخ چسبوندی به صفحه. البته در ام کوچک با دو میخ :-)
یه مشکل دیگه هم الان دیدم و اونم اینه که دی بزرگ بالاش دوخطه هست یعنی بالاتنش بولد هست و  پایین تنش معمولی.
تو تصویر، پایین نقطه های قرمز را دقت کنید میبینید مشکل رو
![english-vazir-new](https://cloud.githubusercontent.com/assets/22021877/21580728/d0b17d7a-d022-11e6-8d80-d4e5d51529b2.png)

**Comment by zoghal** [comment]
@yonessafari :)) استاد طوفان واسه شبکه‌های اجتماعی هست. اینجا صالح خالی هستم
بگذریم. مشکلی که اشاره کردید مربوط به هینتینگ و سیستم مزخرف تکست رندر ویندوز هست.
فکر می‌کنم روی ویندوز ۷ یا ۸ این تصاویر گرفته شده. چون این مشکل تقریبا در ویندوز ۱۰ خیلی بهبود پیدا کرده

**Comment by yonessafari** [comment]
دقیقا متوجه شدم مشکل کجاست
تو سایزهای  12 و 20 و 22 پیکسل.
در بقیه سایزها مشکلی وجود نداشت
فقط تو این سایزها کاراکترهایی که بالاتنشون نیاز به انحنا داره یه نقطه اضافی میخورن
مثل حرف سی ، پی ، او و .....
تو تصویر زیر کاملا مشخصه. تو سایز 22 که کامل مشخصه.
![12px-problem](https://cloud.githubusercontent.com/assets/22021877/21580859/860f1d10-d02a-11e6-8eea-17f66d90dc56.png)

**Comment by yonessafari** [comment]
@zoghal اگر مربوط به مشکل تکست رندر ویندوز هست چرا پس فونتی مثل
segoe ui
این مشکل رو نداره؟

**Comment by rastikerdar** [comment]
تشکر می کنم برای گزارش این ایراد.
درسته حق با شماست. همانطور که آقا صالح هم فرمودند مربوط به هینتینگ هست. دلیلش این بود که من درجه هینتینگ رو روی حداقل نگه داشته بودم. می خواستم حجم فایل زیاد نشود. اما خب اگر امکانش هست این فایل پیوست حاوی فونت رو امتحان کنید اگر مشکل حل شده باشه که نسخه جدید رو منتشر کنم.
[Vazir.ttf.zip](https://github.com/rastikerdar/vazir-font/files/680112/Vazir.ttf.zip)

**Comment by yonessafari** [comment]
سلام
نه متاسفانه حل نشد
یا اگر وسواس کمی به خرج بدیم تنها در سایز 12 مشکل حل شد، البته با تغییر شکل ظاهری
![vazir-new-bug](https://cloud.githubusercontent.com/assets/22021877/21582437/89474f2e-d06c-11e6-9b73-5e7fc6236e7c.png)

**Comment by yonessafari** [comment]
@zoghal @rastikerdar بله حق با شماست و این مشکل فقط در ویندوز هست
من در اوبنتو تست کردم فونت ها بدون هیچ ایرادی در همه سایزها مثل هم هستن
ولی در ویندوز در سایزهای مختلف شکل و شمایل مختلفی البته جزپی دیده میشه
با تشکر

**Comment by rastikerdar** [comment]
سلام. عجیبه که برای من اصلاح شد اما برای شما خیر. به هر حال اگر راه حلی برایش پیدا کردم شما رو در جریان می‌گذارم.

**Comment by yonessafari** [comment]
ویندوز شما هم سون هست؟
چون من از ویندوز سون استفاده میکنم

**Comment by rastikerdar** [comment]
بلی سون هست.

**Comment by zoghal** [comment]
> اگر مربوط به مشکل تکست رندر ویندوز هست چرا پس فونتی مثل
segoe ui
این مشکل رو نداره؟

این فونت فونت دیفالت ویندوز حساب میشه و جایگزین تاهوما محسوب میشه، مربوط به خود ماکروسافت هست. اگر به حجم فونت نگاه کنید می‌بینید حجم بسیار بالایی داره.
از طرفی این فونت کمی خشک هست و دور کمی توش دیده میشه. مشکلی که بهش بر خوردید بیشر روی دور‌ها دیده میشه.
این ویدیو رو ببینید([اینجا](https://streamable.com/f5pys)) این فونت آرش من هست که ۸ ماهی هست دارم برای همین user interface ویندوز اوکی میکنم. متاسفانه ویندوز برای نمایش ۷ حالت داره که هر کدام یک مزیت و عیب برای خودش داره. 

فعلا نتیجه خوب بوده اما خیلی کار می‌بره 
اینم یک ویدیو از پشت صحنه هینتینگ([اینجا](https://streamable.com/6lvt0))


> @zoghal @rastikerdar بله حق با شماست و این مشکل فقط در ویندوز هست
من در اوبنتو تست کردم فونت ها بدون هیچ ایرادی در همه سایزها مثل هم هستن
ولی در ویندوز در سایزهای مختلف شکل و شمایل مختلفی البته جزپی دیده میشه


فکر کنم در سایز ۱۵-۱۶-۱۷ این تغییر شکل دیده میشه که مربوط به هینیگ ماشینی هست.(دردسر‌های هینتینگ یکیش همین هست.)


> بلی سون هست.

بیخیال ویندوز ۷ بشید سر این موضوع خیلی سنگینترین. ویندوز ۷ مشکل زیاد داره.
اما یک پیشنهاد اگر روی ویندوز ۷ دایرکت ایکس آخرین نسخه نصب نیست، نصب کنید کمی وضعیتتون بهتر میشه.

**Comment by rastikerdar** [comment]
ویندوز ۷ رو روی ماشین مجازی برای تست قلم نصب کردم. توی ویندوز بر خلاف گنولینوکس و مک ماجرا زیاده. به تدریج همه چی درست میشه.

**Comment by Masishta** [comment]
درود
نقطه اضافی روی حرف ن هم زیاد دیده می‌شه
وزیر نسخه ۷.۱.۰
سیستم عامل ویندوز ۱۰
برنامه پخش ام پی وی
![01](https://cloud.githubusercontent.com/assets/16443319/23482913/0611c546-fee6-11e6-8ba0-76887cac96a2.jpg)
![02](https://cloud.githubusercontent.com/assets/16443319/23482976/40171426-fee6-11e6-820d-9b937fbca595.jpg)

هر کجا نون پایانی چسبان باشه اون نقطه اضافی دیده می‌شه

![mpv-shot0005](https://cloud.githubusercontent.com/assets/16443319/23483119/d7e2da60-fee6-11e6-9947-1caffc721ac3.png)

**Comment by rastikerdar** [comment]
توی نسخه جدید یعنی ۸ رفع شد. خیلی ممنونم برای گزارش این ایراد مهم. متاسفانه از چشمم دور مانده بود. باز هم اگر موردی بود بفرمایید.

**Comment by Masishta** [comment]
سپاس بابت سرعت عمل!

**Comment by rastikerdar** [comment]
@ghost
در نسخه ۲۷.۰.۳ تغییراتی برای نمایش بهتر در محیط ویندوز اعمال شد. امیدوارم بهتر شده باشه.
https://github.com/rastikerdar/vazir-font/releases

**Comment by rastikerdar** [comment]
ظاهرا کاربری که این ایشو رو باز کرده بود حسابش رو حذف کرده. پس ایشو رو می‌بندم.
