### ISSUE TITLE
توضیحاتی درباره‌ی انتشار

### ISSUE THREAD

**Issue by Javid-Izadfar** [rastikerdar/vazir-font#49]
صابرجان خسته نباشی
امروز دیدم که نسخه‌ی ۷ از وزیر رو منتشر کردی. تبریک میگم!

اما یه گله‌ای دارم ازت. با هر انتشاری که وزیر داشت، هیچکدوم از ما نمیدونیم که چه چیزی تغییر کرده! شاید حتی بعد از نصب فونت و تستش، خیلیا متوجه‌ی تغییرات نشن.

میدونم که کار سخت و حوصله سربری هست ولی ازت خواهش میکنم با هر انتشار توضیحاتی هم درباره‌ی چیزهایی که تغییر کرده (با عکس یا متن - فرقی نداره) بهمون بدی تا بدونیم به استقبال چه چیزی میریم.

باز هم خسته نباشی

**Comment by rastikerdar** [comment]
متشکرم آقا جاوید
راستش تردید دارم این نسخه جدید ۷ بهتر شده باشه. ۶ خوب بود اما احساس کردم به نسبت تاهوما اندازه اش کوچک تره که توی ۷ بزرگ تر شد اما نمی دونم این توی خوانایی و زیبایی و کشیدگی و ... تاثیر منفی گذاشته یا نه.

در مورد تغییرات راستش مختصری توی این فایل با هر انتشار نوشته می‌شه مگر اینکه شما منظورتون اطلاعات مفصل‌تری باشه.
[https://github.com/rastikerdar/vazir-font/blob/master/CHANGELOG.md](https://github.com/rastikerdar/vazir-font/blob/master/CHANGELOG.md)

فکر می‌کنم بهترین راه برای مشاهده تغییرات، رجوع به این صفحه مقایسه بین نسخه‌های محتلف وزیر هست:
[http://rastikerdar.github.io/vazir-font/compare.html](http://rastikerdar.github.io/vazir-font/compare.html)

سلامت باشید.

**Comment by zoghal** [comment]
@rastikerdar تبریک مجدد بر صابر عزیز نسخه ۷ خیلی عالی شده خدا قوت
پیشنهاد میکنم در صفحه مقایسه از اعداد و علايم و همچنین لغات انگلیسی هم استفاده کنید تا بهتره هماهنگی هایی که روی فونت وزیر اعمال می‌کنید خود نمایی نمایند :)
