### ISSUE TITLE
Please rename

### ISSUE THREAD

**Issue by davelab6** [rastikerdar/vazir-font#5]
As you can see at https://github.com/Tarobish/Mirza/commits/master?page=3 another Persian OFL font project was started 7 days before this one, using the same name. 

Therefore, please rename this project (at the bottom of https://github.com/rastikerdar/mirza-font/settings) and update the fonts :)

**Comment by rastikerdar** [comment]
I hadn't seen that project! Although that font is Arabic and this font is Persian but well let me think about a new name. Thank you for mentioning.

**Comment by davelab6** [comment]
No worries :)

The designer of Jomhuria is persian, and it should support both Arabic and
Persian languages..., Do you agree that the script is "Arabic" for both
projects?

**Comment by rastikerdar** [comment]
No problem! You're completely right. I'm searching for a new name :) Thanks

**Comment by rastikerdar** [comment]
close? :)
