### ISSUE TITLE
وزیر مونو

### ISSUE THREAD

**Issue by mmdmine** [rastikerdar/vazir-font#53]
سلام؛ نسخه مونو برای ویرایشگر کد ها و کونسول رو نتونستم پیدا کنم.
دارم روی یه برنامه فارسی کار میکنم فونت پیشفرضش چشممو اذیت میکنه. اگه فونت مونو مناسب سراغ دارید بگید. به نظرم یکی از همین فونت های مجموعه راستی کردار مونو داشت ؛ دیدم.

**Comment by sajaddp** [comment]
سلام
احتمالا منظور شما فونت وزیرکد هست:
https://github.com/rastikerdar/vazir-code-font
