### ISSUE TITLE
تفاوت حروف انگلیسی

### ISSUE THREAD

**Issue by senior-js** [rastikerdar/vazir-font#54]
سلام
تفاوت حروف انگلیسی نسخه اخر فونت وزیر با فونت صمیم در چیست؟
برای یک سایت انگلیسی می خواهم از این فونت استفاده کنم ( با توجه به اینکه گفتید از roboto برای حروف انگلیسی استفاده شده )
تا در نسخه فارسی و عربی سایت زیبایی و یک دستی مناسبی برقرار بشه.
ولی مقایسه که کردم در حروف انگلیسی این دو فونت کمی تفاوت دارند.
ممنون میشم بفرمایید به نظر شما برای یک سایت 3 زبانه بین فونت وزیر و صمیم کدام مناسب تر هست.

تشکر بابت قلم های زیبای شما.

**Comment by rastikerdar** [comment]
سلام
برای فونت صمیم از قلم اوپن سنس و برای وزیر از روبوتو استفاده شده. فونت ساحل هم با اوپن سنس ترکیپ شده.
اینکه کدام مناسب‌تر است رو راستش نمی‌دانم. شاید بهتر باشه خودتون امتحان کنید.
