### ISSUE TITLE
پیشنهاد: ارائه تغییرات هر نسخه جدید در توضیحات نسخه

### ISSUE THREAD

**Issue by behnoodk** [rastikerdar/vazir-font#55]
با ارائه هر نسخه فایل 
CHANGELOG.md
رو زحمت می کشید و اپدیت می کنید که تغییرات هر نسخه مشخص باشد. پیشنهاد می دهم هنگام ساختن یک ریلیس جدید در گیت هاب این تغییرات رو در 
release description
هم وارد کنید. که هنگام نمایش به راحتی تغییرات اعمال شده در آن نسخه مشخص باشد و نیازی به مراجعه به فایل
CHANGELOG.md
نباشد. این یک روند استاندارد هست تا اونجایی که من اطلاع دارم.
مرسی

**Comment by rastikerdar** [comment]
تشکر می‌کنم برای این ایشو. درست می‌فرمایید. پیرو نظر شما و ایشو زیر از نسخه بعدی نکته‌ای که فرمودید رعایت خواهد شد.
#49
