### ISSUE TITLE
نمایش اعداد به صورت انگلیسی

### ISSUE THREAD

**Issue by monala** [rastikerdar/vazir-font#57]
ایا فونت وزیر اعد را هم به صورت فارسی نمایش می دهد؟ اعدادی مثل تاریخ را لاتین نمایش میدهد.
![image](https://cloud.githubusercontent.com/assets/16857813/25081557/48754cac-2360-11e7-98e2-f63d6ffa3081.png)

**Comment by rastikerdar** [comment]
احتمالا شما از فونت استانداردی که در پوشه اصلی قرار دارد استفاده می‌کنید. برای اجبار نمایش تمامی ارقام حتی لاتین، عربی به صورت فارسی از فونت موجود در پوشه ارقام فارسی استفاده بفرمایید.
Farsi-Digits/

**Comment by Masishta** [comment]
درستش اینه کسی که اون نوشته رو تایپ می‌کنه از کیبرد استاندارد استفاده کنه که در این کیبرد عددهای فارسی موجوده ولی متاسفانه بسیاری از کیبرد نا استاندارد استفاده می‌کنند که شماره‌های انگلیسی داره
