### ISSUE TITLE
اضافه کردن تصویری از متن نوشته شده با فونت وزیر

### ISSUE THREAD

**Issue by mkermani144** [rastikerdar/vazir-font#59]
<p dir="rtl">پیشنهاد می‌شه تصویری از یک متن نمونه، مانند متنی که در</p>
http://rastikerdar.github.io/compare-fonts/
<p dir="rtl">هست، به فایل README.md اضافه بشه تا کاربران بتونند فونت رو بدون این‌که نیاز باشه به صفحه‌ی مربوط به فونت مراجعه کنند، مشاهده کنند.</p>

**Comment by rastikerdar** [comment]
اتفاقا توی صفحه فونت صمیم هم آلن عزیز همچین تصویری رو اضافه کرد. اگر تصویری در نظرتونه می‌تونید به صفحه اضافه بفرمایید.
