### ISSUE TITLE
ضخیم شدن حروف انگلیسی در آپدیت 10

### ISSUE THREAD

**Issue by peymanzizi** [rastikerdar/vazir-font#63]
سلام
در آخرین نسخه (10) متاسفانه حروف انگلیسی نسبت به قبل ضخیم شدند که باعث بد شدن جلوه در سایت های چند زبانه میشه.
این ضخیم شدن حتی برای حالت light هم مشهود هست.
تغییر خاصی در فونت انگلیسی اعمال کردید؟

**Comment by rastikerdar** [comment]
سلام. متشکرم برای ایشو
توی نسخه ۱۰.۰.۰ متاسفانه حالت هینتینگ بر روی فونت اعمال نشده بود که امروز توی نسخه ۱۰.۰.۱ اصلاح شد. اگر این مشکل رو با نسخه آخری هم دارید ممنون میشم تصویری از اون رو به نمایش بگذارید تا بهتر متوجه اشکال بشم.

توی این صفحه نسخه های مختلف وزیر قابل آزمایش هست. اگر اختلافی که مد نظرتونه رو مشاهده فرمودید ممنون میشم شماره نسخه آن رو اطلاع دهید.
 [rastikerdar.github.io/vazir-font/compare.html](https://rastikerdar.github.io/vazir-font/compare.html)

**Comment by peymanzizi** [comment]
![1](https://cloud.githubusercontent.com/assets/3840173/26783769/374c1994-4a0f-11e7-951c-9275416e9ebc.png)
لطفا نگاه کنید حروف را با هم مقایسه کنید منظورم را از ضخیم بودن فونت ها بهتر میفهمید
سپاس فراوان

**Comment by rastikerdar** [comment]
آهان متوجه شدم. این موضوع تنها برای حالت نازک قلم پیش آمده. دلیلش اینست که در نسخه های قبل از سری ۱۰ بین حالت نازک لاتین و نازک فارسی اختلاف عمده ای وجود داشت.

![screenshot from 2017-06-05 19-02-37](https://cloud.githubusercontent.com/assets/3116038/26788219/bf4198c6-4a21-11e7-91d6-0efa0f687382.png)

 یا باید فارسی نازک تر میشد یا لاتین ضخیم تر که حالت دوم انتخاب شد یعنی ضخیم تر شدن لاتین.

![screenshot from 2017-06-05 19-05-26](https://cloud.githubusercontent.com/assets/3116038/26788300/07e81f32-4a22-11e7-9ba9-72234033b057.png)

برای حالتی که مد نظر شماست باید یک نسخه بسیار باریک فارسی نیز اضافه شود. یعنی بدین صورت:

![screenshot from 2017-06-05 19-07-35](https://cloud.githubusercontent.com/assets/3116038/26788442/6888a5e6-4a22-11e7-981f-d5582fbb415d.png)

به نظر شما اضافه شود؟

**Comment by peymanzizi** [comment]
با عرض سلام و خسته نباشید دوباره
بله به نظر من که اضافه شود
بسیار هم عالی میشود

**Comment by rastikerdar** [comment]
نسخه باریک در سری جدید یعنی ۱۱ اضافه شد. با تشکر از پیگیری شما.
