### ISSUE TITLE
woff VS woff2

### ISSUE THREAD

**Issue by onrea** [rastikerdar/vazir-font#64]
چه فرقی دارن؟

‫برای پروژه‌هام از woff استفاده کردم. ‫به woff2 تغییرشون بدم؟!

**Comment by Javid-Izadfar** [comment]
<p dir="rtl">سلام</p>
<p dir="rtl">تفاوت خاصی توی فرمت هدینگشون وجود نداره ولی به صورت میانگین ۳۰٪ و نهایتا تا ۵۰٪، woff2 از woff حجم کمتری رو موقع کامپرس شدن میگیره.</p>
<p dir="rtl">فرق قابل توجه دیگه ساپورتشونه که IE11 و سافاری مک‌او‌اس‌های قدیمی woff2 رو نمیخونن.</p>
<p dir="rtl">توی لینک زیر میتونین بیشتر در موردش مطالعه کنی:</p>
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a

**Comment by onrea** [comment]
پس از نظر خروجی بصری که روی وب می گیریم با هم فرقی ندارند، درسته؟

**Comment by Javid-Izadfar** [comment]
خیر. در صورتی که مشکلی پیش نیومده باشه، نباید با هم متفاوت باشن
