### ISSUE TITLE
مشکل نقطه در سایز کوچک

### ISSUE THREAD

**Issue by nimah79** [rastikerdar/vazir-font#66]
فونت وزیر در سایز کوچیک یه مشکلی پیدا می‌کنه. برای مثال اگه کلمه‌ی «پاسخ» رو در Microsoft Word تایپ کنید و سایز فونت رو کم کنید، در یک سایز مشخصی نقطه‌ی حرف خ از حود حرف فاصله می‌گیره.
لطفاً بررسی کنید.

**Comment by rastikerdar** [comment]
ممنونم برای این ایشو. این مشکل به دلیل فرآیند تبدیل فضای برداری به پیکسلی می‌باشد که به آن
rasterization
می‌گویند و در سایز کوچک به دلیل محدودیت‌های پیکسلی این جابجایی ممکن است کمابیش به وجود آید. اگر ممکن است بتوان با طراحی خوب این مشکلات رو کاهش داد اما این رو مشکل من در فونت‌های فارسی/عربی دیگر هم می‌بینم.
