### ISSUE TITLE
همنامی قلم‌های نازک و معمولی

### ISSUE THREAD

**Issue by Javid-Izadfar** [rastikerdar/vazir-font#67]
<p dir="rtl">با سلام</p>
<p dir="rtl">موقعی که نسخه‌ی جدید رو میخوام روی ویندوز نصب کنم، به دلیل هم‌نام بودن قلم‌های نازم (thin) و معمولی (Regular)، آن‌ها جایگذین همدیگه میشن و باید قید یکیشون رو بزنم.</p>
<p dir="rtl">این مورد حداقل در مورد قلم‌های بدون انگلیسی و با ارقام معمولی صادق هست.</p>

**Comment by rastikerdar** [comment]
سلام
کاملا درست فرمودید.
توی نسخه ۱۱.۰.۱ امیدوارم رفع شده باشه.
با تشکر
