### ISSUE TITLE
نام‌گذاری فونتها

### ISSUE THREAD

**Issue by morealaz** [rastikerdar/vazir-font#69]
<div dir="rtl">
با سلام و تشکر از شما به خاطر زحماتتان

در حال حاضر برای فونت وزیر و سایر فونتهای شما چندین نسخه وجود دارد که تفاوت آنها از لحاظ داشتن یا نداشتن اعداد فارسی و همچنین داشتن یا نداشتن کاراکترهای لاتین می باشد که به عنوان نمونه برای فونت وزیر به صورت:
</div>

- Vazir
- Vazir-FD
- Vazir-WOL
- Vazir-FD-WOL

<div dir="rtl">
می‌باشند. نکته ای که وجود دارد این است که تمام این فونتها یک فونت یکسان با نام Vazir را نشان می دهند و در نتیجه نمی توان از این فونت ها به صورت همزمان در سیستم استفاده نمود و حتی در ویندوز امکان نصب آنها به صورت همزمان وجود ندارد.
سوال و درخواست من این است که آیا امکان این وجود دارد که نام این فونت ها را به نحوی تنظیم کنید که نشان دهنده این تفاوت ها باشد و امکان استفاده همزمان از آنها را فراهم نماید؟
این خواهش را در مورد تمام فونت هایی که جناب عالی ایجاد نموده اید  دارم.
با تشکر
</div>

**Comment by rastikerdar** [comment]
کاملا درست می‌فرمایید. به روی چشم.

**Comment by rastikerdar** [comment]
با سلام و احترام
امیدوارم توی نسخه ۱۴ که شامل بهبود فونت و رفع این ایراد هست مشکل حل شده باشه. اگر مشکلی بود ایشو رو مجددا باز بفرمایید تا رسیدگی بشه.
متشکرم برای این ایشو.

**Comment by morealaz** [comment]
متشکرم از زحمات شما
