### ISSUE TITLE
مشکل نیم‌فاصله

### ISSUE THREAD

**Issue by ahmadalli** [rastikerdar/vazir-font#7]

**Comment by ahmadalli** [comment]
همین‌طور حرف م

**Comment by ahmadalli** [comment]
البته همیشه این اتفاق نمیوفته. ولی نمی‌دونم مشکل از فونته یا از ورد چون توی فونت دیگه‌ای ندیدم این اتفاق بیوفته

**Comment by rastikerdar** [comment]
به نظر میاد مشکل از ورد هست. چون با فونت های دیگه هم تست کردم همین مشکلو داشت. شما هم بررسی بفرمایید.

متشکرم بابت گزارش. اگر باز هم مشکلی دیدین ممنون میشم اطلاع بدین.

**Comment by ahmadalli** [comment]
فکر می‌کنم کارکتر نیم‌فاصله توی فونت موجود نیست و برای همین ورد فونت پیش‌فرضش برای این کارکتر رو به‌کار می‌بره. با کارکتر مپ ویندوز چک کردم کارکتر zwnj رو پیدا نکردم
https://en.wikipedia.org/wiki/Zero-width_non-joiner

**Comment by rastikerdar** [comment]
کاملا حق با شماست. از شما هم تشکر می کنم و هم عذرخواهی.
نویسه های فاصله مجازی و نیم فاصله در نسخه ۱.۸ اضافه شدند.

با سپاس فراوان

**Comment by ahmadalli** [comment]
با تشکر از شما، مشکل حل شد :smile:
