### ISSUE TITLE
اِعراب‌گذاری بعد از تشدید زیر تشدید قرار می‌گیرد، نه زیر آن حرف تشدیددار

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#70]
آقای بزرگواری در مورد اعراب فونت‌ها نکته ای بیان فرمودند که به صورت ایشو اینجا کپی می‌کنم:

---

با درود و خسته نباشید

یک مشکل آزاردهنده در فونت‌های فارسی این است که اِعراب‌گذاری بعد از تشدید زیر تشدید قرار می‌گیرد، نه زیر آن حرف تشدیددار. در بعضی از فونت‌ها چنین چیزی درست است، مثلن Tahoma یا Arabic Typesetting

 

حرف «ی» در کلمه‌ی «معنی» این بیت حافظ باید مشدّد خوانده شود، و از طرفی برای درست‌خوانی به کسره نیز نیاز دارد؛ ولی کسره زیر «ی» قرار نمی‌گیرد بلکه مانند خط عربی زیر تشدید می‌رود.

 

فونت بی‌زر:

معنیِّ آبِ زندگیّ و روضه‌ی اِرَم

جز طَرْفِ جویبار و مِیِ خوشگوار چیست؟

 

فونت تاهما:

معنیِّ آبِ زندگیّ و روضه‌ی اِرَم

جز طَرْفِ جویبار و مِیِ خوشگوار چیست؟

 

فونت عربیک تایپ ستتینگ:

معنیِّ آبِ زندگیّ و روضه‌ی اِرَم

جز طَرْفِ جویبار و مِیِ خوشگوار چیست؟

 

ولی متسفانه در فونت‌های زیبا و کاربردی‌ئی مانند صمیم و وزیر و غیره کسره زیر تشدید قرار می‌گیرد، نه زیر حرف «ی». آیا راهی برای حل این مساله هست؟ (ایران‌سنس رو نتونستم تست کنم؛ حدس می‌زنم همین مشکل رو داشته باشه.)

 

یا مثلن «در این فروشگاه رُبِّ انار موجود است». کسره باید زیر «ب» باشه، نه زیر تشدید.

 

امیدوارم اعراب‌گذاریِ مثال‌ها رو چون از طریق ایمیل فرستادم به‌هم نریزه.

مرسی از توجه‌تون

**Comment by zoghal** [comment]
صابر جان اگر با این شخص در ارتباطی می‌تونی بپرسی برای این حرفشون ایا رفرنسی دارند یا نه 
دقیقا بیاد ندارم اما درست نمایش اعرابی که روی یک حرف تشدید میاد دقیقا به این صورت است:
![a004584d_o](https://user-images.githubusercontent.com/174688/27991574-4b8803f0-6490-11e7-9a5f-9c47ee6f81f6.png)
نظر ایشان ظاهرا سلیقه ای هست. مگر بتوانند رفرنسی ارائه بدن تا بشه دقیق پیگیر این موضوع شد.
ممنون میشم ازشون سوال کنید

**Comment by rastikerdar** [comment]
من لینک اینجا رو برایشان گذاشتم. البته برای من هم سواله که چرا مثلا تاهوما زیر حرف قرار می‌ده اما بقیه زیر تشدید؟

**Comment by zoghal** [comment]
بزرگترین مشکل ما در مورد خط فارسی دیجیتال اینه که دیگران برای ما تصمیم گرفتن بدون آنکه از ماهیت خط فارسی / عربی بدانند. و از طرف دیگر خیلی مسایل سلیقه‌ای بوده و الان تبدیل به بدعت شده.

**Comment by bateni** [comment]
این قضیه بسته به سلیقه است.  در کتاب‌های دبستان زمان ما که کسره زیر حرف و نه زیر تشدید گذاشته می‌شد. کتاب‌های جدید را نگاه نکرده‌ام.

در عربی، اکثراً کسره را زیر تشدید می‌گذارند ولی مثلاً در قرآن‌ها اغلب (مثلاً نسخ عثمان طه را ببینید) کسره را زیر خود حرف می‌گذارند.

قلم شهرزاد [یک feature](http://software.sil.org/scheherazade/support/smart-font-features/) برای این انتخاب تعبیه کرده است و به نظرم راه درستش هم همین است تا به کاربر امکان تعیین این مسئله را بدهیم.

**Comment by zoghal** [comment]
در ابتدا وظیفه خودم می‌دانم از جناب دکتر باطنی عزیز که فارغ از جایگاه علمی و تحصیلی و … در اینگونه مباحث مشارکت می‌کنند و دانسته‌های خودشون رو با دیگران مطرح می‌سازند صمیمانه تشکر و قدردانی نمایم.



# اصل مطلب:
من طی پژوهشم به این مورد بر خورده بودم اما چون بعید میدونستم  این مورد توجه کسی رو به خودش جلب کنه زیاد پیگیری نکردمش، بعد از خوندن این بحث مجدد منابع و رفرنس‌هایی که جمع آوری کرده بودم رو مورد بررسی قرار دادم و به این نتایج رسیدم:


۱- بطور کلی نشانه‌ها در فارسی و بر اساس سند «[تبادل و شیوهٔ نمایش اطلاعات فارسی بر اساس یونی کد](https://drive.google.com/file/d/0B63aUENCmKIOWmRiQjMyQ0hDYzA/view)» به شرح زیر می‌باشند: 


![default](https://user-images.githubusercontent.com/174688/28244308-f5bd7a3c-69fc-11e7-84fb-6f791dbc06f5.png)


۲- در نتیجه اینکه اعراب ترکیبی زیر مرتبط به خط رسم فارسی نیست و مربوط به خط رسم قرانی می‌باشد(بعید می‌دونم در عربی معمولی نیز کاربرد زیادی داشته باشد). 


![e7e133fc_o](https://user-images.githubusercontent.com/174688/28244380-fc5e43d8-69fe-11e7-9d99-46c54db8c4bc.png)


۳- همچنین بر اساس تصویر بالا این حرکت‌ها  در ینیکد دارای شناسه یکتا می‌باشند و به در گروه لیگچر‌ها تعریف شدند. پس نوع رفتار این حرکات یعنی زیر هم قرار گرفتن کاملا درست و استاندارد است.

![untitled](https://user-images.githubusercontent.com/174688/28244389-361ed9a2-69ff-11e7-9e49-bfa426c881f6.png)

۴- همچنین در سند «تبادل و شیوهٔ نمایش اطلاعات فارسی بر اساس یونی کد» نیز این مورد تاکید شده است.


# نکته جالب در مورد تشدید در فارسی:

واژه‌های فارسی تحت تأثیر چند چیز تشدید می‌پذیرند ([منبع](http://aryaadib.blogfa.com/post-991.aspx)).
یکی از این چیز‌ها که مرتبط با این ایشو می‌باشد این است که کلماتی که تحت تأثیر اضافات مانند کسره‌ی نقش‌نمای اضافه(هکسره) و واو ربط؛ مانند: زرّ سرخ، فرّ و شکوه  قرار می‌گیرند تشدید دار می‌شوند. مثل معنیّ


در نهایت علت ایجاد این مشکل بدین صورت است که این بزرگوار بیش از حد دارد در مورد رعایت نگارش صحیح کلماتی که کسره‌ی نقش‌نمای اضافه(هکسره) دارند حساسیت به خرج می‌دهند. در واقع در کلمه «معنی» زمانی که تشدید می‌گذاریم دیگر نیاز به کسر نیست

**Comment by rastikerdar** [comment]
مفید و آموزنده بود آقای سوزنچی. سپاس
