### ISSUE TITLE
is this font quite standard for use in mobile applications?

### ISSUE THREAD

**Issue by mrzslr** [rastikerdar/vazir-font#71]
hi there. first of all thanks for this awesome Persian font.
I just have a question in my mind. I wanna use Vazir font in my android application, so is this font suitable for use in mobile apps? 
I mean in the case of size and drawing.

**Comment by rastikerdar** [comment]
سلام
راستش نمی‌دونم شاخص های استاندارد بودن در اپ موبایل چیه با این حال شاید بد نباشه خودتون امتحان کنید.
