### ISSUE TITLE
مشکل با XeLatex

### ISSUE THREAD

**Issue by sae13** [rastikerdar/vazir-font#73]
سلام من فونت وزیر رو برای لاتک استفاده می‌کنم. 
`\documentclass{book}
\usepackage{xepersian}
\settextfont{Vazir}`

وقتی میخوام سرفصل تعریف کنم
`	\chapter{مقدمه}`

پیغام خطای زیر رو می‌ده:
`xdvipdfmx:fatal: Cannot proceed without the font: /usr/share/fonts/truetype/Vazir/vazir-font-master/dist/Farsi-Digits-Without-Latin/Vazir-Bold-FD-WOL.woff`

ولی من فونت رو دارم

` saeb@Fujitsu  ~  fc-list|grep -i "Vazir-Bold-FD-WOL.woff"
/usr/share/fonts/rastikerdar/Farsi-Digits-Without-Latin/Vazir-Bold-FD-WOL.woff: Vazir:style=Bold
/usr/share/fonts/truetype/Vazir/vazir-font-master/dist/Farsi-Digits-Without-Latin/Vazir-Bold-FD-WOL.woff: Vazir:style=Bold
`

**Comment by morealaz** [comment]
<div lang="rtl">
من فکر میکنم این مشکل با نام‌گذاری فونت ها که در #69 اشاره کردم رابطه داشته باشه. چون چند تا فونت هست که همگی با عنوان وزیر شناخته می شوند و همگی در سیستم هم زمان نصب شده‌اند

**Comment by sae13** [comment]
تست کردم انگار مال اون نیست. یه پوشه رو پاک کردم باز هم جواب نداد

**Comment by sae13** [comment]
ممنون حل شد.

`sudo rm \`fc-list|egrep ".+\.woff"|rev|cut -d: -f3|rev\``
