### ISSUE TITLE
ترکیب با فونت لاتین در سایت

### ISSUE THREAD

**Issue by ShahriarKh** [rastikerdar/vazir-font#74]
سلام
فایل https://cdn.rawgit.com/rastikerdar/vazir-font/v14.0.0/dist/font-face.css از نسخه‌ی با حروف لاتین استفاده می‌کنه. لطفاً نسخه‌ی با حروف فارسی و بدون لاتین رو درست کنید. 
(مثلاً به جای Vazir.eot فونت Vazir-FD-WOL.eot بیاد)

**Comment by rastikerdar** [comment]
سلام
برای تمام حالات در پوشه مربوط به خودشان فایل سی‌اس‌اس قرار داده شد. ممنونم برای این ایشو.
