### ISSUE TITLE
اضافه شدن به Google Fonts

### ISSUE THREAD

**Issue by mrdaliri** [rastikerdar/vazir-font#75]
سلام آقا صابر عزیز!

برنامه‌ای برای اضافه کردن این فونت و بقیه فونت‌های هم‌خانواده اون به Google Fonts ندارید؟
با توجه به متن‌باز بودن این فونت‌ها به‌نظرم مشکل لایسنس هم پیش نمیاد.

چون نبود چندتا فونت فارسی مناسب برای متن روی Google Docs واقعا احساس میشه.

**Comment by rastikerdar** [comment]
سلام آقای دلیری عزیز. متشکرم برای توجهتون.
درسته که به لحاظ لایسنس هیچ مشکلی وجود نخواهد داشت اما چون این فونت‌ها بر مبنای یک شیوه کاملا اصولی و آکادمیک که بین متخصصین فونت رایج هست طراحی و پیاده نشده‌اند بعید می‌دانم چه گوگل و چه هر شرکت دیگری حاضر به پذیرش آن‌ها باشد. علاوه بر آن، فونت‌ها کامل و همچنین عاری از اشکال نیستند که اگر چه ممکن است نیاز ۹۹ درصدی جامعه رو پوشش بدهد اما همان یک درصد هم برای استاندارد بودن یک فونت لازم و مورد تاکید است.
در هر صورت گوگل یا هر شرکت دیگری می‌تواند از متخصصین فونت بهره برده و هر کدام از فونت‌ها را که مورد پسند جامعه می‌داند تغییر دهد و به شکل استاندارد مورد نظر خود در بیاورد. 
:)
