### ISSUE TITLE
قرار دادن نسخهٔ با ارتفاع کم در بسته قلم

### ISSUE THREAD

**Issue by rastikerdar** [rastikerdar/vazir-font#77]
به عبارتی ارتفاع قلم با لاتین یکسان باشد. ظاهرا این حالت برای استفاده در موبایل لازم است.

**Comment by Masiha** [comment]
این مورد مثلا در نمایش نوتیفیکیشن‌های گوشی نماد پیدا می‌کند، چون  سیستم‌عامل به اندازه قلم انگلیسی به آن فضا اختصاص می‌دهد ولی ارتفاع متن فارسی از آن بیشتر است و در نتیجه یک برش افقی از متن خارج از کادر می‌افتد.
![CVdB0b5D](https://user-images.githubusercontent.com/290224/54872075-101d2480-4ddc-11e9-99b9-15ce8be313d3.png)

**Comment by rastikerdar** [comment]
یک نسخه با ارتفاع کم در بسته قلم قرار داده شد تا این مشکل رفع بشه
UI
https://github.com/rastikerdar/vazir-font/releases
