### ISSUE TITLE
حروف لاتین غیر انگلیسی

### ISSUE THREAD

**Issue by ControlAdad** [rastikerdar/vazir-font#79]
سلام
از ساخت فونت خوانای وزیر متشکرم
امکان دارد حروف لاتین غیر انگلیسی را هم اضافه کنید
لطفا به تصویر توجه کنید:
[
![screenshot_9](https://user-images.githubusercontent.com/179375/31581890-190f6bf4-b182-11e7-96be-0c57378754c6.jpg)
](url)

**Comment by rastikerdar** [comment]
سلام. ممنونم.
راستش برای اینکه حجم قلم زیاد نشه کلیه حروف لاتین غیر انگلیسی حذف شدند. شما می‌تونید از نسخه بدون لاتین فونت که در بسته موجود است استفاده کنید تا برای انتخاب نوع قلم لاتین یکدست، راحت باشید. و یا اینکه قلم دوم یا لاتین رو روی قلم روبوتو تنظیم کنید که اگر حرفی در قلم وزیر نبود از روبوتو نمایش دهد.

راه حل سوم اینه که تمامی گلیف‌های لاتین روبوتو رو با وزیر ترکیب کنیم که شرایط برای توسعه دشوار خواهد شد.

**Comment by ControlAdad** [comment]
سلام
بله حجم زیاد میشه - شاید بهتر باشه از دو فونت استفاده بشه
از جواب شما متشکرم
