### ISSUE TITLE
Missing Glyph

### ISSUE THREAD

**Issue by karianpour** [rastikerdar/vazir-font#81]
Missing "Arabic Date Separator" U-060D which is very important for date typing as the direction of this glyph should be set always left to right, so with this character it can be typed 11/09/1395 and the result will be 1395/09/11, the normal slash character (Solidus U-002F) does not do that as the character has not strong left to right direction and should not. I tried to show it in attachment. And the shape of the glyph can be the same as slash.

![image](https://user-images.githubusercontent.com/24288617/34325139-4ffce134-e89e-11e7-8311-aea5d03644c4.png)

**Comment by rastikerdar** [comment]
Done, thanks.
![screenshot from 2018-01-08 10-03-42](https://user-images.githubusercontent.com/3116038/34661763-124f2bd4-f461-11e7-8f0c-9d32f0e77965.png)
