### ISSUE TITLE
عدم نمایش "ئ" در فونت سایزهای کوچک

### ISSUE THREAD

**Issue by AliMottaghiPour** [rastikerdar/vazir-font#83]
با سلام
من از آخرین ورژن و در وب سایت از این فونت استفاده میکنم. در فونت سایزهای کوچیک (11 و کمتر) و در کلماتی مثل "مسئول" کلمه "ئ" نمایش داده نمی شود. با هر دو مرورگر فایرفاکس و کروم (ویندوز 7) هم این مشکل وجود دارد.

**Comment by rastikerdar** [comment]
با سلام و تشکر
آیا علامت همزه کلا دیده نمی‌شود یا مثلا به صورت نقطه قابل مشاهده است؟

**Comment by AliMottaghiPour** [comment]
با سلام مجدد
کلا دیده نمیشه
![4854854](https://user-images.githubusercontent.com/20952617/35197586-a1f05804-fef6-11e7-9738-864be91ac878.jpg)

**Comment by rastikerdar** [comment]
اگر برایتان مقدوره نام سیستم عامل و برنامه‌ای که در آن به این مشکل برخوردید رو بفرمایید.

**Comment by AliMottaghiPour** [comment]
هر دو سوالی که تا الان پرسیدید من تو گزارش اولم جوابش را گفته بودم
سیستم عامل ویندوز 7
در همه مرورگرهای معروف (کروم، فایرفاکس، اپرا و آی ای)

**Comment by rastikerdar** [comment]
آخ ببخشید خیلی بی‌دقتی کردم.

راستش من هر جوری تست می‌کنم حتی "مسئول"ی که نوشتید رو کپی می‌کنم چه توی مرورگرها چه برنامه‌های دیگه مشکل رو نمی‌تونم ببینم. اگر تنها با فونت وزیر به این مشکل برخوردید پس احتمالا ایراد در خود فونت وزیر باشه.
ممنونم برای گزارش

**Comment by zoghal** [comment]
تو ویندوز ۱۰ من هم تست کردم مشکلی نبود!

**Comment by rastikerdar** [comment]
من موفق نشدم این مشکل رو بازتولید کنم اما اگر با نسخه آخر وزیر یعنی 24.2.0 این مشکل برطرف شده پس ایشو رو ببندیم در غیر اینصورت باز بمونه.
[https://github.com/rastikerdar/vazir-font/releases](https://github.com/rastikerdar/vazir-font/releases)
