### ISSUE TITLE
حذف دو نقطه در ي عربی

### ISSUE THREAD

**Issue by najafzadeh1055** [rastikerdar/vazir-font#84]
با سلام و سپاس به خاطر طراحی و نشر فونت زیبای وزیر
با توجه به فارسی بودن فونت، در صورت صلاحدید حرف "ي" عربی با دو نقطه، به ی عادی تبدیل شود
با تشکر

**Comment by rastikerdar** [comment]
با سلام و احترام
دغدغه شما رو درک می‌کنم اما فکر می‌کنم که به دلایلی این کار صحیح نباشد.

**Comment by mokhosh** [comment]
بله هر کاری باید سر جای خودش انجام بشه و جای این کار توی نرم افزار هست بسته به نیازتون، نه توی فونتی که باید بر اساس استاندارد، تمام انواع کاربری ها رو جوابگو باشه.
