### ISSUE TITLE
مشکل الف چسبان با رنگ پس زمینه

### ISSUE THREAD

**Issue by WebNashr** [rastikerdar/vazir-font#85]
در صورت قرار دادن پس زمینه برای نسخه لایت الف به شکل زیر نمایش داده می شود:
![image](https://user-images.githubusercontent.com/7099274/36789170-d3f541f8-1ca5-11e8-88d3-ec4a5982712f.png)

**Comment by zoghal** [comment]
چه باحال شده؟
صابر جان دو تا شیب روی هم افتاده؟

**Comment by rastikerdar** [comment]
صالح جان راستش هر چی نگاه می‌کنم مشکلی توی خود گلیف پیدا نمی‌کنم. برام عجیبه.

**Comment by zoghal** [comment]
@rastikerdar من تو یک تست سریع مشکلی ندیدم!
@WebNashr  دوست عزیز لطف می‌کنید کمی بیشتر توضیح بدید که این مشکل در چه مرورگری، سیستم عاملی اتفاق می‌افتد؟
و دقیقا کدام فایل رو لود می‌کنید؟ اسم و فرمت رو حتما ذکر کنید.
و آیا از آخرین نسخه استفاده می‌کنید؟

**Comment by WebNashr** [comment]
@zoghal عرض کردن نسخه لایت مرورگر کروم آخرین نسخه فونت

**Comment by zoghal** [comment]
@WebNashr من روی این سیستم :
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3355.0 Safari/537.36
```
هیچ مشکلی نداشتم در ضمن سیستم عامل رو هم فراموش کردید؟ ویندوز لینوکس یا مک؟ و چه نسخه‌ای؟
برای تست مهم هستند.

لطفا یکبار در این صفحه([اینجا](http://libre.font-store.ir/PersianFontTestingTools/)) تست بزنید کافیه فایل فونت را در بخش هدر دراگ دروپ کنید و ببینید باز مشکل دیده می‌شود یا خیر؟(در بالای صفحه متن‌ها امکان تغییر رنگ وجود دارد)

در کل یک باگ استثنایی هست :))

**Comment by WebNashr** [comment]
ویندوز ۱۰در حالت بولد این حالت پیش میاد اگر چه

**Comment by rastikerdar** [comment]
ببخشید من نتونستم این مشکل رو بازتولید کنم. اگر با نسخه آخر وزیر یعنی 24.2.0 این مشکل برطرف شده پس ایشو رو ببندیم در غیر اینصورت باز بمونه.
[https://github.com/rastikerdar/vazir-font/releases](https://github.com/rastikerdar/vazir-font/releases)
