### ISSUE TITLE
بهبود فونت وزیر برای اپلیکیشن های موبایلی

### ISSUE THREAD

**Issue by oky2abbas** [rastikerdar/vazir-font#87]
سلام . تشکر میکنم از شما برای انتشار این فونت به صورت آزاد  .
من فونت های شما رو تست کردم برای اپلیکیشن های اندروید و فونت وزیر بهترین فونت هست برای این نوع دیوایس ها و البته فونت ساحل هم خوبه ولی مشکلاتی داره که داخل صفحه خودش مطرح میکنم اما در مورد فونت وزیر :

مشکل اول : فونت وزیر نصبت به چند نسخه اولیه خودش متاسفانه حجم نوشته ها رو زیاد میکنه من از نسخه ۱ از این فونت استفاده میکنم و طی این مدت متوجه شدم تغییرات شما داره این فونت رو شبیه به فونت یکان میکنه در صورتی که در اوایل شبیه به ایران سنس شریف بود که این خیلی بده .

مشکل دوم : حروف در یک سطح هستند اما وزن یکی ندارن و مثلا شاهد این هستیم که یک حرف ممکنه به صورت عمودی با حروف دیگه به یک میزان ارتفاع نداشته باشه که از خانایی فونت کم میکنه در دستگاه های موبایلی .

طی برسی های تمام فونت های شما متوجه شدم بهترین فونت برای وبسایت ها ساحل و بهترین فونت برای موبایل ها و تبلت ها وزیر هست پس لطفا سعی کنید هماهنگی بیشتری با دستگاه های موبایلی به وزیر بدین . شما این همه فونت ساختید لطفا این یکی رو بزارین برای ما توسعه دهنده های اپلیکیشن های اندروید لطفا خرابش نکنید  :) تشکر .

**Comment by rastikerdar** [comment]
سلام
تشکر می‌کنم برای این ایشو.
۱. توی صفحه زیر مقایسه چند نسخه ابتدایی با نسخه آخر آمده است. راستش دوستان می‌فرمودند که وزیر به مرور بهتر شده به ویژه توییت نسخه آخر (۱۸.۰.۰).  
[rastikerdar.github.io/vazir-font/compare.html](http://rastikerdar.github.io/vazir-font/compare.html)  

من درک می‌کنم که چرا ایران‌سنس معیاری برای قضاوت در مورد سایر فونت‌ها گردیده اما واقعیت امر اینست که از روز نخست هم، نه به ایران‌سنس توجهی داشته‌ام و نه به رقابت با آن، که اگر با سلیقه من همخوان بود که اساسا خودم رو به زحمت پرهزینه و گزاف تولید فونت نمی‌انداختم. اصلا قرار نبوده و نیست که وزیر به فونتی شبیه باشد. وزیر بر مبنای سلیقه و درک شخصی از مقوله خط ایجاد شده. من با وزیر خیلی راحت‌تر از ایران‌سنس مطلب می‌خوانم. آرامش بیشتری دارم. با ساحل و صمیم و یا گندم نیز. مبنای وزیر فونت‌های تاهوما و دژاوو بوده (خودم خیلی به این دو علاقه‌مندم) اگر چه نمی‌تونم اعمال سلیقه ناشی از علاقه خودم نسبت به رویا و نازنین و دروید رو هم پنهان کنم. در مورد چرایی و نحوه پیدایش وزیر، در یک پست توضیح داده‌ام.
[rastikerdar.blog.ir/1395/07/25/وزیر-چرا-و-چگونه-آمد](http://rastikerdar.blog.ir/1395/07/25/%D9%88%D8%B2%DB%8C%D8%B1-%DA%86%D8%B1%D8%A7-%D9%88-%DA%86%DA%AF%D9%88%D9%86%D9%87-%D8%A2%D9%85%D8%AF)
البته پرستو و شبنم، به نازنین و یکان شبیه‌اند چون که اساسا بر مبنای درک و الهام از آنها ساخته شده‌اند. 

دلیل تغییر تایپ‌فیس وزیر در نسخه‌های متعدد (فارغ از بحث رفع ایرادات در ضخامت و زاویه و انحنا و ...) در واقع موضوع هماهنگی و ساده‌تر شدن آن و همچنین اعمال سلیقه مخاطبان بود. آیا شما شکلی ساده‌تر از این برای تمامی گلیف‌های فونت وزیر می‌توانید متصور باشید؟ اگر بلی بفرمایید تا اعمال شود. یا برای مثال شکل‌های «م» را در توییتر به رای گذاشتم که تقریبا همه دوستان به جز خودم و دو سه نفر رای به شکل فعلی «م» دادند.

![vazir18](https://user-images.githubusercontent.com/3116038/37111345-b4597e5e-2254-11e8-8900-7480d4ec566a.png)

من سخن شما رو درک می‌کنم. در واقع به خاطر اعتراض چندباره برخی دوستان به «روند تغییرات از نسخه یک به بعد» بود که فونت دیروز را بر مبنای نسخه شماره یک وزیر آماده کردم. اگر از «دیروز» استقبال می‌شد خب من روند توسعه رو از وزیر به دیروز منتقل می‌کردم (شخصا وزیر یک رو بیشتر از همه فونت‌ها می‌پسندم).  
[rastikerdar.github.io/dirooz-font/](https://rastikerdar.github.io/dirooz-font/)

این را از این بابت می‌گویم که اگر به دنبال ایران‌سنس دیگری می‌باشید با احترام و صداقت می‌گویم به دنبال فونت دیگری باشید.

۲. این مشکل را ای کاش با مثال نشان می‌دادید چون حقیقتش متوجه منظورتان نشدم.

۳. در مورد هماهنگی با موبایل نیز کاملا حق با شماست اما راستش رو بخواهید من دقیقا نمی‌دونم چه ویژگی‌ای رو باید برای وزیر در نظر بگیرم. مثلا نمی‌دانم در ایران‌سنس نسخه موبایل که بسیار رایج است چه ویژگی‌ای در نظر گرفته شده است.

**Comment by okabbas** [comment]
سلام . با تشکر از پاسخ شما من منظورم از مثال زدن فونت ایران سن سریف این بود که این فونت هماهنگی با اپلیکیشن های موبایل داره و نسخه های اولیه وزیر هم اینطور بودن و هرگز هدفم این نبوده بگم شبیه به این فونت وزیر رو بسازید (اگر همچین برداشتی داشتید عذر خواهی میکنم) .


سه فونت وزیر۱ و وزیر ۱۸ و دیروز رو با هم مقایسه کردم در اندروید و چیزی که میتونم بگم اینه که فونت نسخه ۱ وزیر متفاوت با فونت دیروز بود و نسخه ۱ وزیر از فونت دیروز از نظر من داخل موبایل خوانا تر بود و تفاوت کمی داشتن البته . 

و در مجموع فونت نسخه ۱۸ وزیر از این ها خوانا تر بود و حرف قبلیم رو پس میگیرم و عذر خواهی میکنم .

اما چیزی که مورد توجه بود این هست که در مجموع فونت های وزیر ۱ یا دیروز جمع و جور تر از فونت وزیر ۱۸ هستن و در متن های طولانی وزیر ۱۸ فضای بیشتری رو در بر میگیره و نمیدونم این بهتر هست یا بد تر چون تخصصی ندارم .

جناب راستی کردار از نظر من شما بهترین در شغل خودت هستی و اینکه این کار رو به صورت آزاد انجام میدی ارزش کار شما رو چند برابر میکنه واقعا ممنونم .

**Comment by okabbas** [comment]
سلام . من یکم توضیح میدم تا وضعیت و تفاوت وب و موبایل رو بیشتر درک کنید .

تفاوت اپلیکیشن و وبسایت در این هست که وبسایت شامل متن های طولانی یا غیر طولانی هست و در اینجا بحث سایز المان ها کمتر دیده میشه مثلا متن شما در یک صفحه سفید شناور هست یا … و اکثرا در المان ها و ایتم های بزرگ قرار میگیرن .

اما اپلیکیشن موبایل مثلا کافه بازار و دیجی کالا رو در نظر بگیرید اکثر محتوی متنی این اپلیکیشن ها ۱ کلمه هستن و یا ۲ کلمه و گاهی پیش میاد متن ها فوق العاده کوچیک میشن به دلیل اینکه باید در یک المان مثلا ۵۰ در ۵۰ پیکسلی جابگیرن مخصوصا اگر سایز صفحه نمایش تغییر کنه و به اون نصبت سایز فونت کم و زیاد میشه و مشکل اینجاست هرچه فونت کوچکتر میشه اگر فونت ذخیم باشه خوانایی کمتر میشه و برعکس هرچه فونت بزرگتر میشه اگر نازک باشه زشت تر میشه و فونت سن سریف تا حدودی تونسته از پس این مشکل بر بیاد با نازک کردن فونت های نسخه موبایلش (البته من شخصا علاقه ای به این فونت ندارم)

در اپلیکیشن های موبایل فونت باید به یک حد استاندارد برسه که در المان های مختلف در سایز های کوچک و بزرگ و در متن های معمولی و تک کلمه ای بتونه خوانایی خودش رو بالا ببره . این که فونت وزیر برای موبایل راحت تر و بهتر هست دلیلش اینه که این فونت از شکستگی کمتری (منظورم اینه خطوط ساده رسم میشن) برخورداره و زمانی که ریز میشه کلمات از دور قابل تشخیص هست تا حدودی


در آخر باید بگم احساس میکنم اگر لبه های آخر حروف به جای خطی گرد باشن بهتر میشه مثلا اگر به عکسی که در بالا خودتون در پاسخ به من ارسال نگاه کنید میبینید که حروف مثلا “ا” یا عدد “۱” به صورت مستطیل عمودی هستن و به نظرم اینکه مثلا “۱” لبه های بالا و پایینش گرد تر باشه بهتره البته نه فقط این دو حرف بلگه همه حروف . الان در فونت وزیر تمام لبه های تمام حروف خط مستقیم هستن و فونت به جمع و جوری ساحل برسه .

البته این پیشنهادات منه و ممنون میشم اگر این موارد رو در آینده هروقت وقت داشتید برسی کنید و در صورت پذیرفتن انجام بدین .  من توسعه دهنده هستم و تخصصی در این موضوع ندارم مگرنه خودم اصلاح میکردم :) با تشکر .

**Comment by okabbas** [comment]
من مجموع برسی هام رو در مورد فونت ها در وبلاگم منتشر کردم  : http://okcode.ir/tutorial/%D8%A8%D9%87%D8%AA%D8%B1%DB%8C%D9%86-%D9%81%D9%88%D9%86%D8%AA-%D9%81%D8%A7%D8%B1%D8%B3%DB%8C-%D8%A8%D8%B1%D8%A7%DB%8C-%D9%85%D9%88%D8%A8%D8%A7%DB%8C%D9%84-%D9%88-%D9%88%D8%A8/

و فونت وبلاگ من هم ساحل هست (با تشکر از شما) امیدوارم همیشه موفق باشید و به زودی به فونت های شما هم کمک مالی انجام میدم و امیدوارم بتونم یکم تخصص کسب کنم که حداقل fork کنم فونت وزیر رو و بتونم تغییراتی داخلش انجام بدم کسی چه میدونه شاید واقعا تونستم :)

**Comment by rastikerdar** [comment]
وزیر برای تغییر کاملا آزاد است. حتی پیشنهاد می‌کنم نسخه‌ای دلخواه از روی وزیر بسازید و با لایسنس دلخواهتون بفروشید.

**Comment by zoghal** [comment]
درود بر همگی، ببخشید می‌پرم وسط فقط می‌خواستم یک درخواستی کنم از @okabbas پیرامون این بخش از صحبت‌هاشون.

> تفاوت اپلیکیشن و وبسایت در این هست که وبسایت شامل متن های طولانی یا غیر طولانی هست و در اینجا بحث سایز المان ها کمتر دیده میشه مثلا متن شما در یک صفحه سفید شناور هست یا … و اکثرا در المان ها و ایتم های بزرگ قرار میگیرن .
اما اپلیکیشن موبایل مثلا کافه بازار و دیجی کالا رو در نظر بگیرید اکثر محتوی متنی این اپلیکیشن ها ۱ کلمه هستن و یا ۲ کلمه و گاهی پیش میاد متن ها فوق العاده کوچیک میشن به دلیل اینکه باید در یک المان مثلا ۵۰ در ۵۰ پیکسلی جابگیرن مخصوصا اگر سایز صفحه نمایش تغییر کنه و به اون نصبت سایز فونت کم و زیاد میشه و مشکل اینجاست هرچه فونت کوچکتر میشه اگر فونت ذخیم باشه خوانایی کمتر میشه و برعکس هرچه فونت بزرگتر میشه اگر نازک باشه زشت تر میشه و فونت سن سریف تا حدودی تونسته از پس این مشکل بر بیاد با نازک کردن فونت های نسخه موبایلش (البته من شخصا علاقه ای به این فونت ندارم)
در اپلیکیشن های موبایل فونت باید به یک حد استاندارد برسه که در المان های مختلف در سایز های کوچک و بزرگ و در متن های معمولی و تک کلمه ای بتونه خوانایی خودش رو بالا ببره . این که فونت وزیر برای موبایل راحت تر و بهتر هست دلیلش اینه که این فونت از شکستگی کمتری (منظورم اینه خطوط ساده رسم میشن) برخورداره و زمانی که ریز میشه کلمات از دور قابل تشخیص هست تا حدودی


من صحبت‌های شما رو خوندم راستش دقیقا متوجه منظورتان نشدم، اما فکر می‌کنم با یکی از مباحث پژوهشنامه من در ارتباط باشد. لذا گفتم ازتون بخواهم در صورت وقت آزاد در مورد این موضوع در تلگرام یک گپی باهم بزنیم، شاید شما دارید به یک نیاز جدید اشاره می‌کنید که فراتر از ذهنیت من هست.(چون تجربه توسعه اپ موبایل را ندارم.). شناسه من در [تلگرام](http://t.me/zoghal/)

در آخر پیشاپیش سال نو رو به همگی و مخصوص به صابر عزیز تبریک عرض می‌کنم.

**Comment by rastikerdar** [comment]
ممنونم صالح جان. بر شما هم مبارک.
من هم فکر می‌کنم حرف‌های صادق خیلی مهمه و اگر به عنوان یه مخاطب نکته‌سنج نظرش برآورده بشه احتمالا خروجی همون چیزی می‌شه که همه می‌پسندند.

**Comment by seyedmmousavi** [comment]
فونت ساحل از لحاظ فیس خیلی زیباست و در یک مورد پروژه موبایل استفاده کردم.
فونت وزیر اما برای موبایل دارای ارتفاع بیش از حد است. یعنی تصور کنید یک صفحه رتبه بندی داریم که تعدادی ستاره نمایش داده میشه و قراره زیر اون یک متنی نوشته بشه. این متن فاصله بیش از حدی خواهد داشت چون ارتفاع فونت زیاده.
در کل برای برنامه‌های موبایل، فشردگی سطرها لازمه و سایزهای کوچک مرسوم تره
از لحاظ فیس، متوجه شدم نسخه ۵ کلا یک شکل دیگری داره و نظر من رو جلب کرد.

**_یک نکته بسیار بسیار مهم رو هم بگم، چون تجربه کردم؛_**
در کارهای هنری نمیشه نظر همه رو روی یک طرح اعمال کرد. چون نظر حتی دو تا هنرمند در یک موضوع متفاوته چه برسه به غیر هنرمند. به نظرم باید طرح، تنها توسط یک طراح مدیریت بشه و همه نظرها از فیلتر همون یک شخص رد بشه. نباید طرح مثلا در نسخه ۵ متفاوت بشه و باز در نسخه ۸ چیز دیگری بشه. اصالت و ایده و نظر اصلی طرح از بین میره.
در عوض میشه فونتهای متعددی با نظرهای متعددی داشت که هر کدوم اصالت ایده اصلی خودشون رو حفظ کنن.

**Comment by rastikerdar** [comment]
@seyedmmousavi 
در مورد پروسه طراحی درست می‌فرمایید. ولی حقیقتش در مورد فونت وزیر کار کمی پیچیده شده بود. اما خب فکر می‌کنم وزیر به شکل معقولی رسیده و تناسباتش به گونه‌ای منطقی به نظر می‌رسه به طوری که اگر نگیم زیبا هست ولیکن زشت هم نباشه. یه شکل ساده و عمومی. ممکنه در مورد ضخامت تصمیمات بهتری می‌شد اتخاذ کرد اما در مورد شکل ایده خاصی ندارم. شاید هم من اشتباه کرده‌ام.

در مورد نسخه موبایل هم درست می‌فرمایید اما تا الان چیزی که به ذهنم رسیده این بوده:
[github.com/rastikerdar/fontservice](https://github.com/rastikerdar/fontservice)

**Comment by seyedmmousavi** [comment]
@rastikerdar 
من بسیار از شما سپاس گذارم به دو دلیل؛
اول اینکه حرفه‌ای هستید اما از تکبر به دور هستید و راستیکردارید
دوم اینکه حرکت بسیار ارزشمندی انجام دادید که فراتر از توانایی بسیاری از ماست.
به نظرم فونتهای بسیار زیبایی طراحی نمودید. مخصوصا فونت ساحل که خیلی خاص است.
از شما سپاسگذارم
موردی که فرمودید خیلی خوبه. البته حالتهای پر کاربرد رو اگه بشه آماده داشت خیلی خوبه. به هر حال باید صبر کرد. متاسفانه بنده در این زمینه نمیتونم همکاری داشتم باشم. من کیوت کار هستم و طراح تجربه کاربری.
این رو هم بگم که بنده هم قصد دارم کارهای حرفه‌ای عام المنفعه ای انجام بدم که البته به دلیل تفاوت دیدگاه من با تفکرات متن باز، نتیجه‌ای متفاوت خواهد داشت. امیدوارم موفق بشم.

**Comment by rastikerdar** [comment]
توی نسخه‌های اخیر تلاش شد وزیر جمع و جورتر بشه. امیدوارم به مقصود شما نزدیک شده باشه. اگر چنین فکر می‌کنید ایشو رو ببندیم.  
[https://rastikerdar.github.io/vazir-font/compare.html](https://rastikerdar.github.io/vazir-font/compare.html)
