### ISSUE TITLE
افزودن فونت heavy

### ISSUE THREAD

**Issue by hashemp206** [rastikerdar/vazir-font#91]
سلام 
تشکر از طراحی این فونت بسیار زیبا

آیا برنامه‌ای برای افزودن نسخه هیوی به این فونت دارید؟ در طراحی های متناسب با آی او اس ۱۱، فونت هیوی ضروری است

**Comment by rastikerdar** [comment]
سلام
در نسخه جدید اضافه گردید.
Vazir-Black
با تشکر
