### ISSUE TITLE
Free Persian fonts for Ubuntu initiated with Vazir font

### ISSUE THREAD

**Issue by par6n** [rastikerdar/vazir-font#94]
For the sake of simplification of font installation process in Ubuntu, I created a PPA for free Persian fonts, which is compatible with Ubuntu 18.04 and later. Using this PPA, installing Persian fonts is easier, just open a terminal and type these commands:
```bash
sudo add-apt-repository ppa:blacksuited/fonts
sudo apt install fonts-vazir
```
It won't be necessary to deal with `fc-cache`. Other free Persian fonts will be added to the archive.

**Comment by rastikerdar** [comment]
Thank you Ehsan :+1:
How about adding this to the [Install](https://github.com/rastikerdar/vazir-font#install) section?

**Comment by MersadAkbari** [comment]
Salam @par6n , Dadash `apt update` yadet raft

**Comment by par6n** [comment]
> Salam @par6n , Dadash `apt update` yadet raft

The repository is discontinued since I lost the private keys required to update the repo. I don't know what you mean by `apt update`.

**Comment by rastikerdar** [comment]
پس بهتره حذفش کنیم از صفحه اصلی

**Comment by MersadAkbari** [comment]
وقتی یه Repository اضافه میشه باید یه بار apt update بزنی تا بتونی ازش استفاده کنی

**Comment by rastikerdar** [comment]
با توجه به اینکه اون روش دیگه قابل استفاده و بروزرسانی نیست من حذفش کردم. با تشکر از شما.

**Comment by sinalalebakhsh** [comment]
> با توجه به اینکه اون روش دیگه قابل استفاده و بروزرسانی نیست من حذفش کردم. با تشکر از شما.

سلام دوست عزیز نحوه حذف کردن تون با چه کامندی بوده ؟ لطفا راهنمای کنید
