### ISSUE TITLE
Can you add Urdu support to the font?

### ISSUE THREAD

**Issue by nasirpk** [rastikerdar/vazir-font#96]
Urdu is very similar to Persian and both languages share most of letters but Urdu has some additional letters. It will be highly appreciable if your fonts support Urdu too by adding some Urdu specific letters to the font like ہ، ھ، ے ، ڈ، ٹ، ڑ . Many of these characters require some modification in existing letters using shapes and do not require creating new shapes. Moreover, support for Urdu in default Ubuntu fonts is very poor and many default fonts have to be disabled in order to properly see Urdu text. Therefore it will be great to see some mature fonts like these supporting Urdu. Thank you!

**Comment by rastikerdar** [comment]
Thank you for this issue. I should plan for this and the old #13.

**Comment by rastikerdar** [comment]
The last version (released a few minutes ago) supports Urdu language. I'm sorry it took so long. Thank you for your patience.
