### ISSUE TITLE
مشکل با لیگیچرها

### ISSUE THREAD

**Issue by aminabedi68** [rastikerdar/vazir-font#97]
سلام صابرجان، خسته نباشی
من با لیگیچرهای که فرمهای پایانی و ایزوله «ه» و «یای کوتاه» رو میارن مشکل دارم، آیا این یه روش مناسب برای وارد کردن شکل صحیح این حروف هست یا ضرورت باعث ابتکار این روش شده؟ و آیا ممکنه کسی دیگه‌ای تو زبان عربی با وارد کردن این حروف و دریافت نتیجه لیگیچرها به مشکل بخوره؟
و یه مسئله دیگه، من میخواستم برای حل حالات اشتباه دیگه‌ای که توی وب رایج شده چند تا لیگیچر بنویسم مثل اینا:
-ه+فاصله+ی+فاصله=ه+یای کوتاه
-ه+نیم فاصله+ی+نیم فاصله=ه+یای کوتاه
اما ظاهرا جواب نمیده، به نظرم این موضوع نیاز به بحث بیشتر داره

**Comment by rastikerdar** [comment]
سلام و ممنون
در مورد این موضوع فکر می‌کنم صالح اطلاعات خوبی داشته باشه. @zoghal
راستش نمی‌دونم چه این لیگچر با یای کوتاه و چه «ه» همزه‌دار چقدر توی عربی کاربرد داره. مثلا توی توضیح این گلیف نوشته:
![screenshot from 2018-05-03 18-30-21](https://user-images.githubusercontent.com/3116038/39581138-223f702c-4f00-11e8-8623-3c73ba583edb.png)

Arabic letter HEH with **Yeh** above
هر چند که در ادامه مساویش کرده با همزه

در مورد مسئله دوم مطمئنی اساسا با فاصله میشه لیگچر ایجاد کرد؟ من خاطرم نیست فقط گفتم اول مطمئن بشیم.

**Comment by zoghal** [comment]
درود بر همگی

۱- نکته اول: یای کوتاه اشتباه هست. یای دوم بریده یا یای دم کوتاه درستش هست. وقتی اسم دم که بیاد زمان طراحی گلیفش از وسط ی گلیف را  قطع نمی‌کنید که مجدد شبیه به همزه یا کافچه کاف عربی بشود. یک قوس کوچولو به سمت بالا نیاز دارد البته نظر شخصی من هست.


# اما عنوان ه + همزه:

نکته: شاید در فونت‌های مختلف ظاهر گلیف حرف ه یکسان باشد یا حتی در نوشتار شاید شبیه ه ما باشند، اما در تلفظ و نوع آوایی که دارد فرق دارند.



## ۱- برای زبان Uighur, Kazakh, Kirghiz:
![uighur kazakh kirghiz copy](https://user-images.githubusercontent.com/174688/39626950-40363bd8-4fb9-11e8-9774-4ce62634c4a6.png)

در زبان یوگوری این حرف دقیقا(۹۸٪ فکر می‌کنم 💃 ) نقش هکسره تو فارسی را دارد.

تو فارسی: قطرۂ آب => قطره‌ ی آب
تو یوگوری : قطرِ آب تلفظ میشه.




## ۲- اردو:
![uniview_10_0_0_-_2018-05-04_14_59_03 copy](https://user-images.githubusercontent.com/174688/39626952-4433627e-4fb9-11e8-9fd7-8eeb78883d12.png)

گویا در زبان اردو شکل فرم ه چندین حالت دارد (فکر می‌کنم در نستعلیق به یک شکل است در نسخ شکل دیگر؟!)

![arabic_character_notes_-_2018-05-04_17_21_20](https://user-images.githubusercontent.com/174688/39629049-2927994e-4fc0-11e8-8075-bcc85d2ffc34.png)

![arabic_character_notes_-_2018-05-04_17_14_47](https://user-images.githubusercontent.com/174688/39629051-2b964392-4fc0-11e8-955c-a4edc648563e.png)


در زبان اردو این حرف دقیقا(۹۸٪ فکر می‌کنم 💃 ) نقش هکسره تو فارسی را دارد.

تو فارسی: قطرۂ آب => قطره‌ ی آب
تو اردو: قطرِ آب تلفظ میشود.

(گویا در مدت زمان تلفظ آوا با یوگوری تفاوت دارند خودم هنوز این رو مطمئن نیستم. اگر کشف کردید، لطفا به بنده هم بگویید داستان از چه قراره)




## ۳- اما شیرین شکر، قند فارسی 👍 

برای فارسی سناسه کاراکتر مفرد و تمامی چهار فرم‌ آن:
![farsi-letter copy](https://user-images.githubusercontent.com/174688/39629373-33b520ec-4fc1-11e8-8f9a-cf6373804590.png)


به دو صورت می‌شود هٔ و ‍هٔ رو تعریف کرد:

![uniview_10_0_0_-_2018-05-04_15_12_16 copy](https://user-images.githubusercontent.com/174688/39629419-5f4d0f30-4fc1-11e8-95fd-176d5a81b484.png)
![uniview_10_0_0_-_2018-05-04_15_15_17 copy](https://user-images.githubusercontent.com/174688/39629423-609e0bdc-4fc1-11e8-84fc-01969460f337.png)

## ۴- و اما زبان عربی:
تنها حروفی که می‌توانند همزه بگیرند این‌ها هستند. حرف ه فقط ضمه، فتحه،کسره، و سکون و مد آن هم در رسم الخط قرآنی اعراب می‌گیرد.

![arabic_character_notes_-_2018-05-04_18_24_03](https://user-images.githubusercontent.com/174688/39631807-77375284-4fc8-11e8-8495-3a74f88b8c43.png)


## و اما بحث بعدی:
امین عزیز اگر بدرستی منظورت از این:
>  -ه+فاصله+ی+فاصله=ه+یای کوتاه

را فهمیده باشم شما دنبال همیچین چیزی هستید؟

![amozeh-regular](https://user-images.githubusercontent.com/174688/39630467-9ccb3834-4fc4-11e8-99c6-5f73f938f1bc.gif)

بله میشه، اما اگری بری دنبالش خودت رو گول زدی و وقت رو هدر!
چون فونت فقط حروف رو  فقط در نمایش تغییر می‌دهد چیزی که شما دنبالشی آخرش میرسی به این:
![_-_-_2018-05-04_18_04_17](https://user-images.githubusercontent.com/174688/39630884-eecd290c-4fc5-11e8-8db9-c6ea094774fa.png)

اما وقتی یک متن بدرستی و استاندارد تایپ شده باشد، منظورم رعایت فاصله کوتاه در نمایش:
![_-_-_2018-05-04_18_05_18](https://user-images.githubusercontent.com/174688/39630981-39d1520c-4fc6-11e8-9cff-d359f31c9040.png)


امیدوارم پاسخ سوالاتت رو کامل داده باشم.
شاد و پیروز باشید.

**Comment by aminabedi68** [comment]
از هر دو نفر شما ممنونم, به نظر میرسه استاندارد مناسبی برای وارد کردن این کارکترها به صورت لیگیچر وجود نداره، البته شاید تگهای زبانی جداول بتونن اختلاف این موارد رو از هم تشخیص بدن(دو جدول با تگهای زبان متفاوت که ورودی یکسان و خروجی مطابق زبان استفاده شونده دارن) که اونها هم ظاهرا توی وب کارایی ندارن, نمونش وارد کردن اعداد فارسی تو وب.
راستش صابرجان یادم نیست ولی انگار قبلا این کارو(لیگیچر کردن با فاصله) یه جایی انجام دادم. البته تو مرورگر کروم اصلا جواب نمیده
نه صالح جان منظورم حذف فاصله اضافی به صورت خودکار نیست، کما اینکه فکر میکنم این کار ممکنه باعث بروز اشتباهاتی هم بشه، مثل عبارت زیر:
سُربی کمرنگ
منظور من لیگیچر کردن و تبدیل غلطهای املایی مثل «بیمه ی عمر» به فرم درستشون «ﺑﻴﻤﮥ عمر» به صورت خودکار بود. البته من جواب نگرفتم

**Comment by rastikerdar** [comment]
با توجه به توضیحات خوب و کامل آقای سوزنچی فکر می‌کنم تکلیف موارد روشن شد. با اجازه من ایشو رو می‌بندم.

**Comment by typoman** [comment]
> منظور من لیگیچر کردن و تبدیل غلطهای املایی مثل «بیمه ی عمر» به فرم درستشون «ﺑﻴﻤﮥ عمر» به صورت خودکار بود. البته من جواب نگرفتم

درست کردن غلط املایی از طریق فونت یک اشتباه بزرگه. خیلی مواظب باش که اینکارو نکنی که باعث مشکلات بعدی خواهد شد.

**Comment by zoghal** [comment]
> 
> 
> > منظور من لیگیچر کردن و تبدیل غلطهای املایی مثل «بیمه ی عمر» به فرم درستشون «ﺑﻴﻤﮥ عمر» به صورت خودکار بود. البته من جواب نگرفتم
> 
> درست کردن غلط املایی از طریق فونت یک اشتباه بزرگه. خیلی مواظب باش که اینکارو نکنی که باعث مشکلات بعدی خواهد شد.

اشتباه بزرگ هم کمه، اصلا خود خیانت به بشیریت هست🤨
