### ISSUE TITLE
How do Delete English Number?

### ISSUE THREAD

**Issue by MohMehrnia** [rastikerdar/vazir-font#99]
Please upload vaziri FD source.

**Comment by zoghal** [comment]
درود بر شما
در حالت کلی شما می‌تونید از نسخه بدون انگلیسی استفاده نمایید و نیاز به حذف اعداد نیست.
مگر نیاز خاصی مد نظرتان باشد. لطفا کمی بیشتر توضیح دهید تا شاید بتوانیم کمکتان کنیم.

**Comment by MohMehrnia** [comment]
سلام و تشکر از پاسخ گویی شما
من در گذشته نرم افزاری های مختلفی برای این یک ارگان تدوین و پیاده سازی نموده ام و اخیرا در خصوص رفع برخی  مشکلات در خصوص چاپ گزارشات فونت وزیری را به کار گرفته ام، متاسفانه در این مجموعه اکثر رایانه ها دارای قالب کیبورد عربی هستند و حرف ی به صورت ي و حرف ک نیز عربی است و امکان تغییر قالب کیبورد به دلیل تداخب به برخی نرم افزارها دیگر وجود ندارد. حال آیا این امکان وجود دارد که این دو حرف در نسخه فونت وزیری کلا حذف گردد. و به جای آنها از ی و ک فارسی استفاده گردد.
با عرض پوزش موضوع را اشتباها نوشته ام اصل موضوع مشکل در حروف عربی است.

**Comment by zoghal** [comment]
دوست عزیز کاملا متوجه مشکل شما شدم، اما چندتا نکته را خدمت شما عرض می‌کنم و امیدوارم باعث شود تغییر مسیر بدید از راهی که می‌خواهید پیش بگیرید.
بزرگترین مشکل ما ایرانی‌ها این هست که همیشه سعی می‌کنیم مشکلاتمون رو بصورت سطحی حل کنیم یا دنبال ساده‌ترین راه حل بگردیم تا فقط مشکل را موقت حل کنیم و هیچ نگاهی به آینده نداریم، متاسفانه عادت هم می‌کنیم مکررا کار اشتباه را تکرار کنیم :(

مشکلی که شما از آن صحب کردید کاملا صحیح است و من هم کم و بیش در پروژه‌های قدیمی خودم با آن درگیری دارم.

اما راه حل این مشکل تغییر واقعا در اعمال تغییرات در فونت نیست. فرض رو بگیرید روزی مجددا بخواهید یک فونت دیگر مثلا فونت [بهداد](http://libre.font-store.ir/BehdadFont/) من رو استفاده کنید. آیا بازهم می‌خواهید با تغییر در فونت این مشکل را حل کنید؟

من هم دلفی کار می‌کنم و هم وب، در هر دو حالت در پروژه‌های قدیمی هنگام نمایش محتوا با یک تابع کوچیک تغییرات مورد نیازم را اعمال می‌کنم. یعنی متن را به فرمت صحیح تغییر می‌دادم. و خیالم راحت است که دیگه اون نقطه زیر ي عربی رو نمی‌بینیم یا مشکل نمایش اعداد لاتین مواجه نخواهم شد.

امیدوارم شما نیز این راه را در پیش بگیرید. احیانا اگر مشکل خاصی در این مورد دارید ممنون می‌شوم با ما درمیان بگزارید تا ببینیم چه راهکاری می‌توان برای آن پیدا کرد.
با تشکر از شما
